### ISSUE TITLE
Please stop using the "docker" group

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/adb-atomic-developer-bundle#1]
At least `components/rhel-with-docker/docker-host/Vagrantfile` seems to.

See https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2015-January/msg00034.html

**Comment by langdon** [comment]
Unfortunately, I believe this is a change that would have to be made in the upstream docker provider ( https://github.com/mitchellh/vagrant/tree/master/plugins/providers/docker ) as the code there uses "docker" vs "sudo docker." However, I will look in to this issue to see if we can work around it.
