### ISSUE TITLE
Package containers inside the Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#101]
We need a way to package docker container image in the adb Vagrant box

**Comment by bexelbie** [comment]
#25 will be solved by this as this is a general case.

**Comment by LalatenduMohanty** [comment]
Closing this as this issue can tracked in https://github.com/projectatomic/adb-atomic-developer-bundle/issues/192 and seems duplicate.
