### ISSUE TITLE
[Doc] Instead of 'libvirt' it should be 'vagrant-libvirt' in readme

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#106]
Currently README contain below step to start adb vagrant box if we use libvirt provider

```
Fedora 22: dnf install libvirt 
Which should be *dnf install vagrant-libvirt*
$ vagrant up
Which should be *$ sudo vagrant up*
```

Because if we only have libvirt installed and try to do **vagrant up** then it will fail with below error

```
$ vagrant up --provide libvirt
The provider 'libvirt' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
$ rpm -qa libvirt
libvirt-1.2.13.1-3.fc22.x86_64
$systemctl status libvirtd.service 
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2015-10-21 06:57:57 EDT; 1h 9min ago
```

Please comment if I am missing something otherwise will correct it and send patch for same.

**Comment by LalatenduMohanty** [comment]
@praveenkumar  are u looking at https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.rst#2-install-vagrant ?

As I can see "yum/dnf install -y vagrant-libvirt vagrant" there.

**Comment by LalatenduMohanty** [comment]
@praveenkumar I see https://github.com/projectatomic/adb-atomic-developer-bundle#what-are-the-deliverables-and-how-do-i-get-it  
yeah, you can send a patch to point it to https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.rst#2-install-vagrant or equivalent 

Thanks
