### ISSUE TITLE
extend included info in adbinfo, i.e. openshift info

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/adb-atomic-developer-bundle#110]
to allow us to find what is the connection string for openshift I suggest we included as much info as possible in `vagrant adbinfo`.

For example:

```
OPENSHIFT_API_URL=https://10.1.2.2:8443
```

Might also be relevant to include username, if we won't support token access.

**Comment by LalatenduMohanty** [comment]
@praveenkumar  we are hardcoding the openshift IP address in the vagrantfile right? If so , it would be easy to patch vagrant-adbinfo . I have also raised an issue in https://github.com/bexelbie/vagrant-adbinfo/issues/26

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes we are hardcoding OSE IP address in vagrant file.
https://gist.github.com/praveenkumar/5f3cc1869d531619b5ae#file-vagantfile-L29

@maxandersen Right we should include access details to plugin.

**Comment by hferentschik** [comment]
> yes we are hardcoding OSE IP address in vagrant file

To be clear though, hard coding does not mean it is always the same IP. The user should be able to take a different private network IP as the one we are using per default.

**Comment by LalatenduMohanty** [comment]
Closing the issue here as it is addressed in https://github.com/projectatomic/vagrant-adbinfo/issues/26
