### ISSUE TITLE
adbinfo format should be windows compatible

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/adb-atomic-developer-bundle#112]
currently adb-info outputs lines in the format:

`export DOCKER_HOST=tcp://127.0.0.1:2379`

This won't work on Windows.

Thus if we run adbinfo on Windows it should output:

`setx DOCKER_HOST=tcp://127.0.0.1:2379`

**Comment by bexelbie** [comment]
Fixed in https://github.com/bexelbie/vagrant-adbinfo/pull/19
