### ISSUE TITLE
don't glob host machines 127.0.0.1:* ports

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/adb-atomic-developer-bundle#113]
could we make it so adb/cdk would not default to map services into 127.0.0.1 and instead use a specific ip - an ip that even could be dumped out in adbinfo as CDK_HOST or similar.

I would like to reduce the times users need to go via localhost with obscure port values instead of a proper ip/dns + sensible port values.

please note: the 127.0.0.1 here is the users machine host - we should _not_ require that to be used, but rather setup the CDK box to have its own IP.

**Comment by LalatenduMohanty** [comment]
@maxandersen I think it is fixed as part of https://github.com/LalatenduMohanty/adb-atomic-developer-bundle/commit/30176cb15230db874dc4035058a95763bd6c6449

**Comment by maxandersen** [comment]
Which IP will we expose on then ? Not following how 30176cb fixes this.

Related to https://github.com/projectatomic/adb-atomic-developer-bundle/issues/119

**Comment by hferentschik** [comment]
Docker should be accessed via the private network IP (no manual port forwards should be needed). I think we can resolve this issue.

**Comment by navidshaikh** [comment]
Filed issue in vagrant-adbinfo repo: https://github.com/projectatomic/vagrant-adbinfo/issues/39
Closing here.
