### ISSUE TITLE
Published ports for Docker containers should be accessible from the Host VM

### ISSUE THREAD

**Issue by xcoulon** [projectatomic/adb-atomic-developer-bundle#119]
Published ports for Docker containers (with the `-P` or `-p` flags) should be accessible form the Host VM, so the developer can connect with this client tools (typically, a Web browser) to connect to the application running in the container.

**Comment by maxandersen** [comment]
devex:interest

**Comment by hferentschik** [comment]
I think we can resolve this issue. Provided one access the CDK via the private network IP, container ports will be available. Same applies for #113

**Comment by LalatenduMohanty** [comment]
@maxandersen @hferentschik closing this as this is addressed by  https://github.com/projectatomic/vagrant-adbinfo/issues/33
