### ISSUE TITLE
We need to have single node k8s setup (but not as default) in the ADB Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#123]
PR #121 removes the default k8s single setup from the kick start file. As we need to support OpenShift container by default on the ADB Vagrant box. 

However we need to provide a way to do the single k8s setup if someone needs it. I have written a script [1] which can do that. 

However we need to findout what is the best way to include the script in the Vagrant box (may be as RPM).  Also we need to make documentation changes to reflect this.

[1] https://github.com/LalatenduMohanty/k8s-setup/blob/master/k8s-setup.sh

**Comment by LalatenduMohanty** [comment]
Another solution is a Vagrantfile which can do the setup for single node k8s https://gist.github.com/LalatenduMohanty/c95f01446493560f6d16

**Comment by praveenkumar** [comment]
@LalatenduMohanty So as per our last Wednesday meeting we agreed upon to have provision scripts for k8s/openshift in the box not using Vagrantfile.

**Comment by LalatenduMohanty** [comment]
@praveenkumar Yes, We want to go to a go a situation where we dont need these Vagrantfiles . But till we have the solution in place we can keep using the Vagrantfiles

**Comment by LalatenduMohanty** [comment]
Closing this issue as we have a Vagrantfile for single node k8s setup
