### ISSUE TITLE
Support OpenShift DNS entries on Windows

### ISSUE THREAD

**Issue by pmuir** [projectatomic/adb-atomic-developer-bundle#126]
When I run OpenShift in the CDK, and create applications, I need to be able to access them from my host. OpenShift uses name based routing (via HAProxy). These names need to be resolvable from my host.

**Comment by praveenkumar** [comment]
We are targeting to use landrush for this purpose. It works in MAC without any issue and for Linux (Virtualbox provider) we have to configure dnsmasq to make it work.

**Configuration dnsmasg**
➜ Add the following to /etc/dnsmasq.conf:
   listen-address=127.0.0.1
➜ cat /etc/dnsmasq.d/vagrant-landrush 
server=/.vm/127.0.0.1#10053
➜ sudo systemctl start dnsmasq.service 
➜ sudo systemctl status dnsmasq.service 

_If it is fail then we can fix it by telling system dnsmasq to bind to specific interfaces. Open the  /etc/dnsmasq.conf again and list only the interfaces you need (and don’t conflict with libvirt specific interfaces)_

➜ Add the following to /etc/dnsmasq.conf
interface=enp0s25
bind-interfaces

➜ Make sure put '127.0.0.1' as nameserver to /etc/resolve.conf (Make sure you have 127.0.0.1 placed at first place in resolve.conf)

```
$ cat /etc/resolv.conf
nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 4.4.4.4
```

➜ Vagrant file snip to enable landrush

```
PUBLIC_ADDRESS=10.1.2.2
PUBLIC_HOST= adb.vm
config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"
config.vm.hostname = "#{PUBLIC_HOST}"
config.landrush.enabled = true
config.landrush.host_ip_address = "#{PUBLIC_ADDRESS}"
config.landrush.tld = ".vm"
confg.landrush.guest_redirect_dns = false
```

➜  vagrant landrush ls

```
adb.vm           10.1.2.2
2.2.1.10.in-addr.arpa            adb.vm
```

➜ Check listen port status

```
$ sudo netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:17500           0.0.0.0:*               LISTEN      2946/dropbox        
tcp        0      0 10.65.193.61:44319      0.0.0.0:*               LISTEN      14810/weechat-curse 
tcp        0      0 127.0.0.1:17600         0.0.0.0:*               LISTEN      2946/dropbox        
tcp        0      0 127.0.0.1:45186         0.0.0.0:*               LISTEN      433/GoogleTalkPlugi 
tcp        0      0 127.0.0.1:39715         0.0.0.0:*               LISTEN      433/GoogleTalkPlugi 
tcp        0      0 127.0.0.1:17603         0.0.0.0:*               LISTEN      2946/dropbox        
tcp        0      0 0.0.0.0:10053           0.0.0.0:*               LISTEN      14966/ruby-mri      
tcp        0      0 127.0.0.1:2222          0.0.0.0:*               LISTEN      15200/VBoxHeadless  
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      16871/dnsmasq       
tcp        0      0 192.168.121.1:53        0.0.0.0:*               LISTEN      16817/dnsmasq       
tcp        0      0 192.168.124.1:53        0.0.0.0:*               LISTEN      16810/dnsmasq       
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2647/cupsd          
tcp6       0      0 ::1:631                 :::*                    LISTEN      2647/cupsd          
```

➜ Test out app route after deployment

```
$ ping adb.vm
PING adb.vm (10.1.2.2) 56(84) bytes of data.
64 bytes from 10.1.2.2: icmp_seq=1 ttl=64 time=0.332 ms
64 bytes from 10.1.2.2: icmp_seq=2 ttl=64 time=0.238 ms

[vagrant@adb ~]$ oc get routes
NAME             HOST/PORT                       PATH      SERVICE          LABELS                                       INSECURE POLICY   TLS TERMINATION
nodejs-example   nodejs-example-default.adb.vm             nodejs-example   app=nodejs-example,template=nodejs-example                     
[vagrant@adb ~]$ exit
logout
Connection to 127.0.0.1 closed.

[prkumar@localhost adb2_ose]$ ping nodejs-example-default.adb.vm
PING nodejs-example-default.adb.vm (10.1.2.2) 56(84) bytes of data.
64 bytes from 10.1.2.2: icmp_seq=1 ttl=64 time=0.217 ms
64 bytes from 10.1.2.2: icmp_seq=2 ttl=64 time=0.169 ms
64 bytes from 10.1.2.2: icmp_seq=3 ttl=64 time=0.136 ms
```

**Comment by hferentschik** [comment]
Here is a pull request for Landrush making it work on all OSes (OS X, Windows, Linux).

**Comment by praveenkumar** [comment]
@hferentschik I think you forgot to provide PR link or I am missing something?

**Comment by hferentschik** [comment]
@praveenkumar LOL, indeed. Here it is https://github.com/phinze/landrush/pull/154

**Comment by LalatenduMohanty** [comment]
Moving it to ADB 2.1 as we are not planning to use landrush for ADB 2.0

**Comment by hferentschik** [comment]
Ok, Landrush 1.0.0 is released now. We could switch the default Vagrant file to make use of it. 

There is still a manual step required to configure visibility on the Windows host, but the Landrush DNS server works fine now. Probably should get into the next public release of ADB/CDK, since the xip.io solution proved to be quite unreliable.

**Comment by LalatenduMohanty** [comment]
@hferentschik We also need documentation about how users can use landrush with adb-utils move to use landrush.

**Comment by hferentschik** [comment]
@LalatenduMohanty we don't only need documentation, but I also suggest to use Landrush as the default in the _Vagrantfile_. Which means the landrush gem needs to be added as well, etc.

We need a bit of planning here what we should get into the next release of ADB/CDK. The folder synv via sshfs should go in as well together with the removal of the /vagrant folder. This needs some planning and scheduling in particular in relation to a new public CDK release.

**Comment by LalatenduMohanty** [comment]
This is fixed by https://github.com/projectatomic/adb-atomic-developer-bundle/pull/462
