### ISSUE TITLE
RHEL Vagrantfiles are missing

### ISSUE THREAD

**Issue by langdon** [projectatomic/adb-atomic-developer-bundle#133]
Please add the vagrantfiles to support the adb for a RHEL vm back to the repo

**Comment by LalatenduMohanty** [comment]
As discussed with @whitel , we will add the vagrantfiles  from CDK 2.0

**Comment by praveenkumar** [comment]
@LalatenduMohanty is this already done?

**Comment by LalatenduMohanty** [comment]
@praveenkumar nope, I think we should wait for GA of CDK 2.0

**Comment by praveenkumar** [comment]
@LalatenduMohanty Alright, My understanding was that to include beta Vagrantfiles also but we can wait till GA.

**Comment by LalatenduMohanty** [comment]
https://github.com/projectatomic/adb-atomic-developer-bundle/pull/263 fixes this issue
