### ISSUE TITLE
Should we include the "oc" binary in ADB?

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#134]
CC @maxandersen

**Comment by maxandersen** [comment]
to be clear, the suggestion is to include the oc client binary for windows, OSX and linux into CDK so we can get to interact with openshift/kube without installing additional platform binaries.

**Comment by maxandersen** [comment]
can you add focus:devex to this ?

**Comment by hferentschik** [comment]
+1 to this and I might even go one step further and put the client libs into the Docker image. This way it would be guaranteed that server and cli tools are aligned.

**Comment by praveenkumar** [comment]
@maxandersen oc  and oadm binary is already part of our CDK box when we use OSE vagrantfile for setup or you want something different?

https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/Vagrantfile#L109

>  I might even go one step further and put the client libs into the Docker image. This way it would be guaranteed that server and cli tools are aligned. 

@hferentschik Did you mean 'oc/oadm' clients libs to origin image? If yes then I think it's already there.

**Comment by hferentschik** [comment]
AFAIU, the Linux client libs are there. And yes, they are in the CDK and the Openshift container image. What we are talking about here is to include the client libs for all three OS types - Linux, Windows, OS X. They can be made available in a known location in the image or on the CDK VM. 

In our use cases we want the user to be able to do as much as possible directly from the host. Interact with Docker, but also with Openshift. To do the latter we need the _oc_ and _oadm_ libraries for the host OS. Also for some functionality (log streaming for example) also the Eclipse tooling requires a local client lib. 

If the OS specific version is not bundled with the CDK or Openshift image, the user needs to download them separately, potentially having the problem of finding the correct version. I guess the developer tooling installer can include the CLI tools as well, but even there we need a location to get them from.

**Comment by praveenkumar** [comment]
> In our use cases we want the user to be able to do as much as possible directly from the host. Interact with Docker, but also with Openshift. To do the latter we need the oc and oadm libraries for the host OS. Also for some functionality (log streaming for example) also the Eclipse tooling requires a local client lib. 

Yes agreed, It make sense for host (I was confused with CDK box). In our earlier discussion we agreed that in a zip file which we ship currently (have vagrantfile for different use-case) also include those binaries so user will easily get those.

**Comment by hferentschik** [comment]
> In our earlier discussion we agreed that in a zip file which we ship currently (have vagrantfile for different use-case) also include those binaries so user will easily get those.

+1 makes sense (to have them in the zip as well). The question here is also where to get the right client lib from and how to keep it in sync. Say one updates the OpenShift version used within the CDK, how would you make sure that you also are in sync with  the client lib. From that perspective it would be nice if the OSE container would include them and one could copy them out from there.

**Comment by bexelbie** [comment]
docker and kubectl too

**Comment by praveenkumar** [comment]
> Say one updates the OpenShift version used within the CDK, how would you make sure that you also are in sync with the client lib. From that perspective it would be nice if the OSE container would include them and one could copy them out from there.

@hferentschik  Let me understand correctly so if a user update OpenShift version using it's updated container and then client libs should sync with CDK box (not with host) provided we included those libs to container image. 
I was more concerned about providing client binary for host.

> docker and kubectl too

I was just looking windows 'docker-client' binary and seems it's unofficial maintained (https://chocolatey.org/packages/docker) so those details we can put in doc section instead of putting it to zip file( we provide which version of docker-daemon we are using and user can install specific client binary). For kubectl binary I checked (https://github.com/eirslett/kubectl-windows) may be we have to build ourself for specific version and then add to zip.

Thoughts?

**Comment by maxandersen** [comment]
isn't oc a superset of kubectl anyway and docker cli does not (yet) work on windows.  

I would focus on openshift oc binaries first, at least lets not hold this back to wait for having builds of docker and kubectl.

And about getting the right content to the users host, then yeah, I would assume the user runs a script (maybe a vagrant-plugin?) to copy updated binaries to his host system to get the updated client libs.

**Comment by hferentschik** [comment]
> I was more concerned about providing client binary for host.

sure, me too. Even though for the CDK VM it would make sense as well I guess. Regardless where the binaries are, from the CDK VM or even from the Openshift docker image, the user needs to know how to get these binaries to the host. This can just be documented or, even better, as @maxandersen says be part of a vagrant plugin. `adbinfo` comes to mind which should be renamed either way. The beauty of the plugin is that it can figure out the host OS and copy automatically the right binaries.

**Comment by hferentschik** [comment]
In this context - https://github.com/projectatomic/vagrant-adbinfo/issues/37 and https://github.com/projectatomic/vagrant-adbinfo/issues/54

**Comment by bexelbie** [comment]
@praveenkumar official docker binaries are here: https://github.com/docker/docker/releases

Do we really need to rebuild these for Mac and Windows?

**Comment by praveenkumar** [comment]
I have 2 options to resolve it, let me know which one is most suitable to close this issue.

Option-1. We are now using specific version/tag for OpenShift instead of master and we are in good position to provide openshift client libs download url for different OS (https://github.com/openshift/origin/releases)

Option-2. We include a suboption to `adbinfo` side and download OS specific version of client libs (adbinfo should first figure out which version of origin currently running in vagrant box) 

Same we can do for docker since @bexelbie provided release link which have OS specific binaries.

**Comment by hferentschik** [comment]
+1 for option 2. I think this is by far the nicest.

**Comment by navidshaikh** [comment]
> dbinfo should first figure out which version of origin currently running in vagrant box

@praveenkumar : is there a way to get the version of origin running ? like `curl`ing the API or checking the container image's tag, etc?

**Comment by hferentschik** [comment]
`docker inspect -f '{{.Config.Image}}' ose` maybe!? Gives you the image name and version

**Comment by praveenkumar** [comment]
https://github.com/projectatomic/vagrant-service-manager/issues/90 filled for it and @budhrg working on it.

**Comment by LalatenduMohanty** [comment]
Lets close it in ADB as it is tracked in https://github.com/projectatomic/vagrant-service-manager/issues/90
