### ISSUE TITLE
$(vagrant adbinfo) is not working in shell due to leading comments

### ISSUE THREAD

**Issue by maxandersen** [projectatomic/adb-atomic-developer-bundle#135]
This related to #111 

Running adbinfo 0.9 I do the following (from the dir of the CDK vagrant instance):

```
~/c/c/openshift-vagrant git:master ❯❯❯ export DOCKER_HOST="blah"
~/c/c/openshift-vagrant git:master ❯❯❯ echo $DOCKER_HOST
blah
~/c/c/openshift-vagrant git:master ❯❯❯ eval $(vagrant adbinfo)
~/c/c/openshift-vagrant git:master ❯❯❯ echo $DOCKER_HOST
blah
~/c/c/openshift-vagrant git:master ❯❯❯ eval $(docker-machine env default)
~/c/c/openshift-vagrant git:master ❯❯❯ echo $DOCKER_HOST
tcp://192.168.99.100:2376
```

notice how eval of vagrant adbinfo has no effect on my environment (it stays 'blah') but docker-machine env default works.

The only difference I can spot between docker-machine and adbinfo is that it opposite to what was suggested in #111 adbinfo have comments to start with.

And when I actually strip the comments it works.

i.e.

```
~/c/c/openshift-vagrant git:master ❯❯❯ export DOCKER_HOST="blah"                                                                                            ⏎
~/c/c/openshift-vagrant git:master ❯❯❯ echo $DOCKER_HOST
blah
~/c/c/openshift-vagrant git:master ❯❯❯ eval $(vagrant adbinfo | tail -n +3)
~/c/c/openshift-vagrant git:master ❯❯❯ echo $DOCKER_HOST
tcp://:2376
```

note: the missing host in adbinfo is a seperate issue (#136)

But as you notice vagrant adbinfo will not actually change the environment unless it put comments at the end.

**Comment by maxandersen** [comment]
note, turns out doing `eval "$(vagrant adbinfo)"` does work.

So it is not a blocker but seems it would be a nice polish not having to require quoting

**Comment by hferentschik** [comment]
So why would you run w/o quotes anyways, adbinfo as well as docker-machine show the command with quotes:

```
# eval "$(vagrant adbinfo)"
```

resp.

```
# eval "$(docker-machine env default)"
```

You need to prevent word splitting of the variable passed to eval.

That said, the difference here are the the empty lines:

adbinfo:

```
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:

export DOCKER_HOST=tcp://10.1.2.2:2376
export DOCKER_CERT_PATH=/Users/hardy/work/developer-platform/openshift-vagrant/cdk-v2/.vagrant/machines/default/virtualbox/.docker
export DOCKER_TLS_VERIFY=1
export DOCKER_MACHINE_NAME=45e2078

# run following command to configure your shell:
# eval "$(vagrant adbinfo)"
```

compared to

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/hardy/.docker/machine/certs"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval "$(docker-machine env default)"
```

I reckon removing the empty lines will do the trick and +1 for doing this, but using this command w/o the quotes is asking for trouble and not recommended.

**Comment by hferentschik** [comment]
The issue should really be moved to here - https://github.com/projectatomic/vagrant-adbinfo

**Comment by navidshaikh** [comment]
Thank you @maxandersen for pointing this out and @hferentschik for the insight on evaluation of environment variables. Copied the issue at vagrant-adbinfo repo https://github.com/projectatomic/vagrant-adbinfo/issues/48
