### ISSUE TITLE
Provide service scripts to control OpenShift on the VM

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#140]
Currently OpenShift can be using on the ADB VM using Vagrant provisioning. See #66 and the `Vagrantfile` provided via #ab4e2e3. 

There is no easy way for a user in this case to control (start/stop/reload) OpenShift apart of re-provisioning which is not intuitive. It also exposes a lot of low level details to the user.

A better approach would be to pull the required scripts into the VM itself and provide systmctl control scripts, so that OpenShift becomes a service like Docker. The creation of templates and users could still be done via Vagrant, since this might be user specific. The creation of a registry lies somewhere in between. Personally I think it could also be done as part of service scripts, since OpenShift is pretty much unusable without it.

Similar to the Docker service scripts, the OpenShift service script should define custom extension points for things a user most likely wants to change, eg the default route name.

In the Docker service configuration there are custom variables like `INSECURE_REGISTRY` and `ADD_REGISTRY` which are only used by the sysyemctl scripts and which modify the Docker daemon options if set.

**Comment by hferentschik** [comment]
Please add label focus:devex

**Comment by praveenkumar** [comment]
I started working towards it but still in very early stage and have to figure out some options before merge it to main repo.

https://github.com/praveenkumar/adb-atomic-developer-bundle/tree/origin_service/components/centos/centos-with-openshift/service-script

**Comment by hferentschik** [comment]
> I started working towards it but still in very early stage 

Nice.

> and have to figure out some options before merge it to main repo.

I'll try to have a look and see how it works for our use case.

**Comment by navidshaikh** [comment]
Having systemd service for OpenShift in the box should help identify if service is up and running in standard way, this in turn helps adbinfo plugin to check the service status and accordingly display connection information related: https://github.com/projectatomic/vagrant-adbinfo/issues/26

**Comment by LalatenduMohanty** [comment]
Closing this as this issue is handled in https://github.com/projectatomic/adb-utils/issues
