### ISSUE TITLE
Need documentation for building an Atomic App example using ADB

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#141]

**Comment by praveenkumar** [comment]
@bexelbie Doesn't we have it now? If it is running a atomicapp example then we already have some tested app which can be included in doc. ( #185 )

**Comment by bexelbie** [comment]
@praveenkumar I believe we may have some examples we can use to build an app, but we still need to document the workflow.

**Comment by LalatenduMohanty** [comment]
@thatdocslady  closing this as we are focusing on OpenShift now.
