### ISSUE TITLE
Need documentation for Eclipse integration with ADB

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#142]

**Comment by LalatenduMohanty** [comment]
CC @bexelbie @navidshaikh

**Comment by LalatenduMohanty** [comment]
basically we need more documentation about how we can use ADB for http://tools.jboss.org/features/dockertools.html

**Comment by rctrh** [comment]
A somewhat more fundamental, and general topic is "Using docker (and other) tooling from outside the Vagrant box". 

My current understanding of the Eclipse piece in ADB is to establish the connectivity to the docker engine inside the Vagrant box for the Eclipse plugin.  (Though really that would be any docker tooling running on the (physical) host system.)

Beyond the demos, a developer using the ADB from a host system is going to need a slightly better understanding of the networking and what's going in the Vagrantfiles, eg port forwarding 2379 in the eclipse VF vs. exposing the box's network in the OSE VF.

**Comment by LalatenduMohanty** [comment]
@rctrh agree . Some documentation about using docker from host has been added at https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-the-box-from-the-host
Let us know how it looks to you

**Comment by LalatenduMohanty** [comment]
Some documentation exist in the testing repo https://github.com/projectatomic/adb-tests/tree/master/adb-testing

**Comment by bexelbie** [comment]
Fixed in #161
