### ISSUE TITLE
Time out during vagrant up but it still starts

### ISSUE THREAD

**Issue by mmalina** [projectatomic/adb-atomic-developer-bundle#147]
Even with the fix from #128 I still get a time out during vagrant up, but this is probably something else.
I have seen this before even in instances where that other issue didn't happen. I'm on OS X and am using the build from December 11 through https://github.com/redhat-developer-tooling/openshift-vagrant .
See here:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
==> default: Registering box with vagrant-registration...
==> default: Rsyncing folder: /Users/rasp/git/openshift-vagrant/cdk-v2/ => /vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

**Comment by LalatenduMohanty** [comment]
@mmalina thanks.  I think the timeouts are coming because the dhcp server for the guest is taking time to respond.  However will take a look

```
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty @mmalina this log doesn't prove any timeout issue. Below log section is always there because sshd takes few second to come up. (Not dhcp issue). This you will also get with centos/fedora base box also IIRC.

```
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar I think you might be right. 

Just checked the CentOS vagrant box (vagrant init centos/7) on libvirt , I dont see timeout 

```
[root@dhcp35-203 C7]# vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              C7_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          centos/7
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/C7_default.img (41G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Installing rsync to the VM...
==> default: Rsyncing folder: /home/C7/ => /home/vagrant/sync
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty  yes because when we are using libvirt provider it actually waiting for ssh to become available.

```
==> default: Waiting for SSH to become available...
```

**Comment by hferentschik** [comment]
> I'm on OS X and am using the build from December 11 through https://github.com/redhat-developer-tooling/openshift-vagrant .

Did you delete the cached VM via `vagrant box remove cdk_v2` to make sure the latest box is even downloaded? I am on OS X as well and in its current config redhat-developer-tooling/openshift-vagrant has not been timing out anymore.

I think it is still possible to see the warnings `default: Warning: Remote connection disconnect. Retrying...`, at least I do on Windows. However, this should just appear a couple of times and then proceed with the bootstrap. Even on Windows I can now start the VM on each `vagrant up`.

**Comment by mmalina** [comment]
@hferentschik yes, I used vagrant box remove and destroy and then downloaded the new box during vagrant up.

I agree that it starts up every time now. But I can see this time out (one or two) every time and so does @rhopp on Fedora.

When I tried vagrant up with logging set to info, I saw that it tried to connect via ssh many times:

```
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/Users/rasp/git/openshift-vagrant/cdk-v2/.vagrant/machines/default/virtualbox/private_key"]
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHDisconnected: The SSH connection was unexpectedly closed by the remote end. This
usually indicates that SSH within the guest machine was unable to
properly start up. Please boot the VM in GUI mode to check whether
it is booting properly.>
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "2055f2de-ba4f-49c7-a6b8-7479166b59af", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "2055f2de-ba4f-49c7-a6b8-7479166b59af", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
```

This would repeat many times until eventually it says:
 INFO ssh: SSH is ready!
With the info logging there is no warning there.

**Comment by hferentschik** [comment]
> I agree that it starts up every time now. 

So what is the problem? 

> But I can see this time out (one or two) every time and so does @rhopp on Fedora.

You mean:

`default: Warning: Connection timeout. Retrying...`

If so, I think this is perfectly normal. It is a warning after  all. The issue was that this warning would appear ~20 times and then an actual error would occur. Vagrant will try to ssh into the VM and depending on how fast the VM boots, there might be a couple of warnings printed. This might depend on how fast your machine is as well as what the VM does prior to accepting ssh connections. So, I am not quite sure what you are asking here.

**Comment by mmalina** [comment]
@hferentschik the problem is that there is a warning every single time. A warning should warn a user of something going slightly wrong. Perhaps something that the user has done wrong. At least that's my opinion. So what I'm asking here is to fix it so that either a more benevolent time out is given or some other mechanism is employed so that a warning is not displayed every time (for me and @rhopp).

But of course it's up to you all to decide if you accept this as a bug or not :)

**Comment by hferentschik** [comment]
> the problem is that there is a warning every single time.

Sure, but that's not only the case for the ADB VM. If anything it is a Vagrant "issue". Maybe they should have made this an info message.

> A warning should warn a user of something going slightly wrong

Exactly what happens here. Something goes slightly wrong. Vagrant tries to connect via ssh, but the VM is not ready. There is a `config.vm.boot_timeout` one can set in the `Vagrantfile`, but that only effects when the actual timeout occurs. I don't think it has any influence on how often and when Vagrant tries to ssh to the machine.

> So what I'm asking here is to fix it so that either a more benevolent time out is given

I don't think we can

> some other mechanism is employed so that a warning is not displayed every time 

Note, from the perspective of Developer Tooling this is probably even less an issue, since one would control the vagrant up/down via the Eclipse plugin. Not sure whether the plugin displays the output of the vagrant boot. If it does, one could do something there, but even that is questionable imo.

As part of this project I am not sure there is much we can do here. I vote to close the issue.

**Comment by praveenkumar** [comment]
> There is a config.vm.boot_timeout one can set in the Vagrantfile, but that only effects when the actual timeout occurs. I don't think it has any influence on how often and when Vagrant tries to ssh to the machine.

Yes, it's depend on vagrant retry to ssh a machine and it's depend on host configuration also so setting a config.vm.boot_timeout may not resolve this issue.

> As part of this project I am not sure there is much we can do here. I vote to close the issue.

+1 to close this issue (If in future we find some other relevant solution then we can look)

**Comment by mmalina** [comment]
OK, fine, it seems there is not much that can be done to fix this.

> Note, from the perspective of Developer Tooling this is probably even less an issue, since one would control the vagrant up/down via the Eclipse plugin. Not sure whether the plugin displays the output of the vagrant boot. If it does, one could do something there, but even that is questionable imo.

Yes, CDK tooling in Eclipse will show the full console output of the vagrant up command, so users will see the same warning there if present.

**Comment by hferentschik** [comment]
>  CDK tooling in Eclipse will show the full console output of the vagrant up command, so users will see the same warning there if present

Ahh, thanks. I did not know that.

**Comment by LalatenduMohanty** [comment]
Closing this as discussed above
