### ISSUE TITLE
ADB should also support single node Apache mesos setup

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#151]
ADB should also support single node  [Apache mosos](http://mesos.apache.org/) setup. So that users can create Atomic App for mesos provider.

**Comment by dharmit** [comment]
@bexelbie @LalatenduMohanty what do we need to solve this? I'm interested in getting this done.

If I understand correctly, we need to make sure that the Mesos and Marathon binaries are installed in the ADB vagrant box.

A point to note : Marathon listens on port 8080 and so does kube-apiserver (IIRC) or some other k8s service. But, I think, we are looking at a setup where we'll bundle the orchestration tools in the box and the user decides which one (s)he wants to enable and work with. Hence, less chances of port conflict out of the box.

Correct me wherever I am going off-track. I could be wrong as I haven't used ADB earlier. :smiley:

**Comment by bexelbie** [comment]
@dharmit You are correct.  I believe that we want to switch all of the orchestrators to services that can be enabled/disabled as needed by the user (ideally via vagrant adbinfo).  Therefore to solve this you would need a service that understands how to start Mesos and stop it.  Ideally it will also block other competing services from starting via systemd magic (magic :) ).  

Personally, I believe you should use a containerized Mesos, if that is possible to limit the amount of code directly installed in the box.  I don't know if that is practical at this stage though.

@praveenkumar @LalatenduMohanty Does this match your understanding of our conversations?
