### ISSUE TITLE
OpenShift registry and HAProxy images should be cached as well

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#160]
The VM caches the Openshift Docker image for faster startup of Openshift. Really it needs to cache the matching registry and HAProxy images as well.

**Comment by hferentschik** [comment]
Can we add label focus:devex, please.

**Comment by praveenkumar** [comment]
Then we need to cache a specific version/tag for Openshift also instead of using latest and same version we can cache for registry and HAProxy.

**Comment by hferentschik** [comment]
> Then we need to cache a specific version/tag for Openshift also instead of using latest

Absolutely, in fact using the latest is imo bad practice. It should be easy to "update" to the latest version, for example by setting a version attribute in some property/config file, but using the latest, can results in unexpected and hard to debug behavior for the user. The documentation should make clear which version is used and how to upgrade it.

> same version we can cache for registry and HAProxy. 

Absolutely and I think this is the right thing to do. Also I am not a big fan of tagging the image just _openshift3/ose _. Using `docker ps` it does not give you any indication which version you are running. The images which are then pulled afterwards are of the form _openshift3/ose-pod:v3.1.0.3 _ which in my opinion is much better. With a service script in place, there is no benefit in having a short name like _openshift3/ose _. IMO it would be much better to use a specific version.

Regarding caching, we need to find a solution one way or the other. I think the user would expect that after OpenShift is running, an application build can be started directly. Even though an application can be created, it will stay in pending state for a long time (downloading all the required images - router, registry, sti, ose-pod) without giving any feedback on what's going on.

**Comment by praveenkumar** [comment]
> Regarding caching, we need to find a solution one way or the other. I think the user would expect that after OpenShift is running, an application build can be started directly. Even though an application can be created, it will stay in pending state for a long time (downloading all the required images - router, registry, sti, ose-pod) without giving any feedback on what's going on.

Agreed, @LalatenduMohanty  do we have any provision in cbs to include docker images? (iirc when we started our build we didn't have that option I am wondering if that improved/added in between).

**Comment by LalatenduMohanty** [comment]
@praveenkumar nope. We cant do that in CBS . But we should be able to fix that in CDK builds

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes agreed, for CDK builds I will send a patch to kickstart with specific version.
@hferentschik So in CDK we are only going to use ship version of OSE (and relative components) and once we have same functionality to CBS then we can do it for ADB builds also.

**Comment by praveenkumar** [comment]
@hferentschik We have now OSE component containers are also cached (for CDK). Build available on our internal server (06-Jan). Please try out and let us know.

PS: Now size of vagrant box is around 955MB.

**Comment by hferentschik** [comment]
> Please try out and let us know

Will do, thanks.

**Comment by hferentschik** [comment]
Which images are you caching and where  (out of interest) is this actually done?

**Comment by hferentschik** [comment]
Ok, seems to work. I don't seem to see the `openshift3/ose-sti-builder` image cached. It is needed for doing any build using the templates really. I guess somewhere we need to draw a line on what to cache. Also the VM size needs to be watched.

**Comment by hferentschik** [comment]
How do you want to go about closing issues which are resolved in weekly scratch builds? Resolve them once verified or only resolve them once they are part of a proper release?

**Comment by praveenkumar** [comment]
> I don't seem to see the openshift3/ose-sti-builder image cached. It is needed for doing any build using the templates really.

I only cached images which are available once ose container is deployed (By default). Let me know if that is something really required. 

```
$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose-haproxy-router    v3.1.0.4            6a3fe65c07f1        3 weeks ago         410.5 MB
registry.access.redhat.com/openshift3/ose-deployer          v3.1.0.4            9580a28b3e18        3 weeks ago         395.6 MB
registry.access.redhat.com/openshift3/ose                   latest              62208f151337        3 weeks ago         395.6 MB
registry.access.redhat.com/openshift3/ose                   v3.1.0.4            62208f151337        3 weeks ago         395.6 MB
openshift3/ose                                              latest              62208f151337        3 weeks ago         395.6 MB
registry.access.redhat.com/openshift3/ose-docker-registry   v3.1.0.4            eb7a879607cf        3 weeks ago         419.9 MB
registry.access.redhat.com/openshift3/ose-pod               v3.1.0.4            758ab73ad286        3 weeks ago         327.4 MB

$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS               NAMES
65a93a81ac84        openshift3/ose-haproxy-router:v3.1.0.4    "/usr/bin/openshift-r"   31 minutes ago      Up 31 minutes                           k8s_router.4b3842e8_router-1-8ebd3_default_f0ec844c-b5c7-11e5-94cc-5254001dff69_f6e35ee1
b1beeb6965b2        openshift3/ose-pod:v3.1.0.4               "/pod"                   31 minutes ago      Up 31 minutes                           k8s_POD.da21dbf3_router-1-8ebd3_default_f0ec844c-b5c7-11e5-94cc-5254001dff69_c40f9a2f
5b37ac0f8b18        openshift3/ose-docker-registry:v3.1.0.4   "/bin/sh -c 'REGISTRY"   31 minutes ago      Up 31 minutes                           k8s_registry.4e8c17aa_docker-registry-1-bg2da_default_ea9b77a4-b5c7-11e5-94cc-5254001dff69_afc73b46
70ea87ffe7c1        openshift3/ose-pod:v3.1.0.4               "/pod"                   31 minutes ago      Up 31 minutes                           k8s_POD.3d2efd0c_docker-registry-1-bg2da_default_ea9b77a4-b5c7-11e5-94cc-5254001dff69_206b1adf
6b226e5ff45a        openshift3/ose                            "/usr/bin/openshift s"   32 minutes ago      Up 32 minutes                           ose
```

>  I guess somewhere we need to draw a line on what to cache. Also the VM size needs to be watched. 

Agreed, Can you make a list which should be cache (if something not required from current cache we can remove). VM size is also something we have to take care and currently I don't know what can be done.

> Resolve them once verified or only resolve them once they are part of a proper release?

I would go with first approach (resolve them + once verified)

**Comment by bexelbie** [comment]
I vote for resolved when verified in a non-scratch build (weekly or otherwise)

**Comment by hferentschik** [comment]
the one image I am missing for now is the `openshift3/ose-sti-builder`. It would be nice if it would be added. On the other hand, with the other images already cached it only takes a few seconds to download the image. Up to you guys.

> I vote for resolved when verified in a non-scratch build (weekly or otherwise)

Ok.

**Comment by praveenkumar** [comment]
> the one image I am missing for now is the openshift3/ose-sti-builder. It would be nice if it would be added. On the other hand, with the other images already cached it only takes a few seconds to download the image. Up to you guys.

Added. In process of creating non-scratch build (for CDK).

**Comment by praveenkumar** [comment]
I will keep this issue open till we have some good solution for ADB also.

**Comment by hferentschik** [comment]
I'd say, resolve this one and open a dedicated issues for solving the caching of images on ADB.

**Comment by LalatenduMohanty** [comment]
@hferentschik yeah . I was for CDK
