### ISSUE TITLE
Expose Kubernetes Service when Kube is running

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#169]
The ports for Kube need to be exposed in the Kube single node setup.

The environment variable needed should be passed by vagrant-adbinfo - 

see: https://github.com/projectatomic/vagrant-adbinfo/issues/58

**Comment by praveenkumar** [comment]
I think this is only vagrant file change (https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-k8s-singlenode-setup/Vagrantfile) to expose standard port of kube service. Or some other changes required for it?

**Comment by navidshaikh** [comment]
As part of the Kuberenetes, services `[etcd, kube-apiserver, kube-controller-manager, kube-scheduler]` run in the box, looking for these services in the box can indicate the adbinfo plugin about running Kubernetes (similar to starting and enabling OpenShift via systemd service).

**Comment by praveenkumar** [comment]
> The ports for Kube need to be exposed in the Kube single node setup.

@navidshaikh Apart from that port expose should happen in k8s vagrant file. And yes services which you listed make sure k8s running.

**Comment by LalatenduMohanty** [comment]
I think @bexelbie meant the code to do port forwarding or associate the kube services with the hostonly IP address of the Vagrant box

**Comment by LalatenduMohanty** [comment]
And we need a workflow with respect to , how the developer will use k8s from his laptop or workstation , @vpavlin any thoughts?

**Comment by bexelbie** [comment]
I believe this use case is simple enough that this is a great chance to develop the service model we have been talking about.  My understanding from the various conversations is that we want this:
- As simple of a vagrant file as possible.  Ideally a single line that tells the box to stop whatever provider is running and use kubernetes instead.
- A way for a developer to issue a vagrant adbinfo subcommand and start/stop kubernetes
  - This requires a way for vagrant adbinfo to easily call something (systemd unit file) to start/stop kubernetes
    - This requires that kubernetes be able to to detect if it should start (i.e. are conflicting providers running).  I believe this means we need a blocking infrastructure.
  - This requires a way for vagrant adbinfo to easily detect whether kubernetes is running and to easily get the required files, information, and environment variables for the user

This set up is simple enough that I think we can actually focus on the infrastructure.

**Comment by vpavlin** [comment]
@bexelbie Are you sure that adbinfo subcommand is a good way? (adb**info** doesn't imply it should control anything).

Maybe rework `adbinfo` to `adb info|provider|...`

But generally, yes - as simple Vagrantfile as possible, single command to switch providers.

Can't we just use API endpoints for checking whether the provider is running? e.g.
1. Is `...oapi/v1/...` reachable? Yes - OSv3 is running, No - continue
2. Is  `http://localhost:8080/api/v1/nodes` reachable? Yes - Kubes is running, No - continue
   ...

**Comment by praveenkumar** [comment]
> Can't we just use API endpoints for checking whether the provider is running? e.g.

@vpavlin API endpoints checks we can use to check provider status but if we want to run a provider then I think systemd unit file (run + provision)  is a way to go or we can include all scripts to adbinfo codebase for each provider but I don't know that is best way to go.

**Comment by LalatenduMohanty** [comment]
This is fixed by Vagrant service manager install-cli kuberenetes feature. Closing the issue.
