### ISSUE TITLE
Need documentation about  config.vm.network "private_network"

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#170]
Most of the Vagrantfiles for ADB uses the private_network.  If we put some documentation around, how it is useful for an user that would be good.

```
 config.vm.network "private_network", type: "dhcp"
```

**Comment by rct** [comment]
When do the docker certs get generated?

If the box's IP address changes, will the docker certs get regenerated to match the box's new IP address?

**Comment by rct** [comment]
Probably a separate issue, but there should be a mention of the docker TLS/certs bits that are going on under the covers. There is a bit of complexity there that I think users of the ADB will trip over at one point or another.  Maybe it just needs to be in an FAQ/Troubleshooting section.

(if there is anything documented I haven't found it yet.)
