### ISSUE TITLE
Use CI to check the sanity of the kickstartfiles for each pull request

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#174]
We can use ksvalidator command to check it.

```
$ sudo yum install system-config-kickstart

```

To validate the kickstart file run `ksvalidator <kickstart file>`
e.g. I have put a "xyz" string at the 2nd line of the file  

```
$ ksvalidator adb-atomic-developer-bundle/build_tools/kickstarts/centos-7-adb-vagrant.ks
The following problem occurred on line 2 of the kickstart file:

Unknown command: xyz
```

**Comment by praveenkumar** [comment]
We have this in place now https://github.com/praveenkumar/adb-atomic-developer-bundle/tree/origin_service -> https://travis-ci.org/praveenkumar/adb-atomic-developer-bundle Will send a PR for it. Also spell check now can be done across project and it will only look for .txt, .md, .rst format.

**Comment by praveenkumar** [comment]
It have now included to travis CI.
