### ISSUE TITLE
Use CI to do spell check for files under docs and readme for each pull request

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#175]
https://github.com/projectatomic/atomic-site  uses similar CI

**Comment by praveenkumar** [comment]
@LalatenduMohanty I didn't see any CI attached to `atomic-site` for us to use directly for our doc spell check purpose. I created a script (https://github.com/praveenkumar/adb-atomic-developer-bundle/blob/spell_check/src/spellcheck.py)  which do it well and can be added to CI. @bexelbie I would also like your input for this.

Also if we are going to use sphinx then it already provide plugin to do that (https://doughellmann.com/blog/2011/05/26/creating-a-spelling-checker-for-restructuredtext-documents/)

**Comment by LalatenduMohanty** [comment]
@praveenkumar the script looks fine to me (I have not tested it yet).

**Comment by bexelbie** [comment]
@LalatenduMohanty I have confirmed that the atomic-site CI does not spell check.  It only verifies that the site will build.  I think there are plusses and minuses to have a spell checker.  However, I believe we can wire one in and see how it goes.

Would we also like to see if we can enforce a "No Docs, No Commit" rule?

**Comment by bexelbie** [comment]
I played with the script a bit tonight.  It is a very chatty.  Can we get a more compressed output? Possibly with line numbers?  I also think the suggestions can be dropped.

**Comment by praveenkumar** [comment]
@bexelbie  I updated this script to display line number and dropped word suggestion. current output will be vim-favorable so you can directly open specific file which contain misspelled word on a particular line.

```
$ python spellcheck.py ../docs/
+128 ../docs/installing.rst : scl
$ vim +128 ../docs/installing.rst
```

**Comment by LalatenduMohanty** [comment]
@bexelbie @praveenkumar It is the https://github.com/projectatomic/container-best-practices project which has spell as travis CI. Sorry for not remembering the project name correctly

**Comment by praveenkumar** [comment]
We have this in place now https://github.com/praveenkumar/adb-atomic-developer-bundle/tree/origin_service -> https://travis-ci.org/praveenkumar/adb-atomic-developer-bundle Will send a PR for it. Also spell check now can be done across project and it will only look for .txt, .md, .rst format.
