### ISSUE TITLE
Re-evaluate packages for the ADB box

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#176]
I think we need to rethink if we need below packages for ADB because these packages does not fit to the objective of the project at this point.

```
@development
flannel
```

I dont think we need @development YUM group. Removing this will reduce the size of the Vagrantbox. Also flannel is required for overlay networking when we have Kubernetes cluster

**Comment by praveenkumar** [comment]
@LalatenduMohanty Let we make a scratch build after removing those and test if that works for our use-case as expected. We really need to shrink vagrant box size.

**Comment by tkdchen** [comment]
How about install packages during provision while `vagrant up`?
Can the build make a minimal installation with Minimal iso image?

**Comment by bexelbie** [comment]
+1 to testing without those.  I am concerned that flannel could be an upstream use case for Kube though

@tkdchen A design goal of the ADB is for it to be, as much as possible, a single download.  We are going to cache some docker images for the same reason.  Your suggestion is valid, but creates a long start up time, and a lot of network traffic if a cache isn't used.

**Comment by langdon** [comment]
Why not file a separate issue to create a 'simple vagrant box' as something available alongside the ADB for more generic use cases. This would also encourage people to file issues about other use cases we might want to have vagrant box support for. This issue can then remain focused on the package set required to make a developer immediately productive with containers.

**Comment by bexelbie** [comment]
Can we start by comparing the packages in a default ADB with an Atomic Host?

See also #190

**Comment by praveenkumar** [comment]
- [x] Check packages which can be removed.
- [x] yum clean all after provision.
- [x] Remove docs from `/usr/share/doc`
- [ ] Look out if any other better way?

**Comment by LalatenduMohanty** [comment]
Closing the issue as this is mostly fixed now.
