### ISSUE TITLE
Add a version file in ADB/CDK 

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#183]
A version file will help identify the version of the box and help adbinfo to provide the information as suggested in https://github.com/projectatomic/vagrant-adbinfo/issues/64
 The file name can be something like /etc/adb-version or /etc/adb-release

**Comment by praveenkumar** [comment]
+1 and file content can be

```
# cat /etc/adb-release
Atomic Developer Bundle (ADB) 2.0
```

**Comment by bexelbie** [comment]
I believe we should consider the way in which the addition of a marker for Atomic Host is being debated in https://bugzilla.redhat.com/show_bug.cgi?id=1200122

In short, I think we need to make a relatively clean way to identify both the base OS and version and ADB and version.  This pattern seems to be the one to follow.

**Comment by langdon** [comment]
Personally, I think it would be better to use the standard os-release model for this: http://www.freedesktop.org/software/systemd/man/os-release.html perhaps introducing a VARIANT_ID of ADB or something? Using something non-standard seems dangerous.

The problem with Atomic (and I am not sure why this bz is still not closed as it was resolved months ago IMO), is that it is not actually different in terms of content, just in terms of how you administer it. I liked the original proposal with atomic which was that it identified as Fedora, RHEL, or CentOS or whatever, but if you want to know if you could use yum, you tested for using yum.

**Comment by praveenkumar** [comment]
So as per `os-release` man page an operating system vendors may extend the file format and introduce new fields, for our use-case can we extend it and provide ADB/CDK version filed? something like below? We might have to append it in kickstart file.

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
ADB_PROJECT_VERSION="2.0"
```

**Comment by bexelbie** [comment]
+1 VARIANT + VARIANT_ID

However, 

@praveenkumar  if we follow your idea, s/ADB_PROJECT_VERSION/ADB_VERSION/

Can we find some examples of ways others have done this so we can make sure we are being somewhat "standard"?

**Comment by langdon** [comment]
The Fedora "editions" do something like this. See os-release in Fedora 23 Workstation.

**Comment by bexelbie** [comment]
In case not everyone is running F23:

$ cat /etc/os-release 
NAME=Fedora
VERSION="23 (Workstation Edition)"
ID=fedora
VERSION_ID=23
PRETTY_NAME="Fedora 23 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:23"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=23
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=23
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Comment by praveenkumar** [comment]
Also we can specify OpenShift version (because it is not deployed as rpm) so either someone have to parse docker images and extract OpenShift version or we can provide it in `os-release` file because anyway we put version info to kickstart file when caching the OpenShift images. Any opinion?

**Comment by bexelbie** [comment]
@praveenkumar I would like to see docker, openshift and other orchestrators have their versions collected by vagrant-adbinfo directly and not in /etc/os-release.  There is a use case from dev exp where those containers may get updated.

**Comment by praveenkumar** [comment]
@bexelbie Ah right, that something we discussed and slipped from my mind. Good to have in `adbinfo` plugin.
