### ISSUE TITLE
Test nulecule-library examples on ADB

### ISSUE THREAD

**Issue by dharmit** [projectatomic/adb-atomic-developer-bundle#185]
Try most examples on [nulecule-library](https://github.com/projectatomic/nulecule-library) on ADB.

**Comment by dharmit** [comment]
| Example | Docker | k8s | OpenShift | Remarks |
| --- | --- | --- | --- | --- |
| [flask-redis-centos7-atomicapp](https://github.com/projectatomic/nulecule-library/tree/master/flask-redis-centos7-atomicapp) | PASS | PASS | NA | None |
| [gitlab-centos7-atomicapp](https://github.com/projectatomic/nulecule-library/tree/master/gitlab-centos7-atomicapp) | PASS | PASS | NA | Requires more memory than default 512 MB |
| [gocounter-scratch-atomicapp](https://github.com/projectatomic/nulecule-library/tree/master/gocounter-scratch-atomicapp) | PASS | PASS | NA | None |
| [guestbook-go](https://github.com/projectatomic/nulecule-library/tree/master/guestbook-go) |  |  |  | Deferred since it requires kube-dns setup |
| [helloapache](https://github.com/projectatomic/nulecule-library/tree/master/helloapache) | PASS | PASS | NA |  |
| [mariadb-centos7-atomicapp](https://github.com/projectatomic/nulecule-library/tree/master/mariadb-centos7-atomicapp) | PASS | PASS | NA | NA |
| [mariadb-fedora-atomicapp](https://github.com/projectatomic/nulecule-library/tree/master/mariadb-fedora-atomicapp) |  | [Docker image not found](http://paste.fedoraproject.org/309388/18871145/) | NA | NA |
| [MLBParks](https://github.com/kadel/openshift3mlbparks/tree/nulecule-two-templates) |  | NA | PASS (CDKv2) | None |

**NA** under a provider (k8s/OpenShift) column indicates that app hasn't been tested under that provider yet.

**Comment by LalatenduMohanty** [comment]
Closing the issue as Nulecule is not the preferred work flow for ADB
