### ISSUE TITLE
Add vim to vagrant box.

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/adb-atomic-developer-bundle#190]
We should add vim (and possibly other tools that users would expect to be there) to the vagrant box.

**Comment by praveenkumar** [comment]
@dustymabe We are hoping, this box is used as connecting point for different services to host not to do any significant work inside the box. Adding more and more packages will increase size of the box also so we are little bit selective on what to include.

**Comment by langdon** [comment]
I think this comes down to: "do you expect people to be logging in directly to the vm?" or "do you expect people to treat it like a black box?"

Personally, I think a lot of the work in adb-2 has been to make the VM be treated more like a black box. As a result, I don't think this is a valid issue. However, that said, having some instructions for getting a docker container like rhel-tools installed which had all that stuff might be cool.

**Comment by dustymabe** [comment]
right. so for me I would be using it directly (perhaps a different use case than our target). I think if we exclude those people we would lose some potential users, but maybe not.

**Comment by langdon** [comment]
@dustymabe hence the idea of a container. I think that would be a super useful container anyway. So, you don't have it immediately, but it is a one line install.

**Comment by bexelbie** [comment]
+1 tools container, however I'd like to see what atomic ships by default as well.

**Comment by bexelbie** [comment]
See also #176

**Comment by LalatenduMohanty** [comment]
+1 for tools container. Closing the issue . Please reopen if you think vim should be shipped by-default.
