### ISSUE TITLE
Single node k8s vagrantfile gives error on libvirt

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#194]
While bringing up single node k8s setup on libvirt provider gives following error 

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
Error while setting up autostart on network: undefined method `autostart=' for nil:NilClass.
```

The issue comes because of the line "config.vm.network "private_network", type: "dhcp"" . This looks like an issue with vagrant-libvirt

**Comment by LalatenduMohanty** [comment]
CC @bexelbie

**Comment by praveenkumar** [comment]
@LalatenduMohanty, @bexelbie This issue is fixed in v0.32 for vagrant-libvirt and updated package is available http://koji.fedoraproject.org/koji/buildinfo?buildID=691847 (by @strzibny) . We might have to document it and make sure user suppose to use updated version of vagrant-libvirt plugin.

**Comment by navidshaikh** [comment]
We have the workaround documented however the actual fix would be to have the latest package built for Fedora 22 and 23.

**Comment by LalatenduMohanty** [comment]
I think we should package vagrant-libvirt for cdk

**Comment by praveenkumar** [comment]
@LalatenduMohanty updated package already in testing repo (f23/epel) so time being it would be good to have in doc section and later we will remove it.

**Comment by praveenkumar** [comment]
Can some of us give it a try  with latest version of vagrant-libvirt plugin (available with f23 and f22) and then close this issue? 
Note: I did testing for f23 and this issue is fixed.

**Comment by bexelbie** [comment]
I agree with @praveenkumar that we should be providing karma/etc. to get this available in the right places and not just repackaging it.  @preeticp and I updated her version on RHEL to the latest CentOS SCLO and it works.  I also believe we can close this issue now.

**Comment by LalatenduMohanty** [comment]
@bexelbie agree
