### ISSUE TITLE
RFE: Increase the default RAM to 1GB for the Vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#21]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Friday May 08, 2015 at 14:19 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/7_

---

Currently the default RAM is 512MB. We need to increase it to 2GB at least.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Friday May 08, 2015 at 16:40 GMT_

---

https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/pull/8 should fix the issue

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Friday May 08, 2015 at 19:31 GMT_

---

Also I need to find out how users will get the modified Vagrantfile when they use the image from https://atlas.hashicorp.com/lalatendum/boxes/nulecule-dev

That means `vagrant init lalatendum/nulecule-dev` should get the modified Vagrant file.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbsingh](https://github.com/kbsingh)**
_Tuesday May 12, 2015 at 10:32 GMT_

---

2GB seems excessive, can we start with 1GB and see if the problems are resolved. Atleast on my laptop, I only have 8GB of ram and dont want to lose 2GB to the vagrant process unless I really haveto. Do you know why the request went from 1GB to 2GB ?

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Monday Aug 03, 2015 at 18:35 GMT_

---

I found out that we can change the default RAM of the box while building the box in Koji/image factory 

"koji -p cbs image-build --help" 
 params = ['ovf_cpu_count','ovf_memory_mb','ovf_name',
'rhevm_default_display_type','rhevm_description','rhevm_os_descriptor',
'vsphere_product_name','vsphere_product_vendor_name','vsphere_product_version',
                      'vsphere_virtual_system_type',
                      'vagrant_sync_directory']

**Comment by langdon** [comment]
Honestly, I think a change in the "box creation" (as you propose) is a much better choice than trying to change it in the Vagrantfile (given that you have to do it per provider)

**Comment by LalatenduMohanty** [comment]
@whitel , I did test this, but the option is not making any difference. I have raised the issue https://github.com/redhat-imaging/imagefactory/issues/356
CC @imcleod

**Comment by bexelbie** [comment]
@LalatenduMohanty can you modify the build for virtualbox to use a 1GB build,  Modify the example libvirt VagrantFile to set this.  Finally, we should have documentation for how to modify this on a per instance basis for both providers.

**Comment by alberttwong** [comment]
I need at least 8 gb to show all the FIS and EAP demos (web servers, app servers, databases, esb + scaling) so that it's not slow.

**Comment by bexelbie** [comment]
@alberttwong can you reset it using the Vagrantfile?

**Comment by alberttwong** [comment]
Yes.   I was just posting to add another point of view.

**Comment by bexelbie** [comment]
@alberttwong Cool. We are looking at (in another PR I think) making this even easier to set

**Comment by LalatenduMohanty** [comment]
Closing this as Vagrantfiles are fixed now and Vagrantfiles are the interface to use ADB at this point.
