### ISSUE TITLE
There is no service reload for OpenShift service

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#213]
`$sudo systemctl reload openshift`
Failed to reload openshift.service: Job type reload is not applicable for unit openshift.service.

**Comment by hferentschik** [comment]
Please add label focus:devex

**Comment by hferentschik** [comment]
TBH, not sure whether it is really needed. Needs discussing.

**Comment by praveenkumar** [comment]
This issue was moved to projectatomic/adb-utils#5
