### ISSUE TITLE
Provisioning script does "too much" for a general purpose OpenShift setup

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#214]
`/opt/adb/openshift_provision` does some basic provisioning for OpenShift. It sets up the OpenShift registry as well as the router. However, it also does change the default permissions of OPenShift to allow to run any image. I think this goes too far. This should most likely be user driven.

The same applies for the imported templates and the created test-admin user. Both things are use-case specific and should be driven by user provisioning.

**Comment by hferentschik** [comment]
Please add label focus:devex

**Comment by praveenkumar** [comment]
This issue was moved to projectatomic/adb-utils#4
