### ISSUE TITLE
The OpenShift service creates an OpenShift instance with no authentication 

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#215]
I think is it not good practice to use an unauthenticated OpenShift. This is of course open for discussion, but I think one should at least use basic authentication.

One needs to also discuss whether an admin user should be pre-created.

**Comment by hferentschik** [comment]
Please add focus:devex

**Comment by praveenkumar** [comment]
This issue was moved to projectatomic/adb-utils#3
