### ISSUE TITLE
Increase startup time of OpenShift service

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#216]
ATM all the configuration of OpenShift occurs on the first startup of the service. This could be improved by doing everything upfront so that the VM and OpenShift is fully prepared.

Also instead of generating the Openshift config on the fly one might as well check it in and save some of the service "provisioning".

**Comment by hferentschik** [comment]
Please add label focus:devex

**Comment by praveenkumar** [comment]
This issue was moved to projectatomic/adb-utils#1

**Comment by praveenkumar** [comment]
This issue was moved to projectatomic/adb-utils#2
