### ISSUE TITLE
Marathon and mesos-slave are configured to localhost

### ISSUE THREAD

**Issue by kadel** [projectatomic/adb-atomic-developer-bundle#218]
these files should contain ip address of vagrant box

```
/etc/marathon/conf/hostname 
/etc/mesos-slave/ip
```

**Comment by dharmit** [comment]
@kadel Thanks for pointing this out. Will do the needful.

**Comment by kadel** [comment]
There is small problem how #221 was implementer. Because after changing config you still need to restart marathon and mesos-slave :-( 
I tried to fix that in #225
