### ISSUE TITLE
httpd-tools package should be present in kickstart file

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#222]
We require `httpd-tools` in our vagrant box because openshift provision require `htpasswd` utility which mentioned package provide to create authentication.

https://github.com/projectatomic/adb-utils/issues/3

**Comment by bexelbie** [comment]
@LalatenduMohanty @praveenkumar I believe this is creating a precedent that could complicate things in the future.  If a provider needs something, it should bring it in with a container.  Otherwise we are going to wind up potentially adding a lot of extra packages to support edge cases or getting into debates and use case validity.

What do you think?

**Comment by praveenkumar** [comment]
@bexelbie adding small packages (which required in provision steps) in a container will just increase size of the box. what I think better to include dev/development tools in a container and make sure it have dev-focus tools.

**Comment by bexelbie** [comment]
@praveenkumar Are you proposing a Dev tools container? If so, that seems to just be shifting this debate.

**Comment by praveenkumar** [comment]
@bexelbie No I was just referring to #190 and #176 , there also we discussed having a container which include required tools for different purpose. Now since we still have issue with centos side to cache docker images and `htpasswd` required during openshift provision I am not sure if we have _include it to container_ discussion for this issue. I better to reopen one on mentioned issue and then track the progress about what could be part of that super container.

**Comment by hferentschik** [comment]
I think this issue can be resolved. `htpasswd` is not installed on the VM, right? If we in the future need a different approach should be discussed in a new issue.

**Comment by praveenkumar** [comment]
> I think this issue can be resolved

Yes it is resolved. I am closing it now.

> `htpasswd` is not installed on the VM, right?

It is part of VM because we are using it as part of openshift provision.
