### ISSUE TITLE
ADB should include cockpit

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#228]
We should include cockpit bridge and cache the cockpit-ws interface.  Once ready, service-manager should be extended to include management of cockpit-ws

**Comment by LalatenduMohanty** [comment]
@bexelbie Last time I heard that cockpit will be available as docker container.  Will that work for you? We can automate that part i.e. pull, run and integration through vagrant-service-manager

**Comment by bexelbie** [comment]
My understanding is that the bridge has to baked in. The interface runs from a container. It needs a systemd unit file.

**Comment by LalatenduMohanty** [comment]
@bexelbie we can do that in adb-utils.

**Comment by LalatenduMohanty** [comment]
@bexelbie I meant using adb-utils+service-manager for this will help fix the issue

**Comment by bexelbie** [comment]
Shouldn't the bridge be in the kickstart, not the adb-utils scripts?

**Comment by bexelbie** [comment]
@LalatenduMohanty ^^

**Comment by LalatenduMohanty** [comment]
@bexelbie I need to look in to more. I am not much aware about what kind of bridge cockpit needs.
