### ISSUE TITLE
Testing ADB v 1.7 release candidate

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#229]
## Latest Build

RC candidate: https://cbs.centos.org/koji/taskinfo?taskID=70325
- For OpenShift please use the Vagrantfile mentioned in https://github.com/projectatomic/adb-atomic-developer-bundle/pull/230
## Older builds:

Build 1:  https://cbs.centos.org/koji/taskinfo?taskID=69372
The version of the box is not correct. But will fix it in later build
Build 2 ; https://cbs.centos.org/koji/taskinfo?taskID=69386
Build 3: https://cbs.centos.org/koji/taskinfo?taskID=70121
Build 4; https://cbs.centos.org/koji/taskinfo?taskID=70282

**Comment by LalatenduMohanty** [comment]
https://cbs.centos.org/koji/taskinfo?taskID=69383

**Comment by LalatenduMohanty** [comment]
Latest Build : https://cbs.centos.org/koji/taskinfo?taskID=69386

**Comment by LalatenduMohanty** [comment]
sccli openshift will break without the Openshift Vagrantfile

**Comment by LalatenduMohanty** [comment]
Ttested fine with vagrant-service-manger

**Comment by navidshaikh** [comment]
Tested latest build and Eclipse integration. Works fine.

**Comment by LalatenduMohanty** [comment]
Works fine for simple docker pull and run.
Also `sccli k8s or sccli opeshift` works fine
