### ISSUE TITLE
Use --force in tagging ExecStartPre

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/adb-atomic-developer-bundle#244]
```
  Process: 14036 ExecStartPre=/usr/bin/docker tag ${DOCKER_REGISTRY}/${IMAGE} openshift (code=exited, status=1/FAILURE)
```

I'd suggest to add `-f` there so that it does not fail (it does not influence the start, but it's not nice to have errors in `systemctl status`

```
 ExecStartPre=/usr/bin/docker tag -f ${DOCKER_REGISTRY}/${IMAGE} openshift 
```

**Comment by bexelbie** [comment]
I believe this is resolved in the new structure in adb-utils

https://github.com/projectatomic/adb-utils/blob/master/services/openshift/openshift.service

@vpavlin can we close this?

**Comment by praveenkumar** [comment]
This is already fixed and now we are not using `ExecStartPre` for taggging. So closing this issue now.
