### ISSUE TITLE
Enable openshift.service in Vagrantfile

### ISSUE THREAD

**Issue by vpavlin** [projectatomic/adb-atomic-developer-bundle#247]
There is no reason why systemd service for OpenShift shouldn't be enabled by default.

I'd suggest adding 

```
sudo systemctl enable openshift.service
```

to Vagrantfile so that you don't need to run `vagrant provision` after `vagrant halt && vagrant up`

**Comment by bexelbie** [comment]
+1

**Comment by hferentschik** [comment]
I think this can be closed? @praveenkumar?

**Comment by navidshaikh** [comment]
This is now handled by vagrant-service-manager plugin.
