### ISSUE TITLE
Move docker pulls into systemd unit file for OpenShift

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#248]
There doesn't seem to be a reason why those pulls need to live in the Vagrantfile

**Comment by hferentschik** [comment]
@bexelbie I think this one is out of date, right? Can we close it?

**Comment by LalatenduMohanty** [comment]
@hferentschik Agree. @bexelbie  Closing this as this is already addressed in adb-utils https://github.com/projectatomic/adb-utils/pull/45
