### ISSUE TITLE
RFE: preload the centos docker image into the vagrant box

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#25]
<a href="https://github.com/goern"><img src="https://avatars.githubusercontent.com/u/260331?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [goern](https://github.com/goern)**
_Monday May 11, 2015 at 15:55 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/11_

---

As I dont want to `docker pull` them each time I `vagrant destroy`'ed a box

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Monday May 11, 2015 at 16:12 GMT_

---

@goern Yup agree. I will work on this

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbsingh](https://github.com/kbsingh)**
_Tuesday May 12, 2015 at 10:30 GMT_

---

I would recommend only doing this for the centos7:latest docker image, and skip centos6 and centos5 by default.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Thursday Jul 23, 2015 at 09:48 GMT_

---

@goern  Koji does not have internet access in side the build root. So baking the image  in the vagrant image seems difficult as of now.
We can create a Vagrant file which will pull the image every time you do "vagrant up" but it does not solve the problem of downloading it every time if vagrant destroy has been executed before vagrant up.

CC @kbsingh @alphacc

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/goern"><img src="https://avatars.githubusercontent.com/u/260331?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [goern](https://github.com/goern)**
_Thursday Jul 23, 2015 at 10:50 GMT_

---

hmm, build a .rpm that carries the docker image and does a docker import/load in post-install-script?

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbsingh](https://github.com/kbsingh)**
_Thursday Jul 23, 2015 at 12:57 GMT_

---

the images, once build, go through an import process for release. That might be a good place to rework stuff like this as well. Presently its just going through a rename and push, but for vmware and other hypervisor support, we might be doing more with qemu-img converts and content being added in via libguestfs. Is that a process we could use here as well ? sort of like a post-script.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Monday Jul 27, 2015 at 11:07 GMT_

---

@kbsingh This seems like a good idea.

**Comment by langdon** [comment]
Being not 100% on docker load, the only concern I have is about making sure that the tarball, once docker load'ed, is still "linked" to the docker-hub version. In other words, be sure that an update to the image in docker-hub is reflected on the next docker pull of a dependent image.

**Comment by bexelbie** [comment]
Would this be solved by having a CentOS docker registry that was trusted by the build process and able to later be pulled from by the internet keeping the linkage intact?  We could then use the RHEL "federation" concept in dockerhub to send requests over.

**Comment by LalatenduMohanty** [comment]
@bexelbie I think @imcleod is the right guy to answer your question

**Comment by bexelbie** [comment]
Look a bit more, it appears that rhel images are not searchable via the web at dockerhub, therefore this is probably a sub-optimal suggestion (federated registry - without real federation).  Therefore the association is something we need to figure out, or we need to do as @kbsingh suggested above.

**Comment by vpavlin** [comment]
@whitel 
1. `docker save/load` preserve image id (which is what matters when checking if there is newer image in registry.
2. As long as name/tag matches, you will always be fine. In the worst case you will get the same image with different id on `docker pull`

I think we should try to solve this by using `docker pull`, not `docker load` because AFAIK there is no `save/load` for Docker V2 yet, so it might get us in problems when Docker drops v1 support.

**Comment by LalatenduMohanty** [comment]
@vpavlin Thanks for the info. I am working on a way to use the docker save and load :/ . But now that these stuffs are not in docker v2 , I dont think I should pursue this anymore

**Comment by bexelbie** [comment]
This is dependent on #101

**Comment by LalatenduMohanty** [comment]
I need to discuss this with @goern with respect to why he wanted the CentOS docker image baked in to the Vagrant box

**Comment by langdon** [comment]
I really think we should just do what we do for now. Hopefully, when docker v2 drops everyone and their brother will have the exact same problem. Solution will be either a more robust build system as suggested [above](https://github.com/projectatomic/adb-atomic-developer-bundle/issues/25#issuecomment-136704590) or a variant of export/load will be provided.

And, as for @LalatenduMohanty's comment above, I am sure @goern wanted the same thing I do, increase performance on the next "docker pull" after the vm starts.

**Comment by LalatenduMohanty** [comment]
I haven't seen any  interest for having the CentOS7 box in the ADB vagrnat box. Hence closing this
