### ISSUE TITLE
Connecting to Kubernetes API server from outside of Vagrant box

### ISSUE THREAD

**Issue by kadel** [projectatomic/adb-atomic-developer-bundle#250]
By default kube-apiserver listens only on `127.0.0.1`.
Without reconfiguring it it is not possible to connect to Kubernetes using kubectl from another machine.

We should consider configuring apiserver to listen on all IPs by default.

This can be done in `/etc/kubernetes/apiserver`:

```
-KUBE_API_ADDRESS="--address=127.0.0.1"
+KUBE_API_ADDRESS="--address=0.0.0.0" 
```

**Comment by navidshaikh** [comment]
`kubernetes` is packaged and shipped in ADB as RPMs. The default config file for `kube-apiserver` sets `127.0.0.1` for API server. Ideally the change as part of this fix should be part of the kubernetes package repo. We can carry the patch in KS until we have it fixed in the kube package itself OR as part of the Vagrantfile for kube https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-k8s-singlenode-setup/Vagrantfile. IMO we should update it in KS itself.

```
# for ADB 1.7

[vagrant@centos7-adb ~]$ rpm -q kubernetes-master 
kubernetes-master-1.0.3-0.2.gitb9a88a7.el7.x86_64

[vagrant@centos7-adb ~]$ rpm -ql kubernetes-master| grep /etc/kubernetes/apiserver
/etc/kubernetes/apiserver

[vagrant@centos7-adb ~]$ cat /etc/kubernetes/apiserver  | grep KUBE_API_ADDRESS
KUBE_API_ADDRESS="--address=127.0.0.1"
```

**Comment by navidshaikh** [comment]
@LalatenduMohanty @praveenkumar  @bexelbie : thoughts?

**Comment by navidshaikh** [comment]
One can use following Vagrantfile to fix the issue (temporarily) until we have fix in the next release of the ADB box

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for single node k8s setup
Vagrant.configure(2) do |config|
  config.vm.box = "projectatomic/adb"

  config.vm.provision "shell", inline: <<-SHELL
     sudo mkdir -p /etc/pki/kube-apiserver/
     sudo openssl genrsa -out /etc/pki/kube-apiserver/serviceaccount.key 2048
     sudo sed -i.back '/KUBE_API_ARGS=*/c\KUBE_API_ARGS="--service_account_key_file=/etc/pki/kube-apiserver/serviceaccount.key"' /etc/kubernetes/apiserver
     sudo sed -i.back '/KUBE_CONTROLLER_MANAGER_ARGS=*/c\KUBE_CONTROLLER_MANAGER_ARGS="--service_account_private_key_file=/etc/pki/kube-apiserver/serviceaccount.key"' /etc/kubernetes/controller-manager
     echo "setup master"

     sed -i.back '/KUBE_API_ADDRESS=*/c\KUBE_API_ADDRESS="--address=0.0.0.0"' /etc/kubernetes/apiserver

     for service in etcd kube-apiserver kube-controller-manager kube-scheduler; do
       echo "  enable $service"
       sudo systemctl enable $service
       echo "  start $service"
       sudo systemctl start $service
     done
     echo "setup nodes"
     for service in kube-proxy kubelet; do
       echo "  enable $service"
       sudo systemctl enable $service
       echo "  start $service"
       sudo systemctl start $service
     done
     echo "  restart docker"
     sudo systemctl restart docker
  SHELL
end
```

**Comment by kadel** [comment]
I'm afraid that this is not going to be changed upstream.
Binding to 0.0.0.0 is OK only for dev environment because it is insecure (no tls no authentication).

There is also secure port, that can be used to access api
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/accessing-the-api.md

**Comment by kadel** [comment]
I found better solution than opening unsecured api ;-)

According to documentation secure port 6443 is by default binded to IP of first non-localhost network interface ([source](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/accessing-the-api.md#ports-and-ips-served-on)). So souldn't need to reconfigure anything.

I tried describe how you can authenticate to apiserver using service account: https://gist.github.com/kadel/9d9d4949a8035cd0c5fb

**Comment by praveenkumar** [comment]
I am in favor of secure port, I think Openshift also use it in same way. I can debug it little more once have some spare time.

**Comment by navidshaikh** [comment]
@kadel : 

> I tried describe how you can authenticate to apiserver using service account: https://gist.github.com/kadel/9d9d4949a8035cd0c5fb

Thank you for writing this up. And yes, the connection from `kubectl` needs to be secured using certificate.

**Comment by kadel** [comment]
@navidshaikh +1 for handling `ca.crt` and  `KUBECONFIG` with vagrant-service-manager plugin

**Comment by LalatenduMohanty** [comment]
@navidshaikh are you planning to fix it for ADB 2.0?

**Comment by praveenkumar** [comment]
@navidshaikh what  is the status of this? Are you still want to work on this issue?

**Comment by bexelbie** [comment]
https://github.com/projectatomic/vagrant-service-manager/issues/11

**Comment by bexelbie** [comment]
Has anyone tested this with virtualbox?  I am concerned it will by default bind to the wrong IP as the first IP is non-routable from the host.

**Comment by kadel** [comment]
I don't remember if I tested this with virtualbox or libvirt. 
But if binding to fist non-localhost network will be issue we can change with `--bind-address` flag, and bind it to `0.0.0.0`. This should't cause any problems.

**Comment by bexelbie** [comment]
+1 for 0.0.0.0

**Comment by kadel** [comment]
So I just tested steps from my gist again on virtualbox and it works fine.
It seems that Kubernets Api Server binds secure port on all addresses.

```
[vagrant@centos7-adb ~]$ sudo netstat -lpn | grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      11977/kube-apiserve 
```

I haven't found any settings set for this so this seems to be default behavior, despite the fact that docs are saying something else.

**Comment by kadel** [comment]
help for kube-apiserver confirms  that `--bind-address` default is `0.0.0.0`

```
  --bind-address=0.0.0.0: The IP address on which to serve the --read-only-port and --secure-port ports.
The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. 
If blank, all interfaces will be used (0.0.0.0).
```

**Comment by praveenkumar** [comment]
We are tracking this from VSM side: https://github.com/projectatomic/vagrant-service-manager/issues/350
