### ISSUE TITLE
Add sccli documention link to ADB documents

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#251]
Currently `adb-utils` repo consist documentation for `sccli` and same we should link to ADB documentation.

https://github.com/projectatomic/adb-utils/blob/master/README.rst

**Comment by LalatenduMohanty** [comment]
@bexelbie suggestion?

**Comment by bexelbie** [comment]
@preeticp and I will look for where to put this.  We probably need to break out a section for vagrant-ssh users

**Comment by praveenkumar** [comment]
@bexelbie , @Preeticp are you folks working on it?
