### ISSUE TITLE
Default Vagrantfile should allow for subscription details via env variables and manual user interaction

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#253]
Currently the _Vagrantfile_ contains:

```
  config.registration.username = ENV['SUB_USERNAME']
  config.registration.password = ENV['SUB_PASSWORD']
```

This will allow to get the credentials via environment variables, but it will fail if no env settings are provided. 

Using

```
  cdk.registration.username    = ENV.has_key?('SUB_USERNAME') ? "#{ENV['SUB_USERNAME']}" : nil
  cdk.registration.password    = ENV.has_key?('SUB_PASSWORD') ? "#{ENV['SUB_PASSWORD']}" : nil
```

should bypass this and in case of no env variables, use manual user interaction. 

On this note, it would make sense to add something like this as well, since registration is not needed in these cases:

```
      case ARGV[0]
      when "up", "halt"
        if cdk.registration.username.nil? || cdk.registration.password.nil?
          puts SUBSCRIPTION_INFO
        end
      end
```

**Comment by hferentschik** [comment]
Could you please add label focus:devex

**Comment by rct** [comment]
Note: There are [instructions in the CDK install guide](https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/version-7/container-development-kit-installation-guide/#registering_your_red_hat_enterprise_linux_vagrant_boxes_with_red_hat) for putting the registration details in the User's vagrantfile in their home directory. (~/.vagrant.d/Vagrantfile)

```
Vagrant.configure('2') do |config|
 config.registration.subscriber_username = '<your Red Hat username>'
 config.registration.subscriber_password = '<your Red Hat password>'
end
```

So any added check shouldn't overwrite that because the environment variables aren't set (at least without correcting the documentation).

Personally I prefer the user-wide Vagrantfile approach to environment variables. Though environment variables should be able to override ~/.vagrant.d/Vagrantfile as needed.

**Comment by hferentschik** [comment]
A couple of things here. First, the docs are wrong. It uses wrong properties:

```
Vagrant.configure('2') do |config|
 config.registration.subscriber_username = '<your Red Hat username>'
 config.registration.subscriber_password = '<your Red Hat password>'
```

   end

There is no _subscriber_ in the properties names.

Secondly, as it stands now, the values form the user's _Vagrantfile_ will never apply. Just by setting the value (and this what you do by `config.registration.username = ENV['SUB_USERNAME']`, you set to a value or empty string), a config is generated for the plugin which gets merged as per https://www.vagrantup.com/docs/plugins/configuration.html. Here is the info output of using the stock _Vagrantfile_ with settings in _~/.vagrant/Vagrantfile_:

```
INFO loader: Set :home = #<Pathname:/Users/hardy/.vagrant.d/Vagrantfile>
INFO loader: Set :root = #<Pathname:/Users/hardy/work/developer-platform/openshift-vagrant/Vagrantfile>
```

   INFO loader: Loading configuration in order: [:home, :root]
   INFO config: Evaluating registration configuration: @conf.username= "foo"
   INFO config: Evaluating registration configuration: @conf.password= "bar"
   INFO config: Evaluating registration configuration: @conf.username 
   INFO config: Evaluating registration configuration: @conf.password 
   INFO config: Evaluating registration configuration: @conf.username= nil
   INFO config: Evaluating registration configuration: @conf.password= nil
   INFO config: Final registration configuration: #<OpenStruct username=nil, password=nil, skip=false, unregister_on_halt=true>
   INFO loader: Set "2164841320_machine_default" = []
   INFO loader: Loading configuration in order: [:home, :root, "2164841320_machine_default"]
   INFO config: Final registration configuration: #<OpenStruct username=nil, password=nil, skip=false, unregister_on_halt=true>

Admittedly  my suggested change has the same issue, but either way something else is needed here. What we want is. Take _~/.vagrant.d/Vagrantfile_ setttings unless environment variables are set. If neither is specified run manual registration.

**Comment by hferentschik** [comment]
Can we mark this as a bug and also schedule for GA.

**Comment by hferentschik** [comment]
This seems to do what we want:

```
  if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
     config.registration.username = ENV['SUB_USERNAME']
     config.registration.password = ENV['SUB_PASSWORD']
  end
```

By wrapping into the if statement we only set plugin config values if the env variables are set. If not the user's Vagrantfile applies. If there is nothing there it will fallback to user interaction.

**Comment by hferentschik** [comment]
On that note, things like:

```
#check if vagrant-service-manager is installed on system
unless Vagrant.has_plugin?("vagrant-service-manager")
  raise "vagrant-service-manager plugin is not installed, run `vagrant plugin install vagrant-service-    manager` to install the plugin."
end
```

and 

```
  if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
     config.registration.username = ENV['SUB_USERNAME']
    config.registration.password = ENV['SUB_PASSWORD']
 end
```

are perfect candidates to be moved into the _Vagrantfile_ which is part of the box. At the moment this file contains:

```
Vagrant.configure("2") do |config|
  config.vm.base_mac = "525400a51d17"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end
```

We are enforcing _rsync_ as folder sync type. This means we already somewhere control what gets into this _Vagrantfile_. Checking for installed plugins and handling for ENV variables should not be directly visible for the user. It is much better off in the box'es _Vagrantfile). Once that would move we would be one step closer to being able to have an empty working dir _Vagrantfile_.

**Comment by bexelbie** [comment]
@hferentschik I agree that handling this in the box Vagrantfile would be ideal, however I believe we can't do that right now because of limitations in ImageFactory ( @navidshaikh  @imcleod )

**Comment by hferentschik** [comment]
> I agree that handling this in the box Vagrantfile would be ideal, however I believe we can't do that right now because of limitations in ImageFactory

This is the info I am looking for. What's the limitation? We already have a custom box file. It must come from somewhere or something should be able to generate it. And if it is an ImageFactory thing, what would it take to fix? Adding your custom _Vagrantfile_ seems to be a standard use case for ImageFactory.

**Comment by bexelbie** [comment]
@hferentschik my understanding is that ImageFactory does handle the custom Vagrantfile, however it doesn't support arbitrary code in the file.  There are only a handful of directives supported.  The project doesn't wish to support arbitrary directives the last time I talked to someone and I was told that if we wanted to add stuff, we would need to propose changes.  If accepted we should expect to see the ability to use it in production in 1 month + development time.

**Comment by rct** [comment]
Off the top of my head, it seems using the box's Vagrantfile to better set some defaults would solve a number of problems across usability, supportability, and documentation.  It seems a particularly good place to ensure the box's content and the required vagrant plugins are in sync.  

It seems to me, given that the .box file is a `tar` file, until you had the appropriate support in the build tool, you could have a temporary build step that worked around this by untaring the box file, patching the Vagratnfile, and then re-taring the .box file.  AFAICT right now the .box file doesn't appear to be digitally signed or have a requirement that would make this harder than that.

**Comment by bexelbie** [comment]
@LalatenduMohanty @kbsingh - are there other considerations in play before we decide if we want to try to create this?

**Comment by hferentschik** [comment]
> Off the top of my head, it seems using the box's Vagrantfile to better set some defaults would solve a number of problems across usability, supportability, and documentation

+1

>  It seems a particularly good place to ensure the box's content and the required vagrant plugins are in sync. 

+1

> It seems to me, given that the .box file is a tar file, until you had the appropriate support in the build tool, you could have a temporary build step that worked around this by untaring the box file, patching the Vagratnfile, and then re-taring the .box file

Good idea. As you say, the box file is just a tarball.

**Comment by hferentschik** [comment]
That said, it might make sense to track the use of the box'es default Vagrantfile in a separate issue, since this is really unrelated to the reported issue around using environment variables for vagrant-registration.

**Comment by kbsingh** [comment]
Note that the monkey patching will need some level of automation and a test framework around it. There are plenty of vagrant up tests around ( for libvirt and kvm, both on linux ), and it should be trivial throwing something around this, but it just needs to be done.

**Comment by hferentschik** [comment]
> Note that the monkey patching will need some level of automation and a test framework around it.

Sure

> and it should be trivial throwing something around this, but it just needs to be done.

Ok, who is normally working in this area?

**Comment by LalatenduMohanty** [comment]
@bexelbie @hferentschik Here is the issue I have raised in imagefactory long back https://github.com/redhat-imaging/imagefactory/issues/361

**Comment by hferentschik** [comment]
> Here is the issue I have raised in imagefactory long back redhat-imaging/imagefactory#361

Thanks @LalatenduMohanty. I commented on the issue as well to get notifications. I would love to understand the problem.

**Comment by hferentschik** [comment]
Guys, discussion around moving the logic where it belongs, we should make sure that in a first step we at least fix the code in the _Vagrantfile_ we already have. The way it is now, really breaks the ability to either add the settings in the users _Vagrantfile_ or via manual registration.

If possible this should actually already go into Beta5.

**Comment by hferentschik** [comment]
Seems there were no changes to the default Vagrantfile for Beta5. When do you guys plan to make changes to it?

**Comment by bexelbie** [comment]
@LalatenduMohanty @praveenkumar ^^

**Comment by LalatenduMohanty** [comment]
@hferentschik We will pick it for next weekly build. Sorry for the inconvenience. CC @praveenkumar

**Comment by hferentschik** [comment]
Since I cannot create a pull request for this. Here is how I think the default Vagrantfile should look like for the CDK atm. Note, the _systemctl enable openshift_ and _systemctl start openshift_ should be removed once OpenShift starts per default - https://gist.github.com/hferentschik/3daaa9297a90016810f4

**Comment by dkutalek** [comment]
Folks, these settings were introduced by me and Lala via:
https://bugzilla.redhat.com/show_bug.cgi?id=1302830

Hardy, I have tested these settings without env. variables provided 
and it worked for me on all 3 platforms - vagrant up asked me 
for username / password. How it didn't work for you Hardy?

The thing we should fix is described in:
https://bugzilla.redhat.com/show_bug.cgi?id=1302830#c5

**Comment by hferentschik** [comment]
@dkutalek, did you also try to add credentials in your default _Vagrantfile_ under _~/.vagrant/Vagrantfile_? This needs to be supported as well. Once you access _ENV['SUB_USERNAME']_ you are getting a value, which might be null or empty string. This would then override anything you potentially set in _~/.vagrant/Vagrantfile_. I tested my _Vagrantfile_ with _~/.vagrant/Vagrantfile_, set env variables and without. It works in all three cases. The current version does not.

**Comment by hferentschik** [comment]
@dkutalek btw, I cannot open these URLs. What is it about?

**Comment by hferentschik** [comment]
@dkutalek BTW, I can see the issue now. The change I propose fixes this issue as well.

**Comment by bexelbie** [comment]
This also seems like something a PR can now be filed on with the merge of #263

**Comment by hferentschik** [comment]
PR - https://github.com/projectatomic/adb-atomic-developer-bundle/pull/311

**Comment by LalatenduMohanty** [comment]
Closing this as #311 is merged.
