### ISSUE TITLE
Wrong order of systemctl calls in Vagrantfile

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#254]
The default Vagrnatfile contains:

```
config.vm.provision "shell", inline: <<-SHELL
  sudo systemctl start openshift
  sudo systemctl enable openshift
SHELL
```

That seems wrong. You would first enable the service and then start it, no?

**Comment by hferentschik** [comment]
Can you please add label focus:devex

**Comment by bexelbie** [comment]
I believe this should be fixed in adb-utils/sccli pending PR https://github.com/projectatomic/adb-utils/pull/45
@praveenkumar

**Comment by praveenkumar** [comment]
@hferentschik So `systemctl enable <service>` just add a symlink `Created symlink from /etc/systemd/system/multi-user.target.wants/<service> to /usr/lib/systemd/system/<service>` so order doesn't matter here. One can start a service and then enable/disable without any issue. `Enable` just make sure service will start during boot in case VM restart/halt.

**Comment by hferentschik** [comment]
> systemctl enable <service> just add a symlink Created symlink from /etc/systemd/system/multi-user.target.wants/<service> to /usr/lib/systemd/system/<service> so order doesn't matter here

Sure, but it still seems odd to me. It just makes (at least me) stumble. I'd switch the order. That said, I understand this will go away anyways. The _service-manager_ plugin will take care of this. It will have a 'provider' option and depending which one is set, it will do the right underlying provisioning and _systemctl_ calls, right? On that note, I also thought we agreed that OpenShift is the default setup for the CDK. In this case I would expect that the service is enabled by default. Also in the context of the _service-manager_, if one wants to use OpenShift one would not have to explicitly specify this option. For me this is all about getting to a zero conf situation for the default (Openshift) case. I still believe a a _vagrant init cdk && vagrant up_ is possible.

**Comment by navidshaikh** [comment]
> The service-manager plugin will take care of this. It will have a 'provider' option and depending which one is set, it will do the right underlying provisioning and systemctl calls, right?

Correct.

**Comment by hferentschik** [comment]
> Correct.

:thumbsup:
