### ISSUE TITLE
Allow to configure number of cores and memory size via environment variables

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#255]
One could make it easier for users to change the default CPU and memory settings via environment variables. Something like that:

```
# The amount of memory available to the VM
VM_MEMORY = ENV['VM_MEMORY'] || 4096

# Number of VM CPUs
VM_CPU = ENV['VM_CPU'] || 2
```

and then:

```
  cdk.vm.provider "virtualbox" do |v, override|
    override.vm.box = "cdk_v2"
    override.vm.box_url = "#{VAGRANT_VIRTUALBOX_URL}"
    v.name = "openshift.cdk-2"
    v.memory = VM_MEMORY
    v.cpus   = VM_CPU
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
```

Just as an idea.

**Comment by praveenkumar** [comment]
+1, you want this to be in our default vagrant file?

**Comment by navidshaikh** [comment]
Should the environment variables be prepended by characters specific to our tooling (ADB / CDK) ?

Going forward if we have multiple environment variables, its easier to distinguish them and avoid possible collision with other tooling consuming such generic environment variables names.

For eg:

```
ADB_VM_MEMORY
ADB_VM_CPU

CDK_VM_MEMORY
CDK_VM_CPU
```

We can support for types of env variables which are prepended by either ADB or CDK based on the box in action.

**Comment by praveenkumar** [comment]
> Should the environment variables be prepended by characters specific to our tooling (ADB / CDK) ?

@navidshaikh No, these are common env. variables and should not be different for ADB/CDK or you have any specific use case except basic functionality those variable going to provide? 

> Going forward if we have multiple environment variables, its easier to distinguish them and avoid possible collision with other tooling consuming such generic environment variables names.

Agree for those kind of variable we will identify and add prefix accordingly like we did for Variant file.

**Comment by hferentschik** [comment]
> you want this to be in our default vagrant file?

That was the idea yes. Not a must, but might be nice. If this would go into the box'es _Vagrantfile_ I would definitely say let's do it. While we still ship a separate standalone _Vagrantfile_ it clashes with the goal to keep it as small and simple as possible.

I leave it up to you guys. Maybe we add it and then take the first opportunity we get to move it into the box. BTW, is there any progress on tweaking the ImageFactory build to take a custom _Vagrantfile_?

**Comment by navidshaikh** [comment]
> @navidshaikh No, these are common env. variables and should not be different for ADB/CDK or you have any specific use case except basic functionality those variable going to provide?

common env variables to which tooling?
Its not about being different for ADB / CDK, but declaring and defining the set of the environment variables that belong to our tooling and they should look alike. 
Also my concern was not to collide with such generic names which could have been consumed by other tooling (non container-tools tooling).

**Comment by praveenkumar** [comment]
> BTW, is there any progress on tweaking the ImageFactory build to take a custom Vagrantfile?

https://github.com/redhat-imaging/imagefactory/issues/361 (I didn't see any much progress here).

**Comment by hferentschik** [comment]
:-(

**Comment by hferentschik** [comment]
BTW, on top of taking the values from the environment variables, we should also increase the current default. 1 GB sounds really low. Admittedly we don't really have real performance numbers, but the Origin Vagrantfile uses for example 3GB (I think).

Do we have an ETA for the _Vagrantfile_ changes? I cannot create a pull request against this repo, right? The file lives somewhere else afaiu. Would it help if I attach a patch?

**Comment by LalatenduMohanty** [comment]
@hferentschik actually we are planning to put the Vagrantfiles in this repo https://github.com/projectatomic/adb-atomic-developer-bundle/pull/263
But it is still in the review process

**Comment by bexelbie** [comment]
@praveenkumar @LalatenduMohanty can we get a PR to update the ADB vagrantfiles so that @hferentschik can at least see the model?

**Comment by hferentschik** [comment]
Since I cannot create a pull request for this. Here is how I think the default Vagrantfile should look like for the CDK atm. Note, the _systemctl enable openshift_ and _systemctl start openshift_ should be removed once OpenShift starts per default - https://gist.github.com/hferentschik/3daaa9297a90016810f4

**Comment by bexelbie** [comment]
@hferentschik #263 merged .. if you have time for a PR you can now submit it.  I'll try to get to it if you don't.

**Comment by hferentschik** [comment]
> #263 merged .. if you have time for a PR you can now submit it.

nice

**Comment by hferentschik** [comment]
PR - https://github.com/projectatomic/adb-atomic-developer-bundle/pull/311

**Comment by brgnepal** [comment]
Closing as the related PR is merged https://github.com/projectatomic/adb-atomic-developer-bundle/pull/311
