### ISSUE TITLE
Add Atomic Registry

### ISSUE THREAD

**Issue by goern** [projectatomic/adb-atomic-developer-bundle#261]
... to the docs so that Devs learn how to share container images with coworkers
... to the cdk (openshift, kubernetes) as a working and usable example

@aweiteka

**Comment by praveenkumar** [comment]
@goern I hope you mean https://github.com/aweiteka/atomic-registry , but as per README I didn't get much info about it can you share some points here?

**Comment by bexelbie** [comment]
@goern I believe this will be done when docs.projectatomic.io comes onlne

**Comment by praveenkumar** [comment]
@bexelbie so is it doc related issue? if yes can you put add a label?

**Comment by aweiteka** [comment]
> @goern I hope you mean https://github.com/aweiteka/atomic-registry

@praveenkumar this repo has been deprecated. It will be removed ASAP.

> ... to the docs so that Devs learn how to share container images with coworkers

Docs are published[1], quickstart image has landed[2]. Have at it!

[1] http://docs.projectatomic.io/registry/
[2] https://hub.docker.com/r/projectatomic/atomic-registry-quickstart/

> ... to the cdk (openshift, kubernetes) as a working and usable example

We need to think through this. Atomic Registry is based on OpenShift. The quickstart image[3] is a reasonable example of a privileged "installer" container but I didn't use atomic app for it. One can run the cockpit-based registry console UI as a template[4]. That might be interesting but these UI elements will be folded into OpenShift soon.

[3] Dockerfile code: https://github.com/openshift/origin/tree/master/examples/atomic-registry
[4] https://github.com/openshift/origin/blob/master/examples/atomic-registry/registry-console-template.yaml

**Comment by LalatenduMohanty** [comment]
The way vagrant networking works, the registry hosted in ADB/CDK can not be used by other workstations in the network.  
I am not sure that even if we add atomic registry in ADB/CDK it would bring any value.

**Comment by praveenkumar** [comment]
> Docs are published[1], quickstart image has landed[2]. Have at it!

@aweiteka Thanks, I just had a quick look to "Getting started" doc and since we are already exposing openshift secure registry[0] where user login to registry with token and perform required operation. As you also said it's based on openshift so I think we already have it included.  If you think there is some other different usecase then I am open for discussion.

[0] https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift_provision#L73-L113

**Comment by aweiteka** [comment]
> since we are already exposing openshift secure registry[0] where user login to registry with token and perform required operation. As you also said it's based on openshift so I think we already have it included.

Yes, it sounds like you have this use case covered. Adding another registry would just add confusion.

**Comment by praveenkumar** [comment]
> Yes, it sounds like you have this use case covered. Adding another registry would just add confusion.

Thank you for clarification (relabeling to docs).

**Comment by bexelbie** [comment]
@LalatenduMohanty please confirm that we are now using openshift registry in place of atomic registry as we move forward.

**Comment by LalatenduMohanty** [comment]
@bexelbie Yes, We have OpenShift docker registry in ADB. Here is an old blog I had written https://lalatendu.org/2016/06/09/using-the-docker-registry-in-openshift-using-adb/
I need to fix the blog as now we do not need to do `vagrant ssh` in to the box.

**Comment by thatdocslady** [comment]
@LalatenduMohanty it seems that the restructured usage doc[1] already contains the latest OSO/Docker registry info. Is there anything else that needs to be documented here or elsewhere? Thx :)

[1]https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst

**Comment by LalatenduMohanty** [comment]
@thatdocslady I think we can close this issue now. But the registry name has changed after landrush integration with ADB. We need to fix that and need to add how an user can use that. But I will create a new issue for that.

**Comment by LalatenduMohanty** [comment]
@thatdocslady looks like the landrush integration working fine for registry too. Now it is  `hub.openshift.adb`.

```
[lmohanty@LalatenduM-laptop centos-openshift-setup]$ vagrant service-manager env

# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://192.168.121.67:2376
export DOCKER_CERT_PATH=/home/lmohanty/vagrantboxes/adb/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.22

# openshift env:
# You can access the OpenShift console on: https://192.168.121.67:8443/console
# To use OpenShift CLI, run: oc login https://192.168.121.67:8443
export OPENSHIFT_URL=https://192.168.121.67:8443
export OPENSHIFT_WEB_CONSOLE=https://192.168.121.67:8443/console
export DOCKER_REGISTRY=hub.openshift.adb
```
