### ISSUE TITLE
Configure private networking for ADB

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#284]
We are configuring the a NAT interface in kickstart file for box, this is to propose configuring non NAT (private) networking interface for the box by default via kickstart.

For multiple use cases we require the non NAT networking interface for the box and having it configured for the box does not break the use cases where it does not require it (vagrant ssh use case per say).

If agreed upon this proposal, the implementation should take into account the static IP given to box explicitly in Vagrantfile.

**Comment by praveenkumar** [comment]
>  this is to propose configuring non NAT (private) networking interface for the box by default via kickstart.

Non NAT you mean configuring bridge networking for box? We have below options for libvirt and virtualbox networking.
- http://wiki.libvirt.org/page/Networking
- https://www.virtualbox.org/manual/ch06.html

**Comment by bexelbie** [comment]
@navidshaikh Exactly what are you proposing to add to the kickstart file? Today provisioning a second interface works. We have a timing issue.

**Comment by navidshaikh** [comment]
> Exactly what are you proposing to add to the kickstart file? Today provisioning a second interface works. We have a timing issue.

I am proposing to configure the `eth1` interface right from the kickstart file. See [this](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/centos-7-adb-vagrant.ks#L114) section in current KS file where we are configuring `eth0` for the box. With that said, we also need to take care what happens if user configures his own interface in Vagrantfile.

**Comment by navidshaikh** [comment]
> Non NAT you mean configuring bridge networking for box? We have below options for libvirt and virtualbox networking.

Private networking, as we explicitly configure in the box for OpenShift or Eclipse use case.

**Comment by bexelbie** [comment]
@navidshaikh it sounds like we will wind up with a lot of adapters using what you propose.  Does it actually fix the static ip problem?

**Comment by bexelbie** [comment]
this issue seems to be duplicating #283 and we should consolidate the conversation

**Comment by praveenkumar** [comment]
@navidshaikh I think we don't require to configure eth1 network like we do for eth0 because for `libvirt` provider we actually don't need any extra network interface and also we had now #283 fixed.

**Comment by bexelbie** [comment]
@navidshaikh I believe our latest fixes in vagrant service-manager have resolved this issue.  Can we close?

**Comment by navidshaikh** [comment]
Sounds good. Closing the issue.
