### ISSUE TITLE
Release v 1.7.2  (was 1.8.0 - see comments)

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#299]
RC 4 : https://cbs.centos.org/koji/taskinfo?taskID=83609
## Here are the areas we should test with the release candidate build
- [Vagrantfiles for Mesos, K8s, Openshift](https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos)
- vagrant-service-manager with [Eclipse and host based tools](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-the-box-with-host-based-tools-eclipse-and-clis)
# Older Builds

RC 1 : https://cbs.centos.org/koji/taskinfo?taskID=82656
RC2:  https://cbs.centos.org/koji/taskinfo?taskID=82684
RC3: https://cbs.centos.org/koji/taskinfo?taskID=83410

**Comment by LalatenduMohanty** [comment]
I have tested OpenShift Vagrantfile, K8s Vagrantfile along with running projectatomic/helloapache and everything works as expected

**Comment by LalatenduMohanty** [comment]
vagrant-sshfs also works with the image

**Comment by brgnepal** [comment]
I tested with Virtualbox, `sccli k8s` and Openshift is working.

**Comment by LalatenduMohanty** [comment]
Changed the release version as  https://github.com/projectatomic/adb-atomic-developer-bundle/pull/297 did not get merged . Refer  https://github.com/projectatomic/adb-atomic-developer-bundle/pull/305

**Comment by bexelbie** [comment]
Tested box (basic sanity testing of docker on virtualbox on fedora) at https://cbs.centos.org/koji/taskinfo?taskID=83609 - LGTM

**Comment by LalatenduMohanty** [comment]
Tested K8s, Openshift, running atomicapp successfully. Also very basic test with Mesos and seems to be working too.

**Comment by LalatenduMohanty** [comment]
Raised issue in bugs.centos.org to upload the images to http://cloud.centos.org/centos/7/atomic/images/  i.e. https://bugs.centos.org/view.php?id=10605 

Once images are uploaded , we should be able to update https://atlas.hashicorp.com/projectatomic/adb and then send the announcement mail to container-tools
