### ISSUE TITLE
RFE: include vasek's docker aliases

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#30]
<a href="https://github.com/goern"><img src="https://avatars.githubusercontent.com/u/260331?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [goern](https://github.com/goern)**
_Monday May 11, 2015 at 19:20 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/15_

---

include the docker aliases [1] of vpavlin wihtin the base image, they are pretty handy...

[1] - https://github.com/vpavlin/docker-tools/blob/master/bash_aliases_docker

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbsingh](https://github.com/kbsingh)**
_Tuesday May 12, 2015 at 10:10 GMT_

---

+1 looks like a good candidate for .bash_profile for user vagrant.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Tuesday May 12, 2015 at 12:14 GMT_

---

@goern looks good to me

**Comment by praveenkumar** [comment]
@LalatenduMohanty does it still applicable (I don't have any background knowledge about it)?

**Comment by LalatenduMohanty** [comment]
Closing the issue as I do not think we need it anymore.
