### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#313]
Calling the version 1.8.0, as there are changes to the kickstart file.
- [X] #263 
- [x] #300 
- [x] #306
- [x] #297
- [x] #311 
- [x] #321
- [x] #322
## Release Candidate Build:

_RC1:_ 

Build: https://cbs.centos.org/koji/taskinfo?taskID=84706
 This is build with #297  PR as we have plan to merge #297 for 1.8.0 release
- Libvirt : http://cbs.centos.org/kojifiles/work/tasks/4706/84706/centos-7-adb-1.8-0.x86_64.rhevm.ova
- Virtualbox : http://cbs.centos.org/kojifiles/work/tasks/4706/84706/centos-7-adb-1.8-0.x86_64.vsphere.ova

**Comment by LalatenduMohanty** [comment]
@budhrg @navidshaikh @praveenkumar @surajssd @bexelbie @Preeticp Need help in testing the box!

**Comment by brgnepal** [comment]
@LalatenduMohanty 
Getting error on running shell provisioner:

```
==> default: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
```

Logs here - http://fpaste.org/350382/99485681/

Steps to reproduce:

```
$ mkdir adb
$ curl -sL https://raw.githubusercontent.com/projectatomic/adb-atomic-developer-bundle/master/components/centos/centos-openshift-setup/Vagrantfile > Vagrantfile
$ vagrant up --provider virtualbox
```

**Comment by LalatenduMohanty** [comment]
@budhrg can you please add steps to reproduce ?

**Comment by brgnepal** [comment]
@LalatenduMohanty Updated with steps to reproduce

**Comment by surajssd** [comment]
@LalatenduMohanty this box works fine for me, when trying OpenShift, I was able to start it normally and deploy an app as well.
I am running the box on Fedora23 on Libvirt provider and the vagrant plugins installed are as:

``` bash
$ vagrant plugin list 
fog-libvirt (0.0.3)
  - Version Constraint: 0.0.3
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.2.1)
vagrant-service-manager (0.0.4)
```

**Comment by bexelbie** [comment]
Works for me F23 Virtualbox

**Comment by LalatenduMohanty** [comment]
@surajssd @bexelbie thanks , worked for me too.  @budhrg can you check again please?

**Comment by brgnepal** [comment]
@surajssd Could you update your `vagrant-service-manager` plugin ?

**Comment by surajssd** [comment]
@budhrg thanks for the notification, will do that!

**Comment by surajssd** [comment]
Is this normal? When I updated the `vagrant-service-manager` which in turn updated the `vagrant-libvirt` which I had installed using `dnf`, this won't break anything right?

``` bash
$ vagrant plugin update vagrant-service-manager
Updating plugins: vagrant-service-manager. This may take a few minutes...
Updated 'vagrant-libvirt' to version '0.0.33'!
Updated 'vagrant-service-manager' to version '0.0.5'!

$ rpm -qa | grep vagrant-libvirt
vagrant-libvirt-0.0.32-1.fc23.noarch
```

**Comment by brgnepal** [comment]
@surajssd Yes it won't break I believe.

**Comment by LalatenduMohanty** [comment]
vagrant-service-manager (0.0.5) does not work with the build. Is this https://github.com/projectatomic/vagrant-service-manager/issues/146 @navidshaikh ?

``` r
[lmohanty@LalatenduM-laptop centos-k8s-singlenode-setup]$ vagrant service-manager env docker
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

docker version --format '{{.Server.ApiVersion}}'

Stdout from the command:

Stderr from the command:

template: :1:9: executing "" at <.Server.ApiVersion>: ApiVersion is not a field of struct type types.Version
```

**Comment by LalatenduMohanty** [comment]
Using vagrant-service-manager from master fixes the above issue.

**Comment by LalatenduMohanty** [comment]
Looks like running atomicapp is broken. I believe this something to with the new atomic CLI version in ADB.

I can still run the atomicapp by running `docker run -it --rm --privileged -v /run:/run -v /:/host --net=host --name helloapache -e NAME=helloapache -e IMAGE=projectatomic/helloapache projectatomic/helloapache run`  as suggested in the command output below.

Steps to reproduce. 
- Install the rc candidate Vagrant box
- use https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-k8s-singlenode-setup Vagrantfile to do `vagrant up`
- run `vagrant ssh`
- run `sudo atomic run projectatomic/helloapache`

**Moving this to a separate issue i.e. #329**

```
[vagrant@centos7-adb ~]$ sudo atomic run projectatomic/helloapache
Using default tag: latest
Trying to pull repository docker.io/projectatomic/helloapache ... latest: Pulling from projectatomic/helloapache
1544084fad81: Pull complete 
474c2ee77fa3: Pull complete 
6ee235cf4473: Pull complete 
4816a298548c: Pull complete 
a031cf52cf7b: Pull complete 
baf743b0b5ae: Pull complete 
2e2e83265a20: Pull complete 
5196adc43dab: Pull complete 
5d88c899be7e: Pull complete 
aebfd78101e7: Pull complete 
a80fc0963aae: Pull complete 
a06d4cf90e5e: Pull complete 
3de79d2d4625: Pull complete 
7dd91e3010a6: Pull complete 
b2c7faf089cc: Pull complete 
f96ffbaec8a6: Pull complete 
7ba2613cf60c: Pull complete 
0df252a2fe0b: Pull complete 
82c3b20ede1d: Pull complete 
8e0204d03413: Pull complete 
Digest: sha256:28a041a34604f9fb77cc138794d8bf38e7ab96e70ecd496cfd9428afa477f265
Status: Downloaded newer image for docker.io/projectatomic/helloapache:latest

docker run -it --rm --privileged -v -v /run:/run -v /:/host --net=host --name helloapache -e NAME=helloapache -e IMAGE=projectatomic/helloapache projectatomic/helloapache run

This container uses privileged security switches:

INFO: --net=host 
      Processes in this container can listen to ports (and possibly rawip traffic) on the host's network.

INFO: --privileged 
      This container runs without separation and should be considered the same as root on your system.

For more information on these switches and their security implications, consult the manpage for 'docker run'.

invalid value "-v" for flag -v: -v is not an absolute path
See 'docker run --help'.
```

Version of docker and atomic RPMs in ADB

```

[vagrant@centos7-adb ~]$ sudo rpm -qa | grep docker
docker-1.9.1-25.el7.centos.x86_64
python-docker-py-1.7.2-1.el7.noarch
docker-selinux-1.9.1-25.el7.centos.x86_64
docker-forward-journald-1.9.1-25.el7.centos.x86_64

[vagrant@centos7-adb ~]$ sudo rpm -qa | grep atomic
atomic-1.9-4.gitff44c6a.el7.x86_64
```

**Comment by praveenkumar** [comment]
> vagrant-service-manager (0.0.5) does not work with the build. Is this projectatomic/vagrant-service-manager#146 @navidshaikh ?

Yes it's because docker version change and so does API call. So we always latest (master or going to be 0.0.6) for this release.

**Comment by surajssd** [comment]
@LalatenduMohanty Atomic CLI fail, that issue is reported, [issue #673](https://github.com/projectatomic/atomicapp/issues/673) in Atomic App.

**Comment by LalatenduMohanty** [comment]
@surajssd Thanks. I have reported https://github.com/projectatomic/atomic/issues/339 as this is a atomic CLI issue.

Looks like `sudo -E atomic run projectatomic/helloapache` works fine.

**Comment by navidshaikh** [comment]
> vagrant-service-manager (0.0.5) does not work with the build. Is this projectatomic/vagrant-service-manager#146 @navidshaikh ?

Correct! 
We should also have https://github.com/projectatomic/vagrant-service-manager/issues/152 fixed in next release to co-op with older boxes running with docker < 1.9.1

**Comment by kadel** [comment]
openshift2nulecule is not going to be included in ADB 1.8.0?

**Comment by LalatenduMohanty** [comment]
@kadel nope. We can add it next release. We are actually done with the release process. Currently just waiting for vagrant-service-manager release, Then will send the release mail.

**Comment by LalatenduMohanty** [comment]
https://www.redhat.com/archives/container-tools/2016-April/msg00021.html
