### ISSUE TITLE
Build a secondary bleeding-dev box that tracks upstream versions closer

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#32]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbsingh](https://github.com/kbsingh)**
_Tuesday May 12, 2015 at 10:25 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/17_

---

It might be a good option to create a second vagrant box that tracks all the upstream versions for the core components we care about here : atomic, kuberneties and docker ( maybe from the virt7-sig ? ) 

This would be in addition to the default dev box that continues to track downstream versions of these components ( to match the default CentOS-7/x86_64 user experience ).

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Tuesday May 12, 2015 at 10:48 GMT_

---

@kbsingh This is something I had in my mind. It is a good idea

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Wednesday May 13, 2015 at 12:14 GMT_

---

This is tracked at utb (upstream tracker build) branch https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/tree/utb

**Comment by bexelbie** [comment]
@LalatenduMohanty did this survive the migration to projectatomic?

**Comment by LalatenduMohanty** [comment]
@bexelbie nope.  Also I am not sure if we should pursue this idea. @kbsingh ?

**Comment by bexelbie** [comment]
I would like to to see it @LalatenduMohanty :) but it can be a post 1.0 goal

**Comment by LalatenduMohanty** [comment]
Closing this as we dont think we need it.
