### ISSUE TITLE
Where is the upstream documentation for ADB ?

### ISSUE THREAD

**Issue by tuxdna** [projectatomic/adb-atomic-developer-bundle#325]
I went to following places:
- http://www.projectatomic.io/docs/
- https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/README.rst

Eventually I managed to to setup ADB using the second link. However I found that `oc` command was not present in the VM by default. I expected OpenShift environment to be present in the VM.

> I can't find any `oc` command in ADB - Here is the output - http://fpaste.org/350211/

I figured it out only I had asked about it on IRC (  @praveenkumar  helped ). I was redirected to this link:

> tuxdna: because you didn't use openshift vagrant file and by default Vagrantfile doesn't setup openshift.
> tuxdna> praveenkumar: how does one reach from https://github.com/projectatomic/adb-atomic-developer-bundle to the link you provided
> <praveenkumar> https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-custom-vagrantfiles-for-specific-use-cases
> <tuxdna> praveenkumar: I think that instruction needs to be added in the README file
> <praveenkumar> tuxdna: ^^
> <praveenkumar> tuxdna: if you still think something missing then please file a issue and will add relevant tag to it.
- https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-custom-vagrantfiles-for-specific-use-cases

These are missing links in the documentation. We do have documentation but its difficult to follow.

I am filing this issue so that we have even better documentation for upstream users.

**Comment by Preeticp** [comment]
The https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/README.rst has a link to  the https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-custom-vagrantfiles-for-specific-use-cases; in the  What is the Typical Usage Pattern? section (More information about using the ADB is available).

**Comment by tuxdna** [comment]
@Preeticp The documentation says that 

> What does it contain?
> The ADB is built on top of CentOS 7 and contains the following:
> - Docker: container runtime and packaging
> - Atomic CLI: container usage assistance
> - Kubernetes: container orchestration
> - OpenShift Origin: a next generation PaaS for docker containers.

I would expect it would have all these setup by default i.e. on following the installation instructions. However that is not the case. We have to setup different Vagrantfile for each of the above mentioned setups. This is not clear from the documentation.

**Comment by Preeticp** [comment]
This issue has been fixed by: https://github.com/projectatomic/adb-atomic-developer-bundle/pull/453
