### ISSUE TITLE
Disk partition for CDK kickstart should be similar to ADB

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#326]
Source: https://www.redhat.com/archives/container-tools/2016-April/msg00007.html

1) the size of the /  partition seems ridiculously large at 20G (he had about 7G used, so maybe 10?)
2) the docker storage setup is using devicemapper. Would it make more sense and be faster to use one of the other storage options? 
3) Docker data size is kinda small at 6g given the vm has a 40g thinly provisioned disk.

Changes required for cdk kickstart file and should be tested on scratch build before committing to dist-git.

**Comment by bexelbie** [comment]
+1 and add docs around other mentioned issues:

1) how to extend the size of his docker storage, 2) how to do it safely, 3) how to clean up his crufty images.

**Comment by LalatenduMohanty** [comment]
@bexelbie @praveenkumar The way ADB file partition is created, docker storage is a thin pool and it would automatically expand till 32GB  as rest 8GB is assigned to /.

+1 to take this to CDK.

**Comment by bexelbie** [comment]
@LalatenduMohanty if it expands .. it is odd that it didn't do that for Burr

**Comment by LalatenduMohanty** [comment]
@bexelbie Thats because the CDK file system partition is not similar to ADB.

**Comment by bexelbie** [comment]
@praveenkumar @LalatenduMohanty perhaps you all could outline the specific changes you would make?  It sounds like we want the ADB to adopt the CDK layout and standards?

**Comment by LalatenduMohanty** [comment]
@bexelbie the change is available in https://github.com/projectatomic/adb-atomic-developer-bundle/pull/328
