### ISSUE TITLE
wrong variable name in Vagrantfile

### ISSUE THREAD

**Issue by optak** [projectatomic/adb-atomic-developer-bundle#332]
The OSE Vagrant file for CDK https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile has below 

``` ruby
  if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
    cdk.registration.username = ENV['SUB_USERNAME']
    cdk.registration.password = ENV['SUB_PASSWORD']
  end
```

creates error, because there is no "cdk", it should be "config" insted, to match

``` ruby
Vagrant.configure(2) do |config|
     config.vm.box = "cdkv2"
```

**Comment by praveenkumar** [comment]
This is resolved.
