### ISSUE TITLE
Default to mounting the user's home directory into the box

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/adb-atomic-developer-bundle#336]
A few of us discussed today the fact that we should default to mounting the user's home directory into the vagrant box via sshfs. I'll let this be a tracker for the work that is being done around that.

The idea is that we want to use the `$HOME` variable on Linux/Mac and the `$USERPROFILE` variable on windows to determine where the user's home directory is and then mount that into a predictable location within the guest.

We may need to do windows->linux path conversion for this. Standby for more information on that.

**Comment by dustymabe** [comment]
@hferentschik @LalatenduMohanty - We'll use this as a tracker for the work.

**Comment by dustymabe** [comment]
For sshfs, Hardy is also recommending that we add some extra options to default to open permissions on everything. Something like this should do the trick: 

```
sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000'
```

**Comment by LalatenduMohanty** [comment]
Here are the @hferentschik suggestions I think

```
cdk.vm.synced_folder ENV['HOME'], ENV['HOME'], type: 'sshfs', sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000'   For Linux


cdk.vm.synced_folder ENV['HOME'], ENV['USERPROFILE'], type: 'sshfs', sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000' FOr Windows
```

**Comment by dustymabe** [comment]
Not exactly. One Correction:

```
cdk.vm.synced_folder ENV['USERPROFILE'], ENV['USERPROFILE'], type: 'sshfs', sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000' FOr Windows
```

**Comment by dustymabe** [comment]
It appears using "virtualbox" synced folders does not do windows path conversion. See attached output: [vboxsf.txt](https://github.com/projectatomic/adb-atomic-developer-bundle/files/211464/vboxsf.txt)

Looks like we will need to do it in the Vagrantfile for now. As an alternative we could submit patches back up to Vagrant to do this in each synced folder implementation.

**Comment by hferentschik** [comment]
> It appears using "virtualbox" synced folders does not do windows path conversion. 

:-( Seems wrong to me

> Looks like we will need to do it in the Vagrantfile for now.

I'll look for a way of doing this...

**Comment by dustymabe** [comment]
Thanks @hferentschik

**Comment by hferentschik** [comment]
I pushed a solution into [openshift-vagrant](https://github.com/redhat-developer-tooling/openshift-vagrant/blob/master/cdk-v2/Vagrantfile#L85). Looks like this:

```
  if Vagrant::Util::Platform.windows?
    target_path = ENV['USERPROFILE'].gsub(/\\/,'/').gsub(/[[:alpha:]]{1}:/){|s|'/' + s.downcase.sub(':', '')}
    cdk.vm.synced_folder ENV['USERPROFILE'], target_path, type: 'sshfs', sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000'
  else
    cdk.vm.synced_folder ENV['HOME'], ENV['HOME'], type: 'sshfs', sshfs_opts_append: '-o umask=000 -o uid=1000 -o gid=1000'
  end
```

The OS detection we get almost for free via a Vagrant util class. The path conversion I do via a some _gsub_ conversions. I guess we could get more sophisticated there if we want.

Hopefully we get a bit of feedback from the people using openshift-vagrant, in particular when it then comes to using the synced folders as part of a Docker volume mount.

**Comment by dustymabe** [comment]
@hferentschik thanks for that. I'll try to test on my windows/linux boxes. 

I opened up two issues on vagrant-sshfs to try to help out on other small items: 
- automatically setting uid/gid on sshfs mount https://github.com/dustymabe/vagrant-sshfs/issues/20
- setting selinux boolean where applicable https://github.com/dustymabe/vagrant-sshfs/issues/19

@hferentschik please comment on those if you like.

**Comment by LalatenduMohanty** [comment]
Closing this issue as PR #413 is merged.

**Comment by valoricDe** [comment]
To use this in my vagrant file on window 7 I have to install sftp-server like described on https://winscp.net/eng/docs/guide_windows_openssh_server right? Or do you know a simpler method to get OpenSSH?

**Comment by brgnepal** [comment]
> https://winscp.net/eng/docs/guide_windows_openssh_server right? Or do you know a simpler method to get OpenSSH?

Yes, it is the preferred one.
 
However,  @valorize I would like to inform you that we are not actively maintaining this project anymore and move to [minishift](https://docs.openshift.org/latest/minishift/index.html) to provide similar solution in much better way.
