### ISSUE TITLE
Default OSE Vagrantfile still contains systemctl provisioning steps

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-atomic-developer-bundle#338]
The default Vagrantfile still contains:

```
  cdk.vm.provision :shell, inline: <<-SHELL
    systemctl enable openshift
    systemctl start openshift
  SHELL
```

With vagrant-service-manager 1.0.0 Openshift gets automatically enabled and started. The systemctl calls are not needed.

**Comment by LalatenduMohanty** [comment]
https://github.com/projectatomic/adb-atomic-developer-bundle/pull/335 will fix this
