### ISSUE TITLE
Virtual Box image needs guest additions

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#34]
<a href="https://github.com/kbsingh"><img src="https://avatars.githubusercontent.com/u/207967?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbsingh](https://github.com/kbsingh)**
_Tuesday May 12, 2015 at 11:34 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/19_

---

We might need to get guest additions added to the vbox image, lots of features in vagrant rely on those. eg:
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Tuesday May 12, 2015 at 12:08 GMT_

---

@kbsingh do you have any pointers for me, about how to do it?

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/whitel"><img src="https://avatars.githubusercontent.com/u/1832177?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [whitel](https://github.com/whitel)**
_Tuesday May 12, 2015 at 13:19 GMT_

---

Some peeps and I had discussed if it would be possible to make a container out of the additions, then they could be installed on vagrant up (or included). However, we haven't seen a lot of kernel mods in containers. This would be especially useful for atomic variants. Note, i believe the v-box additions are all open source.

**Comment by bexelbie** [comment]
@navidshaikh @imcleod

**Comment by bexelbie** [comment]
For now, we will document how to add VBox additions, if desired but they will not be shipped.

**Comment by bexelbie** [comment]
This should be revisited for addition post V2-GA.

**Comment by bexelbie** [comment]
Note - if you use vbguest it can have challenges with vagrant-registration plugin - consider this when thinking about how to do this. - This means disable the auto-update in vbguest

**Comment by tkdchen** [comment]
I'm using this in the toolkit for my project to install guest additions

```
vagrant ssh

function install_vb_additions
{
    local VB_VERSION="$1";
    sudo yum install -y wget
    local download_url=http://download.virtualbox.org/virtualbox/${VB_VERSION}/VBoxGuestAdditions_${VB_VERSION}.iso
    wget -c $download_url
    sudo mkdir /mnt/iso
    sudo mount -o loop VBoxGuestAdditions_${VB_VERSION}.iso /mnt/iso
    sudo yum install -y kernel-devel-`uname -r` gcc make perl bzip2
    cd /mnt/iso
    sudo ./VBoxLinuxAdditions.run
}

install_vb_additions 4.3.30
```

`4.3.30` is passed because I'm using that version. It depends on what version of VirtualBox is being used.

Maybe, this could be added into kickstart script. Hope this helpful.

**Comment by LalatenduMohanty** [comment]
@tkdchen this is helpful. I think you should just use curl to download the iso. s/wget/curl -O/ .

Also this can't be part of the kickstart file as koji/CBS does not have access to the internet. 
The ideal thing is to package the guest additions as RPMs.  However till that happens we can use this in the Vagrantfile.

**Comment by LalatenduMohanty** [comment]
@navidshaikh can please check, if this helps you for sync folder issue?

**Comment by navidshaikh** [comment]
Tested in latest ADB 1.5 box, installation was successful

```
Loaded plugins: fastestmirror
base                                                                                                                                                     | 3.6 kB  00:00:00     
extras                                                                                                                                                   | 3.4 kB  00:00:00     
updates                                                                                                                                                  | 3.4 kB  00:00:00     
(1/4): base/7/x86_64/group_gz                                                                                                                            | 155 kB  00:00:00     
(2/4): extras/7/x86_64/primary_db                                                                                                                        |  90 kB  00:00:00     
(3/4): updates/7/x86_64/primary_db                                                                                                                       | 1.7 MB  00:01:46     
(4/4): base/7/x86_64/primary_db                                                                                                                          | 5.3 MB  00:04:42     
Determining fastest mirrors
 * base: centos.mirror.net.in
 * extras: centos.mirror.net.in
 * updates: centos.mirror.net.in
Resolving Dependencies
--> Running transaction check
---> Package wget.x86_64 0:1.14-10.el7_0.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================
 Package                                Arch                                     Version                                           Repository                              Size
================================================================================================================================================================================
Installing:
 wget                                   x86_64                                   1.14-10.el7_0.1                                   base                                   545 k

Transaction Summary
================================================================================================================================================================================
Install  1 Package

Total download size: 545 k
Installed size: 2.0 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/wget-1.14-10.el7_0.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY        ]  0.0 B/s |    0 B  --:--:-- ETA 
Public key for wget-1.14-10.el7_0.1.x86_64.rpm is not installed
wget-1.14-10.el7_0.1.x86_64.rpm                                                                                                                          | 545 kB  00:00:00     
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-2.1511.el7.centos.2.10.x86_64 (@anaconda)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wget-1.14-10.el7_0.1.x86_64                                                                                                                                  1/1 
  Verifying  : wget-1.14-10.el7_0.1.x86_64                                                                                                                                  1/1 

Installed:
  wget.x86_64 0:1.14-10.el7_0.1                                                                                                                                                 

Complete!
--2016-01-11 05:31:40--  http://download.virtualbox.org/virtualbox/4.3.30/VBoxGuestAdditions_4.3.30.iso
Resolving download.virtualbox.org (download.virtualbox.org)... 23.201.103.154, 23.201.103.137
Connecting to download.virtualbox.org (download.virtualbox.org)|23.201.103.154|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58257408 (56M) [application/octet-stream]
Saving to: ‘VBoxGuestAdditions_4.3.30.iso’

100%[======================================================================================================================================>] 5,82,57,408  857KB/s   in 67s    

2016-01-11 05:32:48 (844 KB/s) - ‘VBoxGuestAdditions_4.3.30.iso’ saved [58257408/58257408]

mount: /dev/loop0 is write-protected, mounting read-only
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.net.in
 * extras: centos.mirror.net.in
 * updates: centos.mirror.net.in
Package kernel-devel-3.10.0-327.3.1.el7.x86_64 already installed and latest version
Package gcc-4.8.5-4.el7.x86_64 already installed and latest version
Package 1:make-3.82-21.el7.x86_64 already installed and latest version
Package 4:perl-5.16.3-286.el7.x86_64 already installed and latest version
Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
Nothing to do
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.30 Guest Additions for Linux............
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules       [  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module                   [  OK  ]
Building the shared folder support module                  [  OK  ]
Building the OpenGL support module                         [FAILED]
(Look at /var/log/vboxadd-install.log to find out what went wrong)
Doing non-kernel setup of the Guest Additions              [  OK  ]
Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.
```

Added a line in Vagrantfile for `synced_folder` and synced home directory of host with ADB box

```
  config.vm.synced_folder "/home/nshaikh/", "/home/nshaikh/"

```

Reload the box

```
vagrant reload
```

and the host's home directory is synced inside the box.

Lets test it:

First configure host's `docker` CLI to connect to `docker` daemon inside the box, we use `vagrant-adbinfo` plugin for it

```
➜  eval "$(vagrant adbinfo)"
➜ # following images are from inside the ADB box
➜  docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
openshift                    latest              80b10b73a2c9        6 days ago          485.9 MB
docker.io/openshift/origin   latest              80b10b73a2c9        6 days ago          485.9 MB
docker.io/fedora             latest              0721f2b3cb16        7 days ago          206.3 MB
docker.io/busybox            latest              fc0db02f3072        4 weeks ago         1.113 MB
```

Lets list the mounts inside the ADB box

```
➜  vagrant ssh
Last login: Tue Jan 12 00:38:21 2016 from 10.0.2.2
[vagrant@centos7-adb ~]$ mount -l | grep /home/nshaikh
none on /home/nshaikh type vboxsf (rw,nodev,relatime)

[vagrant@centos7-adb ~]$ sudo setenforce 0
[vagrant@centos7-adb ~]$ exit
logout
Connection to 127.0.0.1 closed.
```

Now we will run a container inside the box sharing a directory from the host

```
➜  mkdir /home/nshaikh/foo &&  touch /home/nshaikh/foo/bar
➜  docker run -ti -v /home/nshaikh/foo/:/shared_inside_container/ docker.io/fedora bash
[root@22fa93e4d2cd /]# ls /shared_inside_container/
bar
```

**Comment by bexelbie** [comment]
Given https://github.com/projectatomic/adb-vagrant-registration/issues/40 why should we not just advise the use of vagrant-vbguest?

**Comment by langdon** [comment]
However, that issue is a regression. vagrant-vbguest should be working.

**Comment by kbsingh** [comment]
for the Guest Additions - can we just grab the KABI tracking modules for CentOS / EL7 and use those ? would drop the need for gcc and that entire toolchain to get installed - and would have a better user experience if the user did a yum update, that included a kernel as well.

**Comment by maxandersen** [comment]
@kbsingh where is KABI coming from ? url ? 

also, anyone know where vbguest gets its additions from ?

**Comment by hferentschik** [comment]
So where are with all of this?
- We cannot use the vagrant-vbguest plugin, right?
- The `install_vb_additions` script mentioned above is really a shell script to be used on the VM, right?
- Can we add this script to the VM, so that it can just be called from the _Vagrantfile_ during provisioning? Would that be ok?
- How do we handle the registration in all that? Unless all required dependencies are pre-installed, some _yum_ commands need to run which in the case of the CDK will require that the VM is registered at that point
- Also, if we run this as part of provisioning, how do we then mount the actual directory? Synced folders are already setup at this stage, so either the user needs to restart/reload (which sucks a bit) or we mount ourselves using the appropriate mount commands as part of a provisioning script as well (which seems a bit hacky and blows up the _Vagrantfile_).

Either way, I think a step into the right directory is to make sure that the required dependencies would be installed. It would give us some flexibility when it comes to dealing with the registration issue.

Thoughts?

**Comment by LalatenduMohanty** [comment]
At this point vagrant-vbguest plugin is working fine with ADB and CDK.  Also we are using vagrant-sshfs to mount the home directory. So closing the issue.
