### ISSUE TITLE
Starting OpenShift in CDK with VSM taking more time as compared to "systemctl start openshift"

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#342]
Starting OpenShift with vagrant service manager 1.0.1 is taking more time (around 10 to 15 minutes more) as compared to "systemctl start openshift" in [Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile)

The process of "vagrant up" is taking more time because we are running `sccli openshift` in background with VSM and  it leads to run all the docker pulls and downloading new OSE images during `vagrant up`.

[1] https://registry.access.redhat.com/v1/repositories/openshift3/ose/tags

**Comment by LalatenduMohanty** [comment]
_The root cause might be because the way [SCCLI](https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.sh) uses the tags and with the way OSE images are tagged i.e.  https://registry.access.redhat.com/v1/repositories/openshift3/ose/tags_

These are the images cached in CDK before `vagrant up` done with VSM openshift provisioner

```
[vagrant@rhel-cdk ~]$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose-pod               v3.1.1.6            2b96d2bcbc46        12 days ago         428 MB
registry.access.redhat.com/openshift3/ose                   v3.1.1.6            e9c4d9124920        12 days ago         442 MB
registry.access.redhat.com/openshift3/ose-sti-builder       v3.1.1.6            983aa720a8e7        2 weeks ago         441.9 MB
registry.access.redhat.com/openshift3/ose-deployer          v3.1.1.6            d772a87d1aac        2 weeks ago         441.9 MB
registry.access.redhat.com/openshift3/ose-haproxy-router    v3.1.1.6            5e18f7fbcc6c        3 weeks ago         456.8 MB
registry.access.redhat.com/openshift3/ose-docker-registry   v3.1.1.6            3c272743b20a        3 weeks ago         478.5 MB

```

And this is after the `vagrant up`

```
[vagrant@rhel-cdk ~]$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose-sti-builder       v3.1.1.6            7ee9fa6c7597        12 days ago         442 MB
registry.access.redhat.com/openshift3/ose-deployer          v3.1.1.6            cb7cc942539a        12 days ago         442 MB
registry.access.redhat.com/openshift3/ose-haproxy-router    v3.1.1.6            b4802aef71cd        12 days ago         456.8 MB
registry.access.redhat.com/openshift3/ose-docker-registry   v3.1.1.6            12cc7a5cb779        12 days ago         478.5 MB
registry.access.redhat.com/openshift3/ose                   v3.1.1.6            e9c4d9124920        12 days ago         442 MB
<none>                                                      <none>              983aa720a8e7        2 weeks ago         441.9 MB
<none>                                                      <none>              d772a87d1aac        2 weeks ago         441.9 MB
<none>                                                      <none>              5e18f7fbcc6c        3 weeks ago         456.8 MB
<none>                                                      <none>              3c272743b20a        3 weeks ago         478.5 MB
```

**Comment by LalatenduMohanty** [comment]
As we do not have much time before GA I suggest we use "systemctl start openshift" in the Vagrantfile and disable OpenShift provisioning through VSM. This way we can improve the user experience. However an user can still use VSM to start OpenShift , which will work but will take more time.

**Comment by LalatenduMohanty** [comment]
@praveenkumar @hferentschik @navidshaikh @bexelbie ^^

**Comment by hferentschik** [comment]
> background with VSM and it leads to run all the docker pulls and downloading new OSE images during vagrant up.

What additional images are pulled? AFAIK, all images to start OpenShift are cached, no? What's the differences between `sccli` and `systemctl`?

> I suggest we use "systemctl start openshift" in the Vagrantfile and disable OpenShift provisioning through VSM

And what about the idea to use `systemctl` in vagrant-service-manager to start OpenShift? It seems another vagrant-service-manager release is needed anyways.

**Comment by LalatenduMohanty** [comment]
@hferentschik check my second comment https://github.com/projectatomic/adb-atomic-developer-bundle/issues/342#issuecomment-209266251
We still needs to do some more root cause analysis.

**Comment by navidshaikh** [comment]
> As we do not have much time before GA I suggest we use "systemctl start openshift" in the Vagrantfile and disable OpenShift provisioning through VSM.

What is causing additional images to be pulled? are we asking `sccli` to pull different images ?

**Comment by hferentschik** [comment]
> check my second comment #342 (comment)

I read your comment, but I still don't understand, especially how OSE tagging comes into play here

**Comment by praveenkumar** [comment]
> I read your comment, but I still don't understand, especially how OSE tagging comes into play here

So OSE tagging is happen like below:

```
# firefox https://registry.access.redhat.com/v1/repositories/openshift3/ose/tags

{

    "latest": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a",
    "v3.1.0.4": "62208f15133798af253a651386ae2753da9130fcc68f1863cbd735c547356173",
    "v3.1.0.4-1": "2eb816e9a7d05f6d5816be42ba21cf272770a9be1d15e839e7474c0541a40bc7",
    "v3.1.0.4-2": "d4caa301790ed1c64e2b219d82839f6ee5b4dcf3902c2f9e677b4643255e59a9",
    "v3.1.0.4-3": "62208f15133798af253a651386ae2753da9130fcc68f1863cbd735c547356173",
    "v3.1.1.6": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a",
    "v3.1.1.6-10": "b9797469249dcae21e0ee09e9ce57ea4b243515f6022acaaed2fb1151a2b78c4",
    "v3.1.1.6-12": "fdb14d058b48fb0bb35a02d8bec596b974eae51cec864311d2686fd23335ef5b",
    "v3.1.1.6-14": "37824d3edc2e2549bfdd1e96e143d4bdd36bd6b0332004d9444afc8f9072c20d",
    "v3.1.1.6-15": "f69933b7fc281c95974b2af80fcf05ceb7e5e7717c16657a271048f430826353",
    "v3.1.1.6-16": "88178069a37f78271c153243521cc5c11fd96bcda2ce7bdedd458b4b50ce5115",
    "v3.1.1.6-17": "e9c4d91249206195e012c51a85fd47a31b6f0d2364af4c4c3736b5f5e2ecd57a",
    "v3.1.1.6-3": "f489edbeb9a70ced0065e7610fbdfa94929f132331fc63d656da951ddd36ba15"
}
```

Now assume new fix they want to release so they do tagging as v3.1.1.6-18 and then map it to latest and v3.1.1.6 tag now when sccli do `docker pull` it will see there is a new checksum for layered images and it pulled it. Since this is something which they planned it to do that way so when we cached our image it might be case that time it was 3.1.1.6-16 and now it 3.1.1.6-17

**Comment by praveenkumar** [comment]
> What is causing additional images to be pulled? are we asking sccli to pull different images ?

No, we are not asking `sccli` to get new images they got updated on registry.access.redhat.com with same tag which is why it's pulling.

**Comment by praveenkumar** [comment]
> What's the differences between sccli and systemctl?

sccli first do `docker pull <registry>/<image_name>:<tag>` even there is already cached images just to make sure images are available before starting service. Now in this process if a image tag is updated with different layer then it will fetch it before start openshift service. In other hand `systemctl` only start openshift service and not do any checks on image availability on system (so cached images will be used as it is without and any check). 

> And what about the idea to use systemctl in vagrant-service-manager to start OpenShift? 

To update our vagrant file to make vsm not  to configure openshift (`config.servicemanager.services = 'docker'`) and then in shell provisioning we do it using `systemctl enable openshift` and `systemctl start openshift`.

**Comment by hferentschik** [comment]
So we should use a fixed tag, right? Something which is stable, eg 3.1.1.6-17? The whole point is that we want to make sure that we know what a user will get.

**Comment by hferentschik** [comment]
On that note, why would they reuse a tag like _3.1.1.6_, instead of just keeping incrementing, eg  _3.1.1.7_? This is the exact same discussion we have with build artifacts. Once tagged with a specific version it should stay stable. Or am I missing something here?

**Comment by praveenkumar** [comment]
> So we should use a fixed tag, right? Something which is stable, eg 3.1.1.6-17?

I also thought same but when I looked through other cached images tag then they are also different.

```
ose-image-builder
-----------------------
{

    "latest": "7ee9fa6c759703f3cd93f11dcf0745867a77c06b5d87bc001b14968bab53a6bd",
    "v3.1.1.6": "7ee9fa6c759703f3cd93f11dcf0745867a77c06b5d87bc001b14968bab53a6bd",
    "v3.1.1.6-11": "a07169e0dbdcd03df032865c6fc3552b374252a83f8c17862c142759c93ac300",
    "v3.1.1.6-12": "75fa4984985abd605b589d735fb1cec9010ca2e1cd18715efec4f559e65c4045",
    "v3.1.1.6-13": "538dc202b5be69cf6e74425d0e90e1bddd087b14336514dc65e078231c4047cf",
    "v3.1.1.6-14": "983aa720a8e7e5cbf4e694e55251be88b443856ccebd666750c851930028ba83",
    "v3.1.1.6-15": "7ee9fa6c759703f3cd93f11dcf0745867a77c06b5d87bc001b14968bab53a6bd",
    "v3.1.1.6-3": "f6ae4f3e6b020e43cac489a6cd8cbc9d143784457cd92e6322fba3b8908b43ed",
    "v3.1.1.6-9": "87107c0f1a3446ad5cf8e9853385dc74fdae940fde76367b4894a4bb2fc3b19f"

}

ose-deployer
-----------------
{

    "latest": "cb7cc942539a6ee47a49394f058248272f8be2b0ae74232820836e386be9d011",
    "v3.1.1.6": "cb7cc942539a6ee47a49394f058248272f8be2b0ae74232820836e386be9d011",
    "v3.1.1.6-10": "012473dd2d13e1a211a7857977d04a35dbc2064f9bd155a382031d20cf205a9c",
    "v3.1.1.6-12": "4f01e003652d1ec6164ba8936d0b8bbeb52b21c1e3e542c1ec84f0466dbb4272",
    "v3.1.1.6-13": "3bcee4233589f510e35bb3d2386c424d430e74e13bd98a286af07f36437723a2",
    "v3.1.1.6-14": "e0867def701788b19933abb725d666de76eb8dc5154eb5e7c7a821b4201bcc6c",
    "v3.1.1.6-15": "d772a87d1aac30b609959b402759796619166f914cc5247e1981f86f0ebf157c",
    "v3.1.1.6-16": "cb7cc942539a6ee47a49394f058248272f8be2b0ae74232820836e386be9d011",
    "v3.1.1.6-3": "c86dcc5d726fdc1a798f1b74497ffe8214962b3bfd9e7044ee93b61923693a29"
}

ose-pod
-----------

{

    "latest": "2b96d2bcbc46f13718fc1a93a90154ccf3839943b80a60584dc8c5d9dda81d6a",
    "v3.1.1.6": "2b96d2bcbc46f13718fc1a93a90154ccf3839943b80a60584dc8c5d9dda81d6a",
    "v3.1.1.6-3": "ec2a195f885e90d9ed5b3828ce1389d244676386972be6749a70b35a0c06ee68",
    "v3.1.1.6-5": "b22dd4643451dcaa0eba94e0331780e72dd1b5f1181195e63140fcf5283bea2d",
    "v3.1.1.6-6": "ecfbff48161cfa7acb4e1aba20243e9f70084bce66100e8e3e92bea356018e68",
    "v3.1.1.6-8": "2b96d2bcbc46f13718fc1a93a90154ccf3839943b80a60584dc8c5d9dda81d6a"
}

```

So we either have to cached each tag with minor version and test and see that ose minor `-15` work with minor  `-8` of pod.

**Comment by LalatenduMohanty** [comment]
Yes, the root cause is because OSE is using tag like v3.1.1.6-16 and v3.1.1.6-17 when sccli expect to be as just v3.1.1.6. 

Check below cmds. The shasum for v3.1.1.6-16 is same with cached images , so the docker pull for v3.1.1.6-16 does not happen as it is already present but I can do docker pull for v3.1.1.6-17.

```
[vagrant@rhel-cdk ~]$ docker images
REPOSITORY                                                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/openshift3/ose                   v3.1.1.6            88178069a37f        2 weeks ago         441.9 MB
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[vagrant@rhel-cdk ~]$ docker pull registry.access.redhat.com/openshift3/ose:v3.1.1.6-16
88178069a37f: Download complete 
bf63a676257a: Download complete 
23477b5172dc: Download complete 
Status: Image is up to date for registry.access.redhat.com/openshift3/ose:v3.1.1.6-16
registry.access.redhat.com/openshift3/ose: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.

[vagrant@rhel-cdk ~]$ docker pull registry.access.redhat.com/openshift3/ose:v3.1.1.6-17
e9c4d9124920: Download complete 
95612a3264fc: Download complete 
92d4a31b3152: Download complete 
Status: Downloaded newer image for registry.access.redhat.com/openshift3/ose:v3.1.1.6-17
registry.access.redhat.com/openshift3/ose: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```

**Comment by LalatenduMohanty** [comment]
Raised https://github.com/projectatomic/adb-utils/issues/106 to track future discussions.

**Comment by navidshaikh** [comment]
> No, we are not asking sccli to get new images they got updated on registry.access.redhat.com with same tag which is why it's pulling.

thats the reason I had asked the question here https://github.com/projectatomic/adb-utils/pull/103#issuecomment-208835255 about understanding how OSE images are tagged.  But @praveenkumar , you said they bump minor versions https://github.com/projectatomic/adb-utils/pull/103#issuecomment-209217704 
Its important to understand the update cadence happening for images to effectively consume them.

**Comment by praveenkumar** [comment]
>  But @praveenkumar , you said they bump minor versions projectatomic/adb-utils#103 (comment)

yes that was my assumption till today and I was wrong.
