### ISSUE TITLE
Do we need docker-base-setup and Vagrantbox ReadMe?

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#353]
Currently we have docker-base-setup Vagrantfile (https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-docker-base-setup)  which I am not sure now what is the use-case because vagrant service-manager can do docker provision now. So either we can remove this file or we can add vsm config to configure docker.

Also we have a README file which seems outdated and may be not required in this repo (https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/boxes/vagrant-boxes.md)

@LalatenduMohanty @bexelbie thoughts?

**Comment by brgnepal** [comment]
+1 for removing it as it is being addressed by `vagrant-service-manager` plugin by default.

**Comment by bexelbie** [comment]
I believe the Vagrantfile should stay as it shows all of the other setup options.  Until we have a better box Vagrantfile I think we should offer this.

The README should be deleted, but only after we ensure that our docs have links to box options somewhere.  I am offline most of the day today :(  @Preeticp can you review this?

**Comment by Preeticp** [comment]
I will review this Bex.

**Comment by praveenkumar** [comment]
> I believe the Vagrantfile should stay as it shows all of the other setup options. Until we have a better box Vagrantfile I think we should offer this. 

So we have to update this vagrant file to put vsm for configure `docker`

`config.servicemanager.services = 'docker'`

**Comment by praveenkumar** [comment]
> The README should be deleted, but only after we ensure that our docs have links to box options somewhere.

If you check https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/boxes/vagrant-boxes.md contain CentOS images not relevant to ADB so I am not sure those will be included in doc? (CC @LalatenduMohanty )

**Comment by LalatenduMohanty** [comment]
We should not delete https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/centos/centos-docker-base-setup as it has meta data required to run ADB on OpenStack.  We should update the Readme with vagrant-service-manager alternative. So the user can choose accordingly.

**Comment by praveenkumar** [comment]
@LalatenduMohanty what about https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/boxes/vagrant-boxes.md ?

**Comment by LalatenduMohanty** [comment]
@praveenkumar yeah we can remove that.
