### ISSUE TITLE
python-docker-py package should be removed from kickstart

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#356]
Currently we have listed https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/kickstarts/centos-7-adb-vagrant.ks#L55-L57 `python-docker-py` package which was added because of openshift2nulecule and now we don't require it any more.

**Comment by navidshaikh** [comment]
We don't need to downgrade python-docker-py package or we don't need it at all ?

**Comment by LalatenduMohanty** [comment]
@navidshaikh it automatically get installed as atomic CLI has a dependency on it.

**Comment by LalatenduMohanty** [comment]
Here is the cause for the workaround https://github.com/projectatomic/adb-atomic-developer-bundle/issues/279#issuecomment-194110557

**Comment by navidshaikh** [comment]
Okay- so the answer is we do not need to downgrade it.
