### ISSUE TITLE
Modify Repository Description

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#357]
Our current Repo description seems to reference a RH product.  Can we modify it to be more descriptive?  Maybe:

The Atomic Developer Bundle is a Vagrant Virtual Machine that provides a full featured container development and testing environment.

**Comment by praveenkumar** [comment]
@bexelbie Completely agree +1

**Comment by praveenkumar** [comment]
@bexelbie I think it's modified, Can we close this issue now?

**Comment by bexelbie** [comment]
yep
