### ISSUE TITLE
Change the default hostname of the vagrant box to "centos"

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#36]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Wednesday May 13, 2015 at 16:32 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/28_

---

**Comment by LalatenduMohanty** [comment]
PR https://github.com/projectatomic/adb-atomic-developer-bundle/pull/56

**Comment by bexelbie** [comment]
I would prefer something like adb that isn't tied to the underlying distribution.

**Comment by navidshaikh** [comment]
Related with the TLS certs generation of `docker` daemon with DNS wildcards.

**Comment by LalatenduMohanty** [comment]
The PR is merged. Hence closing the issue
