### ISSUE TITLE
Why not default to "latest" openshift container images?

### ISSUE THREAD

**Issue by jeremyeder** [projectatomic/adb-atomic-developer-bundle#370]
Found places where this is hard-coded to either 1.1.1 (in this repo) or 1.1.3 (in adb-utils).  I realize there's the environment IMAGE_TAG work around but I don't see why anyone would want old versions by default.

**Comment by jeremyeder** [comment]
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/Vagrantfile#L9

https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.py#L44
https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.sh#L75

**Comment by LalatenduMohanty** [comment]
I think there are two bugs.
1. The Vagrantfile should use the 1.1.3. Also we are planning to move to 1.1.6.
2. sccli should only set default value if the version is populated in the environment e.g. from the Vagrantfile.

**Comment by jeremyeder** [comment]
Is there some reason not to use :latest ?

**Comment by LalatenduMohanty** [comment]
> Is there some reason not to use :latest ?

Yes, As per our understanding origin updates origin docker images every night  through a CI job and we are skeptical that it might break stuff and create a bad user experience.

**Comment by jeremyeder** [comment]
Ahh -- so perhaps we can request a :stable tag ?

**Comment by praveenkumar** [comment]
> Ahh -- so perhaps we can request a :stable tag ?

@jeremyeder yes, they do provide stable tags (after sanity testing from latest) https://hub.docker.com/r/openshift/origin/tags/ and currently 1.1.6 which is latest. now to include that to ADB box we also test it how it behave with our vagrant box (CentOS based). I recently encountered a bug (https://github.com/projectatomic/adb-atomic-developer-bundle/pull/368) when we tried to update it to `1.1.3` and still need some time to investigate.

**Comment by jeremyeder** [comment]
OK thanks, now I understand the integration of openshift into adb is more complicated than just fixing tags.  So does this mean the latest I can run is 1.1.3?

**Comment by praveenkumar** [comment]
@jeremyeder Currently we tested 1.1.1 which you can run but if you want to experiment with different tags of then please specify that to Vagrantfile which have variable for image tag and hope it didn't break (like 1.1.3 was broke for me).

**Comment by hferentschik** [comment]
There is also the argument of repeat-ability. If we are using tags like 'stable' or 'latest', the behavior of a created VM instance might differ depending on when it gets created. This could introduce very hard to track/debug problems when the behavior between two VM instances differ.

**Comment by praveenkumar** [comment]
@jeremyeder I hope you got answer of your question and if you don't have any other specific query, we would like to close this issue.
