### ISSUE TITLE
openshift: Default root to system:admin login

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/adb-atomic-developer-bundle#371]
Regarding the OpenShift box, It would make sense for ADB users to also be able to administrate the cluster for multiple reasons - e.g. being able to enable custom SCCs for different Docker images.

The simplest would be to change root's `.bashrc` to do:

```
export KUBECONFIG=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig 
```

**Comment by praveenkumar** [comment]
@cgwalters We do have an `admin` user for ADB box which have cluster management permissions.

```
oc login -u admin -p admin
```

**Comment by LalatenduMohanty** [comment]
@cgwalters as @praveenkumar mentioned, we have a cluster administrator  i.e. admin/admin who should be able to change the SCCs for PODs.

**Comment by cgwalters** [comment]
Yeah...I think using openshift-ansible has conditioned me to expect `root` is automatically logged in to the cluster.   Dunno, feel free to close this, but the `KUBECONFIG` tweak should be easy too.

**Comment by praveenkumar** [comment]
> Yeah...I think using openshift-ansible has conditioned me to expect root is automatically logged in to the cluster. 

@cgwalters might be, Can you point out which openshift-ansible script you are using (github link) and also what you trying to provision with it? I think you can do a little hack to ansible script or add a task for cluster-admin.

**Comment by cgwalters** [comment]
https://github.com/openshift/openshift-ansible

I'm not using openshift-ansible with the ADB, just saying matching the behavior would be nice.

**Comment by praveenkumar** [comment]
> I'm not using openshift-ansible with the ADB, just saying matching the behavior would be nice.

@cgwalters  We did have that behavior in past (mostly unsecured access) and after lot of discussion and iteration we landed up to our current behavior, so I am in favor to keep it as it is until we have some blocker which required a change.  

Also I will close this issue if you do agree with me otherwise we can have more specific discussions.
