### ISSUE TITLE
Exposing the registry

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/adb-atomic-developer-bundle#372]
As a container developer, a primary use case is to develop my container in the vagrant environment, get it running as non-root, then try it on openshift. After docker build we need to create a project, login to the registry and push the image to openshift. This creates an image stream that we can then run `oc new-app <imagestream>` and see how the new image works in openshift. Here are the gaps I experienced in trying this workflow:
- I didn't know the registry endpoint and cannot discover it as user openshift-dev
- I didn't know that I needed to or how to login to the registry. Token? What token? How do I use it?
- I didn't know that was the workflow

Here's what I'd like to see added to the vagrant up workflow for the rhel-ose and centos-openshift-setup components:
1. Login as **admin** user
   
   ```
   oc login -u admin -p admin
   ```
2. As user **admin** get the registry endpoint (using service here since I wasn't sure if route was reliable for all configurations)
   
   ```
   oc get service docker-registry -n default --template '{{ .spec.clusterIP }}'
   ```
3. Login as **openshift-dev** user. This has the added benefit of caching a session so the user is automatically logged in when entering the environment.
   
   ```
   oc login -u openshift-dev -p devel
   ```
4. As user **openshift-dev** get the session token
   
   ```
   oc whoami --token
   ```
5. Run docker login for the user so docker push to the integrated registry will "just work".
   
   ```
   docker login -p <user_session_token> -u unused -e unused <registry_service>:5000
   ```
6. Print the registry IP:PORT after `vagrant up` so the user knows how to tag and push an image.
   
   ```
   If you are building docker images you can tag and push them to the integrated OpenShift registry:
       oc new-project test
       docker tag IMAGE REGISTRY:PORT/test/IMAGE
       docker push REGISTRY:PORT/test/IMAGE
   This will create a image stream so you can try it out:
       oc new-app IMAGE
   ```

**Comment by LalatenduMohanty** [comment]
@aweiteka @praveenkumar I think it is an documentation issue as user can use the openshift registry in ADB/CDK. 

If you check the below command output you can see `export DOCKER_REGISTRY=hub.openshift.adb` which can used by user. But we need to add more documentation for this.

```
[lmohanty@LalatenduM-laptop centos-openshift-setup]$ vagrant service-manager env

# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://192.168.121.67:2376
export DOCKER_CERT_PATH=/home/lmohanty/vagrantboxes/adb/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.22

# openshift env:
# You can access the OpenShift console on: https://192.168.121.67:8443/console
# To use OpenShift CLI, run: oc login https://192.168.121.67:8443
export OPENSHIFT_URL=https://192.168.121.67:8443
export OPENSHIFT_WEB_CONSOLE=https://192.168.121.67:8443/console
export DOCKER_REGISTRY=hub.openshift.adb
```

**Comment by LalatenduMohanty** [comment]
Moving this issue to https://github.com/projectatomic/adb-atomic-developer-bundle/issues/547.
