### ISSUE TITLE
Having problems running Fabric8 on CDK 2.   CDK's version of OSE is too old.  

### ISSUE THREAD

**Issue by alberttwong** [projectatomic/adb-atomic-developer-bundle#377]
https://github.com/fabric8io/gofabric8/issues/53

**Comment by LalatenduMohanty** [comment]
@alberttwong you can a newer docker hub Origin image's tag [1] in the Vagrantfile to use newer version. We are also testing the newer versions and will update the Vagrantfile.

[1] https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/Vagrantfile#L9

**Comment by hferentschik** [comment]
Will be addressed by pull request #412

**Comment by LalatenduMohanty** [comment]
Closing the issue as #412 is merged now and you can use it with ADB 2.2.0 version.
