### ISSUE TITLE
ADB OpenShift readme should have information about how to use latest Origin image

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#379]
We need to document [1] how an user can use a newer Origin image with ADB.

[1] https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/centos/centos-openshift-setup/README.rst

**Comment by bexelbie** [comment]
@Preeticp lines ~51-69 of https://github.com/projectatomic/adb-utils/blob/master/README.rst contain this data.  Can you prepare a PR that modifies the README mentioned above?
