### ISSUE TITLE
Rebuild ADB when new atomic CLI ships

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#397]
See: https://github.com/projectatomic/atomic/issues/339

This bug causes all atomic apps to fail as documented.

**Comment by LalatenduMohanty** [comment]
@bexelbie this is duplicate of https://github.com/projectatomic/adb-atomic-developer-bundle/issues/329
We should close one of them. Feel free to close one you like.
