### ISSUE TITLE
Add .gitattributes to stop PR conflicts on CHANGELOG

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#403]
See https://github.com/projectatomic/vagrant-service-manager/blob/master/.gitattributes

**Comment by brgnepal** [comment]
This only helps in solving conflicts for CHANGELOG at local machine level through CLI.
It doesn't have any effect at the web (github) level. Anyhow, one has to do `git push origin pr-branch -f` to fix at web level.

**Comment by bexelbie** [comment]
@budhrg to avoid merge commits, we have been talking about only doing merges at the prompt using git directly.  Therefore this can help :)

**Comment by brgnepal** [comment]
@bexelbie But sometimes this solution of auto-merging is not efficient enough and it need manual interaction like in [this PR](https://github.com/projectatomic/vagrant-service-manager/pull/215/files)

**Comment by praveenkumar** [comment]
@bexelbie @budhrg I would say, we should stop updating CHANGELOG and when we do a release then maintainer should update it, like we were doing previously.

**Comment by bexelbie** [comment]
This is not a magical fix for all problems.  Examples like yours should still be resolved manually.  This would just help in some cases.

That said, if we are going to stop clicking the web button altogether then this may not be needed.  As long as we always rebase the PR before merging locally.

**Comment by hferentschik** [comment]
TBH, I have not tried yet what this flag does. As long as it works on my local checkout I am fine. I can see though that you will need to deal with conflicts here and there regardless. They should be easy enough to sort out, but I understand that they are also a bit of a pita. 

As an alternative, the merger of the pull request can add the commit updating the changelog. This way the file won't get touched until just before the merge.

**Comment by bexelbie** [comment]
@praveenkumar I like seeing the CHANGELOG always represent what is in HEAD.  This way in progress code is easier to understand.  It also makes the maintainers life a lot easier and encourages more frequent releases.

**Comment by hferentschik** [comment]
> I would say, we should stop updating CHANGELOG and when we do a release then maintainer should update it, like we were doing previously. 

+1 This is common practice in all Open Source projects I have been working on.
There might be a slight advantage for potential viewers of the CHANGELOG, but it also has an additional friction point for development.

**Comment by LalatenduMohanty** [comment]
Honestly I am not a fan of maintaining a separate changelog. I am only doing it as you guys like it :)

If you want to check commits between two releases a simple git command can help e.g. `git log --pretty=oneline v1.5.0..v1.6.0 --no-merges`

**Comment by hferentschik** [comment]
> It also makes the maintainers life a lot easier

On the contrary, no? It seems it makes it harder since we more often have to resolve conflicts.

> and encourages more frequent releases.

I am missing the causal relationship. I see no relation between updating the CHANGELOG as you go and the frequency of releases.

**Comment by hferentschik** [comment]
@bexelbie 4 against 1 :-)

**Comment by bexelbie** [comment]
@hferentschik I feel like any increase in steps required to get a release out creates friction on the release.  Obviously I will do as the group decides.

**Comment by hferentschik** [comment]
> I feel like any increase in steps required to get a release out creates friction on the release.

Sure, you need to do this as part of the release, but at this stage my mind is set to do a release anyways. I will need to update the version, update release dates, verify the tests pass, groom the milestones _and_ update the changelog.

**Comment by hferentschik** [comment]
I think we can close this, right?
