### ISSUE TITLE
 /tmp/vagrant-shell dev/null: No such file or directory

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#407]
I am getting following error on Vagrant up on [kubernetes vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile):

```
/tmp/vagrant-shell: line 9: dev/null: No such file or directory in CDK 
```

Steps to reproduce 
1. cd /cygdrive/c/Users/.../Desktop/cdk/cdk/components/rhel/misc/rhel-k8s-singlenode-setup
2. vagrant up 
 /tmp/vagrant-shell: line 9: dev/null: No such file or directory

Open Vagrantfile and add "/" to overcome this error 
Before 
sudo systemctl enable kube-proxy kubelet > dev/null 2>&1
After change 
sudo systemctl enable kube-proxy kubelet > /dev/null 2>&1
after doing this change do vagrant up it will work fine .

Logs 
$ vagrant.exe up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'cdkv2'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: rhel-k8s-singlenode-setup_default_1464178908673_19266
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2200 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Registering box with vagrant-registration...
    default: Would you like to register the system now (default: yes)? [y|n]n
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
==> default: Copying TLS certificates to C:/Users/naina/Desktop/nightly-build/cdk/cdk/components/rhel/misc/rhel-k8s-singlenode-setup/.
vagrant/machines/default/virtualbox/docker
==> default: Rsyncing folder: /cygdrive/c/Users/naina/Desktop/nightly-build/cdk/cdk/components/rhel/misc/rhel-k8s-singlenode-setup/ =>
 /vagrant
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: /tmp/vagrant-shell: line 9: dev/null: No such file or directory

**Comment by LalatenduMohanty** [comment]
This is fixed in #411
