### ISSUE TITLE
Include newer version of atomic command

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#41]
<a href="https://github.com/vpavlin"><img src="https://avatars.githubusercontent.com/u/4759808?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vpavlin](https://github.com/vpavlin)**
_Friday Jul 17, 2015 at 11:40 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/43_

---

In https://github.com/projectatomic/atomic/commit/c97e5d3255b85c715fbbb8e17945beffeefc2332 there was an addition of `$OPTx` feature which lets you to modify labels when running `atomic install|run|uninstall|stop` commands. We merge the patch for Atomic App using this feate and thus we need to get a newer version of atomic into the dev box.

i.e. newer than commit c97e5d3255b85c715fbbb8e17945beffeefc2332

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Friday Jul 17, 2015 at 11:52 GMT_

---

@vpavlin Thats difficult as the box consumes packages from CentOS Core. So I dont see a way to take the new patch unless it comes as an update in RHEL 7. CC @kbsingh

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Friday Jul 17, 2015 at 14:31 GMT_

---

@vpavlin Specially when we dont know which release of atomic this patch will land. Also there is no release happening from atomic's github repo

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Tuesday Jul 21, 2015 at 11:41 GMT_

---

The upstream release stuff is being discussed in https://github.com/projectatomic/atomic/issues/72

**Comment by bexelbie** [comment]
This appears to have landed.  @LalatenduMohanty I think this can be closed.

**Comment by LalatenduMohanty** [comment]
@bexelbie yes, Thanks
