### ISSUE TITLE
Vagrant box size reduce (different ways to do it)

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#419]
- [ ] Check packages which can be removed.
- [ ] yum clean all after provision.
- [ ] Remove docs from `/usr/share/doc`
- [ ] Look out if any other better way?

**Comment by LalatenduMohanty** [comment]
I believe these are trying to achieve the same result https://github.com/projectatomic/adb-atomic-developer-bundle/issues/176

**Comment by praveenkumar** [comment]
@LalatenduMohanty yes thanks to point out, I will close this and add this to that issue.
