### ISSUE TITLE
Expose Docker Daemon Port

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#42]
<a href="https://github.com/bexelbie"><img src="https://avatars.githubusercontent.com/u/7413661?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bexelbie](https://github.com/bexelbie)**
_Monday Jul 27, 2015 at 09:39 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/issues/49_

---

The Docker Daemon port needs to be exposed and TLS certificates made available to the host so that the box can be used as a docker provider on non-linux hosts and so that external tools, such as eclipse can work with the docker daemon in the box.

I believe that by default, we should use port forwarding and create a port on localhost that is forwarded to the docker daemon.  We should document using a private_network IP to accomplish the same task.  We should also generate a tls certificate pair and place the appropriate component on the host for future use.

A small program or plugin can be to set up environment variables for host consumers.

Opinions/ideas welcome.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/LalatenduMohanty"><img src="https://avatars.githubusercontent.com/u/3125299?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LalatenduMohanty](https://github.com/LalatenduMohanty)**
_Tuesday Jul 28, 2015 at 12:44 GMT_

---

@bexelbie Sounds good to me. I need to do some background study on this before I can actively work on this.

**Comment by LalatenduMohanty** [comment]
<a href="https://github.com/bexelbie"><img src="https://avatars.githubusercontent.com/u/7413661?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bexelbie](https://github.com/bexelbie)**
_Tuesday Jul 28, 2015 at 12:59 GMT_

---

I am hoping to have an initial PR today/tomorrow that has most of the goodness in it.  Then you can review it.

**Comment by bexelbie** [comment]
@navidshaikh is now working on this and will hopefully be pushing code soon :)

**Comment by bexelbie** [comment]
This is complete.
