### ISSUE TITLE
OpenShift Vagrantfile uses hardcoded IP for giving OpenShift information

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#439]
OpenShift Vagrantfile uses hardcoded IP for giving OpenShift information. However for provider like libvirt and HyperV we do not need  a private address in the Vagrantfile. In case of libvirt the default IP is routable from workstation and for HyperV ignores network setting in Vagrantfiles and only uses external type networking which is routable IP address [1]. Hence we need to findout which IP is used for OpenShift setup and then print it. 

Thanks to @naina-verma  for testing HyperV beta images. 

Refer https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L74-78

```
config.vm.provision "shell", run: "always", inline: <<-SHELL
    echo
    echo "Successfully started and provisioned VM with #{VM_CPU} cores and #{VM_MEMORY} MB of memory."
    echo "To modify the number of cores and/or available memory set the environment variables"
    echo "VM_CPU respectively VM_MEMORY."
    echo
    echo "You can now access the OpenShift console on: https://#{PUBLIC_ADDRESS}:8443/console"
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ vagrant ssh"
    echo "$ oc login #{PUBLIC_ADDRESS}:8443"
    echo
    echo "Configured users are (<username>/<password>):"
    echo "openshift-dev/devel"
    echo "admin/admin"
    echo
    echo "If you have the oc client library on your host, you can also login from your host."
    echo
  SHELL
end
```

[1]  https://www.vagrantup.com/docs/hyperv/limitations.html

```
Vagrant does not yet know how to create and configure new networks for Hyper-V. When launching a machine with Hyper-V, Vagrant will prompt you asking what virtual switch you want to connect the virtual machine to.

A result of this is that networking configurations in the Vagrantfile are completely ignored with Hyper-V. Vagrant cannot enforce a static IP or automatically configure a NAT.
```

**Comment by LalatenduMohanty** [comment]
Here is the proposed solution.

```
config.vm.provision "shell", run: "always", inline: <<-SHELL
    #Get the routable IP address of OpenShift
    OSIP=`/opt/adb/openshift/get_ip_address`
    echo
    echo "Successfully started and provisioned VM with #{VM_CPU} cores and #{VM_MEMORY} MB of memory."
    echo "To modify the number of cores and/or available memory set the environment variables"
    echo "VM_CPU respectively VM_MEMORY."
    echo
    echo "You can now access the OpenShift console on: https://${OSIP}:8443/console"
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ vagrant ssh"
    echo "$ oc login ${OSIP}:8443"
    echo
    echo "Configured users are (<username>/<password>):"
    echo "openshift-dev/devel"
    echo "admin/admin"
    echo
    echo "If you have the oc client library on your host, you can also login from your host."
    echo
  SHELL
end
```

**Comment by LalatenduMohanty** [comment]
@praveenkumar @hferentschik thoughts?

**Comment by praveenkumar** [comment]
@LalatenduMohanty this was also raised before iirc, now VSM is tightly coupled with our ADB/CDK box and creates automatic a private networking which can/can't be consumed by specific providers (In our case hyperV).  However proposed solutions look good to me.

**Comment by praveenkumar** [comment]
@LalatenduMohanty Also please make sure it is tested across providers.

**Comment by LalatenduMohanty** [comment]
@praveenkumar IFAIR VSM only creates private networking for Virtualbox , not for any other provider. Which is fine IMO.

**Comment by praveenkumar** [comment]
@LalatenduMohanty Nope it create for other provider also @navidshaikh please confirm.

**Comment by LalatenduMohanty** [comment]
> Also please make sure it is tested across providers.

@praveenkumar I am not changing the existing networking changes in the Vagrantfile. That would be a separate issue/PR.  This is only the IP information. I have also checked VSM and it uses the same expression as `/opt/adb/openshift/get_ip_address` to findout the IP address and `vagrant service-manager env` prints the correct information for Virtualbox and HyperV both. We should cross test libvirt too cc @naina-verma.

**Comment by navidshaikh** [comment]
> IFAIR VSM only creates private networking for Virtualbox , not for any other provider. 

@praveenkumar : 
That's correct. There is a check in VSM for VirtualBox provider before adding private networking if not explicitly configured in Vagrantfile.

**Comment by hferentschik** [comment]
We have to be very careful with this change. This implies that everyone will get a different IP which is ok I guess. The problem is documentation. All documentation, demos, examples work around the fixed IP. In our case 10.1.2.2. Once you release this, people using the docs will have issues. Also URLs cannot be cut&paste anymore. So applying this change requires close communication with the docs team. Given that the URLs will be variable, it might not be so easy to document anymore.

What is the time frame for this? I am very close to a Landrush 1.1.0 release. Once this is out we can use Landrush per default. This allows us to hide IPs altogether and use hostnames everywhere - access to console, app routes, documentation, etc. Once this happens we need again to sync with the docs team. I am wondering whether we should not wait and align this change with a switch to Landrush.

Does anyone know a GitHub user id we can ping in this thread and who is involved in the docs? They should be made aware of this discussion.

**Comment by hferentschik** [comment]
> I am not changing the existing networking changes in the Vagrantfile. That would be a separate issue/PR. This is only the IP information

Ahh, I missed this part. I guess then it is fair enough.

**Comment by brgnepal** [comment]
@LalatenduMohanty This can be closed as the changes are merged now https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L80

**Comment by LalatenduMohanty** [comment]
@budhrg thanks.
