### ISSUE TITLE
Network configuation changes required for Vagrantfiles to work with HyperV

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#440]
It is a known issue that networking configurations in the Vagrantfile are completely ignored with Hyper-V [1] . External virtual switch (network configuration) of HyperV works with Vagrant to give a routable IP adress. However it does not support static IP address with Vagrant. So we can only expect dhcp IP address when HyperV is used.

As OpenShift Vagrantfile uses hardcoded IP for giving OpenShift information , to handle this thing in a single Vagrantfile there should be a handler in Vagrantfile to perform specific actions when provider is "HyperV" not the libvirt or virtualbox.

`config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"`  .
Above statement should execute only for libvirt/virtualbox not for  HyperV

[1] https://www.vagrantup.com/docs/hyperv/limitations.html

**Comment by LalatenduMohanty** [comment]
With HyperV we will have 3 providers for CDK and ADB i.e. Libvirt, Virtualbox and HyperV. We had a small discussion with @hardy and @praveenkumar and we think we can create a Vagrantfile without any networkconfig and it will work for all the 3 providers and that would be ideal solution for this issue. The details of the proposed solution:
- The idea is to move towards a dhcp based routable IP address for ADB/CDK.
- However user does not have to deal with IP address as we can use a human readable host name with help from landrush. So the proposed solution need integration with landrush Vagrant plugin.
- Virtualbox needs a private networking dhcp settings and VSM can set it up by default without networking settings in the Vagrantfile.
- For Libvirt the default NAT IP address work as a routable IP address so we do not need any network setting for it in the Vagrantfile.
- HyperV also does not need any network settings and the dhcp IP can be accessed from the workstation.

**Comment by LalatenduMohanty** [comment]
This is fixed as we have a single Vagrantfile for all providers. Closing this.
