### ISSUE TITLE
CDK 2.1 RC2 has version 2.0 in /etc/os-release

### ISSUE THREAD

**Issue by dkutalek** [projectatomic/adb-atomic-developer-bundle#441]
SSIA, we need to bump version number in /etc/os-release.
This is also used to report by vagrant-service-manager.

**Comment by praveenkumar** [comment]
@dkutalek I am not seeing this with RC2 can you please remove older box and then check one more time

```
VARIANT="Container Development Kit (CDK)"
VARIANT_ID="cdk"
VARIANT_VERSION="2.1"
```

**Comment by dkutalek** [comment]
Ah, bad box used, sorry for confusion. Closing
