### ISSUE TITLE
Link getting CDK via developers.redhat.com in docs

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#444]
in quickstart steps at multiple places in docs, we have asked to  `Get latest CDK box (Using Developer Subscription)` . The instruction needs to be linked to respective blog page where dev can latest CDK box.

**Comment by rkratky** [comment]
Tracking in https://issues.jboss.org/browse/RHDEVDOCS-51

**Comment by navidshaikh** [comment]
@LalatenduMohanty mentioned this link http://developers.redhat.com/products/cdk/overview/ for getting CDK.

**Comment by rkratky** [comment]
@navidshaikh, Reading this again, I realized I'm not sure... Is this about docs at http://developers.redhat.com/products/cdk/overview/ or about docs at https://access.redhat.com/documentation/en/red-hat-container-development-kit/version-2.0/installation-guide/installation-guide ?

**Comment by navidshaikh** [comment]
@rkratky : This is about README we have for different components in ADB docs, the doc in question is https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/rhel/rhel-ose#quickstart 

What I wanted to mention is that, for text "Get latest CDK box (Using Developer Subscription)." in Quick start section of [this README](https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/rhel/rhel-ose#quickstart), we should link it to [this page](http://developers.redhat.com/products/cdk/overview/) or whichever is more applicable.

The intended fix for this feature will land in ADB docs.

You can read this related conversation that happened at this PR review https://github.com/projectatomic/adb-atomic-developer-bundle/pull/443#discussion_r66921570, which led to this issue creation.

**Comment by rkratky** [comment]
@navidshaikh, thanks for the clarification. It was a misunderstanding on my part.
