### ISSUE TITLE
Adding documentation to run the Vagrant box on libvirt

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#45]
<a href="https://github.com/nitishb"><img src="https://avatars.githubusercontent.com/u/2337217?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nitishb](https://github.com/nitishb)**
_Saturday Jul 18, 2015 at 07:05 GMT_
_Originally opened as https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/pull/45_

---

---

_**[nitishb](https://github.com/nitishb)** included the following code: https://github.com/LalatenduMohanty/centos7-container-app-vagrant-box/pull/45/commits_

**Comment by LalatenduMohanty** [comment]
cc @nitishb

**Comment by bexelbie** [comment]
@nitishb Did you get this worked out for Ubuntu?

Note: This appeared to be an Ubuntu issue - needs testing for confirmation

**Comment by bexelbie** [comment]
@nitishb please reopen if this is not resolved.
