### ISSUE TITLE
ISO images for ADB

### ISSUE THREAD

**Issue by concaf** [projectatomic/adb-atomic-developer-bundle#454]
Hey,

I was looking forward to install ADB on bare metal, or on some other non-supported cloud provider, an `.iso` image would really help me with that.

Is there something like this on the project's roadmap?

**Comment by praveenkumar** [comment]
@containscafeine 
ADB box = CentOS7 + kubernetes + adb-utils so if you want ADB setup in bare metal then install CentOS-7 and then required packages and finally adb-utils.

Give it a try and let us know if you have any issue.

**Comment by concaf** [comment]
@praveenkumar, I was suggesting something like an automated installation for ADB on bare metal, so if a user has to move his workflow from development (vagrant) to production (bare metal/cloud provider), he'd just install using the iso image, get prompted if he wants to install k8s/oc/marathon environment during OS installation, and move on to replicating his development exactly to production.

Something like a Fedora/CentOS/RHEL spin-off for ADB?

> ADB box = CentOS7 + kubernetes + adb-utils so if you want ADB setup in bare metal then install CentOS-7 and then required packages and finally adb-utils.

I agree I can do this, but I was suggesting an ISO deliverable from the ADB team, and if that was on the road map?

**Comment by praveenkumar** [comment]
@containscafeine Then I would say have a ansible playbook for different provider and after user put CetnOS then he can use this for provision as per his requirements. Does that make sense?

**Comment by concaf** [comment]
@praveenkumar yep, ansible playbooks would make more sense in this case, thanks! :)
