### ISSUE TITLE
Doc update for proxy support

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#460]
Recently we did some work from adb-utils (https://github.com/projectatomic/adb-utils/pull/150) side to support proxy but we also need to update our documents to make sure user understand how to use this feature.

**Comment by LalatenduMohanty** [comment]
Here is the change in Vagrantfile for proxy https://gist.github.com/praveenkumar/6aad634ba038044865bea9557631d74e#file-adb_vagratfile-L78
