### ISSUE TITLE
Container-tools trello board seems to be outdated

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-atomic-developer-bundle#468]
Hi,

The [container-tool](https://trello.com/b/j1rEolFe/container-tools) trello board seems to be not active now a days. 

However, the doc's [What is full feature-set](https://github.com/projectatomic/adb-atomic-developer-bundle#what-is-full-feature-set) section mention its reference.

I believe we should replace it will some active board(is there any?) or if such board is not present if should remove it as I found it as a negative impact on new user. 
I hope, we don't want to give an impression that we have not worked since feb/march(in progress cards last updated months).

**Comment by LalatenduMohanty** [comment]
@budhrg at this point we are not using any Trello board for ADB. We are just operating from this github project.So the future roadmap should be part of this repository.
