### ISSUE TITLE
Update usage doc to Document OpenShift configurations as only works if we mention all three options

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-atomic-developer-bundle#489]
Hi,

Due to this [issue](https://github.com/projectatomic/vagrant-service-manager/issues/366), update existing existence to warn users that it will only work if all three options are provided.

**Comment by thatdocslady** [comment]
@budhrg is this issue resolved? I see some PRs that are closed but it's a bit tricky to navigate the commit/comment trees. Please let us know if there is additional doc support that you need :)

**Comment by brgnepal** [comment]
@thatdocslady Ya it is been resolved now. Thanks for pointing it out. :smile: . Will close this issue.
