### ISSUE TITLE
flannel package in box

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#49]
Since we are using a single box  as k8s master and node, we do not need flannel package in the box.
flannel to be used for overlay network provisioning connection between containers pinned on different k8s nodes.
Thoughts?

**Comment by LalatenduMohanty** [comment]
@navidshaikh But we will go to the route when we use multiple boxes to have a master and one or two node setup. We are most likely to use https://github.com/purpleidea/oh-my-vagrant for that. So I am inclined to close this issue as a non-issue.  Thoughts? CC @whitel @kbsingh

**Comment by langdon** [comment]
So, I would rather have my development boxes be as close to production as possible. As a result, I would be inclined to keep flannel as even though it is not (particularly) useful, it ensures that the code I am running is operating correctly in something as similar as possible to production.

**Comment by LalatenduMohanty** [comment]
Closing this as per above discussion.
