### ISSUE TITLE
python-netifaces should be part of centos tree or atomic tree

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#492]
With enable of proxy support now `adb-utils` package have `python-netifaces` as run time dependency which will break adb box creation if that is not present in respective repo section: https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/build_tools/build_scripts/do_vagrant_cbs.sh#L17-L19

Package is already available in cbs: https://cbs.centos.org/koji/buildinfo?buildID=961

**Comment by LalatenduMohanty** [comment]
Added to below targets.

```
atomic7-adb-common-candidate
atomic7-adb-common-release
atomic7-adb-common-testing
```
