### ISSUE TITLE
Vagrant failed to initialize at a very early stage , due to version upgrade (Documentation note)

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#500]
Vagrant failed to initialize at a very early stage , due to version upgrade (Documentation note)
Hi @Preeticp @praveenkumar ,
Logs link : https://gist.github.com/naina-verma/25110683f570ecdf4921ac8010c89c63

This Error occurred when user upgrade from vagrant older version (1.7.4 ) to (1.8.*) . A doc Note would be good which  point  to remove older meta data. By doing following steps:
1. uninstall vagrant 
2. remove this C:/Users/cdk/.vagrant.d/ directory 
3. install 1.8.1 or 1.8.5

**Comment by thatdocslady** [comment]
Hi @naina-verma I'll be documenting this, can you help by providing some distro/env information? We should estimate whether this is a problem that's relevant only for certain distros or global.

Also, would this be a candidate for a code bug fix, or something that we should accept as a permanent limitation?

Thanks!

**Comment by naina-verma** [comment]
@thatdocslady ,
This problem is on Windows machine , this issue comes into picture when some one upgrade there system form vagrant 1.7.4 version to 1.8.1 or 1.8.\* .
Few of the binaries are not supported for those versions . So few sequential steps are required to achieve a clean up and running  setup;
Those steps are:
1. uninstall vagrant
2. remove this C:/Users/{username}/.vagrant.d/ directory {rm -rf C:/Users/{username}/.vagrant.d/ }
3. install 1.8.1 or 1.8.5

**Comment by thatdocslady** [comment]
@naina-verma @bexelbie can you please review PR #514 :)

**Comment by LalatenduMohanty** [comment]
Ideally this issue should be reported in Upstream Vagrant Or we can create a trouble shooting document to address these kind of issues.

**Comment by naina-verma** [comment]
@thatdocslady , #514  looks good to me !

**Comment by thatdocslady** [comment]
@LalatenduMohanty I understand and agree, but at this point we're on the verge of a full restructuring of the doc set so creating a troubleshooting/known issues document will happen then. In the meantime, this is the best section that we have to hold this information.

**Comment by LalatenduMohanty** [comment]
@thatdocslady In that case if we have an issue to track what we agreed here , it should be fine to put the documentation as per the PR.

**Comment by thatdocslady** [comment]
@LalatenduMohanty created #524 to address this and future "we shouldn't forget to do this" tasks :)

**Comment by bexelbie** [comment]
@naina-verma @LalatenduMohanty 

> Ideally this issue should be reported in Upstream Vagrant 

Did this get reported upstream?  It seems odd that this is required on such a significant platform.  Is this for all upgrades or just ones driven by atlas or cloud.centos/access.rh?

**Comment by naina-verma** [comment]
@bexelbie @thatdocslady ,

I have not reported it into Vagrant Upstream, I expect it should be  in known issues , if some user face this kind of issue for windows.

**Comment by thatdocslady** [comment]
@naina-verma can you please clarify whether this step is required in all update scenarios or just for centos/rh images? thanks!

**Comment by bexelbie** [comment]
> I have not reported it into Vagrant Upstream, I expect it should be in known issues , if some user face this kind of issue for windows.

@naina-verma can you help me understand what breaks here?  I am trying to understand why this is a failure for ADB and not for vagrant.  If it is a vagrant failure I think we have both an obligation to report it and to point to their upstream report.  An inability to upgrade on windows is a significant failure for vagrant.

**Comment by naina-verma** [comment]
@bexelbie ,
This issue was observed in the CDK , when i migrated my system from 1.7.4 vagrant to 1.8._.,
 the C:/Users/{username}/.vagrant.d/ directory {rm -rf C:/Users/{username}/.vagrant.d/ }. these files create trouble to perform Vagrant commands (say vagrant version).
So,I was suggesting it to doc team to put up it in known issues . If user triggers the same things on there laptop after migration  from 1.7.4 vagrant to 1.8._. they can perform set of operations as below :  
1.  uninstall vagrant
2.  remove this C:/Users/cdk/.vagrant.d/ directory
3.  install 1.8.1 or 1.8.5

This is the similar issue in Vagrant upstream : https://github.com/mitchellh/vagrant/issues/6987.Its been closed now due to less responses.

**Comment by brgnepal** [comment]
Closed via https://github.com/projectatomic/adb-atomic-developer-bundle/pull/514
