### ISSUE TITLE
Proxy support  k8 vagrantfile is missing 

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#509]
Proxy support  k8 vagrantfile is missing 

Either it should be mentioned in document (k8 there is no proxy support ) or put up proxy support in k8 vagrant file .

**Comment by praveenkumar** [comment]
@naina-verma Can you try https://gist.github.com/praveenkumar/6aad634ba038044865bea9557631d74e and see if that works for you?

**Comment by naina-verma** [comment]
@praveenkumar , looks good to me !

**Comment by praveenkumar** [comment]
@budhrg you have any suggestion?

**Comment by brgnepal** [comment]
LGTM too :+1:
