### ISSUE TITLE
Vagrant up on rhel-ose vagrant file fails while starting openshift service

### ISSUE THREAD

**Issue by pavanbhat21** [projectatomic/adb-atomic-developer-bundle#510]
Vagrant up fails while starting the openshift service on a RHEL machine with the below error:

```
==> default: Job for openshift.service failed because the control process exited with error code. See "systemctl status openshift.service" and "journalctl -xe" for details.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

We can note that the system has enough resources, 8gigs memory and free meomry can be seen below

```
[pavan@hp-ms-01-c15 rhel-ose]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7807        1548        5089          16        1169        6024
Swap:          8063           0        8063
```

The above issue is noted on CDK 2.2 RC build with below vagrant plugins:

```
landrush (1.1.1)
  - Version Constraint: 1.1.1
vagrant-libvirt (0.0.32, system)
vagrant-registration (1.2.3)
  - Version Constraint: 1.2.3
vagrant-service-manager (1.3.0)
  - Version Constraint: 1.3.0
vagrant-sshfs (1.2.0)
  - Version Constraint: 1.2.0
```

**Comment by pavanbhat21** [comment]
To add to the above, the openshift service is started a few minutes later and the vm will be up and running.

**Comment by praveenkumar** [comment]
@pavanbhat21 As far I tested, it was working fine and looks like your test env had some issue. Can you confirm once that it is resolved now?

**Comment by pavanbhat21** [comment]
@praveenkumar I could not reproduce the issue on a different machine. That said, on the original machine it still fails every time while doing vagrant up, but vagrant reload and vagrant halt/up work absolutely fine.

**Comment by praveenkumar** [comment]
@pavanbhat21 So as per our discussion and we did testing on 2 different new RHEL setup successfully, I am closing this issue. If you again hit on same issue then please re-open.
