### ISSUE TITLE
No success message after vagrant up for rhel-k8s-singlenode-setup 

### ISSUE THREAD

**Issue by naina-verma** [projectatomic/adb-atomic-developer-bundle#512]
No success message after vagrant up for rhel-k8s-singlenode-setup

Steps to reproduce 
1. go to /cdk/components/rhel/misc/rhel-k8s-singlenode-setup
2. do vagrant up 
3. yes to registration or no (same behavior ) 

_Expected_ : 
it is not showing any successful configuration message for k8 single node as it give for rhel-ose

_Actual result_ : 
`default: Running provisioner: shell... default: Running: inline script`
It should give message at end `k8-single-node-setup configured successfully` as it gives for rhel-ose vm 
logs : https://gist.github.com/naina-verma/b63d1c2cf6ef28f3bda0f078099edb04

**Comment by brgnepal** [comment]
@naina-verma @praveenkumar 
Closing this issue as it is actually VSM issue since we are now migrating from Shell provisioning method to VSM configuration way. Created here https://github.com/projectatomic/vagrant-service-manager/issues/379.
