### ISSUE TITLE
landrush plugin prevents Eclipse server adapter from starting

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#513]
From: https://issues.jboss.org/browse/JBIDE-23010

The landrush plugin holds stderr and stdout open for the spawned DNS server.  Eclipse uses the closure of those streams to indicate complete book of the ADB.  This is similar to the issue encountered with vagrant-sshfs.

See the JIRA above for discussion on whether this should be fixed at all.

This program can be used to test and verify the issue: 

https://gist.github.com/jeffmaury/ba61c91fe910220585e9893540ccec7d

To use it:
1. Remove the package line at the top of the file - it's not needed
2. Compile it with `javac -cp . VagrantLauncher.java`
3. Execute it as `java -cp . VagrantLauncher path_to_vagrant path_to_cdk_folder $SUB_USERNAME $SUB_PASSWORD`
- The first argument is the path of the vagrant bin
- The second argument is the path of the CDK folder (where the Vagrant file is)
- The third argument is the user for registration
- The fourth argument is the password for registration

An issue has been opened in landrush: https://github.com/vagrant-landrush/landrush/issues/249

**Comment by bexelbie** [comment]
Note: This is only affecting Mac and Linux

**Comment by bexelbie** [comment]
PR proposed here: https://github.com/vagrant-landrush/landrush/pull/250

**Comment by bexelbie** [comment]
Test Gem: http://file.brq.redhat.com/~bexelbie/landrush-1.1.2.gem

**Comment by brgnepal** [comment]
@bexelbie @praveenkumar I have tested the given `1.1.2.gem` above using the `VagrantLauncher.java` program

Found that output and error thread are dead and command finishes.

```
.....
ERROR> INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x000000019ec5e0>
ERROR> INFO interface: Machine: action ["up", "end", {:target=>:default}]
ERROR> INFO environment: Released process lock: machine-action-2f64d12f67f4d478f9a7f9a17d58d7d8
ERROR>DEBUG environment: Attempting to acquire process-lock: dotlock
ERROR> INFO environment: Acquired process lock: dotlock
ERROR> INFO environment: Released process lock: dotlock
ERROR> INFO environment: Running hook: environment_unload
ERROR> INFO runner: Preparing hooks for middleware sequence...
ERROR> INFO runner: 2 hooks defined.
ERROR> INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000002c129b8>
waitFor returned:0
output thread died
error thread died
##### Command finished here
```

My vagrant plugin list:

```
$ vagrant plugin list
landrush (1.1.2)
  - Version Constraint: 1.1.2
vagrant-libvirt (0.0.35)
vagrant-registration (1.2.3)
vagrant-service-manager (1.3.0)
vagrant-share (1.1.5, system)
vagrant-sshfs (1.2.0)
```

**Comment by bexelbie** [comment]
landrush 1.1.2 has been released to rubygems and can be installed via `vagrant plugin update landrush`.

This gem should resolve this bug.

**Comment by LalatenduMohanty** [comment]
@bexelbie can we close this bug now that it is resolved now?

**Comment by bexelbie** [comment]
@LalatenduMohanty If we have hte official happy-dance from QE, yes.  I consider it resolved.

**Comment by LalatenduMohanty** [comment]
Closing the issue as I am sure this got resolved. Please reopen if this is not fixed for you.
