### ISSUE TITLE
Docs convergence suggestion box

### ISSUE THREAD

**Issue by thatdocslady** [projectatomic/adb-atomic-developer-bundle#524]
This issue is a bucket to capture suggestions, ideas, and proposals that come up "as we work" in this repo, regarding content structure and things that should be addressed during the migration. 

Please include link issue # or PR # for easier tracking.

**Comment by thatdocslady** [comment]
Related to issue #500 and addressed in a conversation with @LalatenduMohanty - we should create a troubleshooting/FAQ for installation and upgrades and move the note from the general updating section.

**Comment by Preeticp** [comment]
Remove article before the product name, in all docs in the ADB umbrella project. The ADB>ADB. Exceptions: 'The ADB project', 'The ADB vagrant box' and 'The ADB Vagrantfiles'.

**Comment by Preeticp** [comment]
Clean up references wrt Fedora 22 in all the docs, refer #508

**Comment by thatdocslady** [comment]
Restructure installation and usage docs to get rid of mega-deep-nested bullet lists, following work that was done on PR #552.

**Comment by thatdocslady** [comment]
Adjust some tagging conventions to align with downstream (or some compromise in the middle as needed), downstream asciidoc style guide is on GitLab

**Comment by Preeticp** [comment]
We do not have cross links bet some of the docs within the repository, such as the troubleshooting/the staging/building/cockpit docs. We could explore having a list of related docs at the end of each doc to help users know these docs are available and this is where they can/might want to go next. Also the contributing doc needs to be linked to the readme in the Interested in Contributing to this project section.
