### ISSUE TITLE
Update SSH Usage Section

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#526]
https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/using.rst#using-the-box-via-ssh

Suggested changes:
1. Do not suggest that this is hte preferred usage method anymore
2. Move `sccli` usage into a section called Using Orchestrators like OpenShift and Kubernetes and then include examples of both `kubectl` and `oc`
3. Reduce atomicapp/nulecule section to basics and refer to their repos
4. In the `docker` section eliminate references to specific orchestrators

**Comment by thatdocslady** [comment]
@bexelbie @praveenkumar @budhrg can one of you provide examples for kubctl and oc for point 2 in the issue?
