### ISSUE TITLE
Add documentaion for using OpenShift registry on ADB 

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#547]
Refer: https://github.com/projectatomic/adb-atomic-developer-bundle/issues/372

Please check the below command output and you can see `export DOCKER_REGISTRY=hub.openshift.adb` which can used by user to push docker images. But we need to add more documentation about how it can be used.

```
[lmohanty@LalatenduM-laptop centos-openshift-setup]$ vagrant service-manager env

# docker env:
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://192.168.121.67:2376
export DOCKER_CERT_PATH=/home/lmohanty/vagrantboxes/adb/adb-atomic-developer-bundle/components/centos/centos-openshift-setup/.vagrant/machines/default/libvirt/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.22

# openshift env:
# You can access the OpenShift console on: https://192.168.121.67:8443/console
# To use OpenShift CLI, run: oc login https://192.168.121.67:8443
export OPENSHIFT_URL=https://192.168.121.67:8443
export OPENSHIFT_WEB_CONSOLE=https://192.168.121.67:8443/console
export DOCKER_REGISTRY=hub.openshift.adb
```

**Comment by LalatenduMohanty** [comment]
Refer : http://developers.redhat.com/blog/2016/06/27/red-hat-container-development-kit-2-1/

**Comment by thatdocslady** [comment]
@LalatenduMohanty @praveenkumar I wrote a draft of this workflow based on the blog post, but before I submit the PR I wanted to verify/clarify the use-case: Is this something we recommend users do in order to test the app? If so, I'd like to create a new doc file called "testing.adoc" and have it separate from the "using.adoc". 

Actually regardless, I would like to create this in a separate file because the future-thinking is to have more modular topics and currently using.adoc is a big-long-monster thing that should be broken down eventually.

WDYT?

**Comment by praveenkumar** [comment]
>  Is this something we recommend users do in order to test the app?

This is how to use openshift exposed registry so might be called as `registry_usage.adoc`. @LalatenduMohanty wdyt?

**Comment by LalatenduMohanty** [comment]
@praveenkumar @praveenkumar lets call it `registry.adoc`. Keeping it as a minimal name will help I think.

**Comment by thatdocslady** [comment]
@LalatenduMohanty @praveenkumar I understand the functionality might demand this, but I'm still trying to figure out the "why" or the use-case. Why would the user want to use this workflow, when is it helpful for them, etc. This might affect the overall "label" of the topic (of course the file name is less important but it affects the title and introduction of the topic as well).

**Comment by praveenkumar** [comment]
>  Why would the user want to use this workflow, when is it helpful for them, etc.

User need this workflow if he/she wants to push local docker builds to openshift registry and then use it for application which they want to deploy. it is helpful to test local images without pushing it to some hub and testing with openshift.

Usually when we deploy an app on openshift, it first check if the image present in the registry then according to that take action. Let me know if you still have query.

**Comment by LalatenduMohanty** [comment]
> User need this workflow if he/she wants to push local docker builds to openshift registry and then use it for application which they want to deploy. 

Right. There are various ways we can deploy an application in OpenShift and using an image is one of the way. The image can be in the local OpenShift registry which can be populated by the user . Refer: https://docs.openshift.org/latest/dev_guide/new_app.html#specifying-an-image
