### ISSUE TITLE
cdk.zip should include a .cdk file in same folder as Vagrantfile

### ISSUE THREAD

**Issue by praveenkumar** [projectatomic/adb-atomic-developer-bundle#550]
Content of this file should be the following type:

openshift.auth.scheme=Basic
openshift.auth.username=openshift-dev
openshift.auth.password=devel

It would also be nice if we were able to include a version here, but as I understand it, the version of the CDK is based on the box that's installed, yes? Not the cdk.zip file or the Vagrantfile?

However, if you were able to add a versioning key here, if we could assume a user is downloading CDK as one, it would be very helpful for our usecase.

Our usecase in JBossTools is to automatically detect CDK installations. Issue is to be linked.

Source: https://issues.jboss.org/browse/CDK-15

**Comment by hferentschik** [comment]
> It would also be nice if we were able to include a version here, but as I understand it, the version of the CDK is based on the box that's installed, yes? Not the cdk.zip file or the Vagrantfile?

That's right. I actually think it is misguided. There is no deterministic way to get the CDK version prior to starting up. IMO, the right way is to use "unkown" (or something similar) until the VM is stated and then use for example 'vagrant service-manager box' to determine and set the version of the CDK.
