### ISSUE TITLE
Cleanup tasks to prepare for docs publication

### ISSUE THREAD

**Issue by thatdocslady** [projectatomic/adb-atomic-developer-bundle#553]
Following the asciidoc conversion, there are some tasks that still need to be performed on the overall doc set in order to get it ready for publication:
- Update and formalize permalink IDs (for each h2, h3). Currently they're auto-generated in the asciidoc files, but because they will ultimately end up in the URL breadcrumbs it's probably a good idea to review them and make sure they're concise and accurate (it'll be harder to change later and if we can avoid redirects that's a good thing (tm) ).
- Cross-document (and some cross-repo) links currently refer to the adoc files. We need to replace these with the published URLs (this should probably wait until we do a test publication and have the full URL), otherwise users will end up in the GH files instead of the published content.

**Comment by hferentschik** [comment]
> Cross-document (and some cross-repo) links currently refer to the adoc files. We need to replace these with the published URLs (this should probably wait until we do a test publication and have the full URL),

Links across the various documents need to stay relative. The asciidoc(tor) converted will take care that in the HTML version the links points to the correct HTML file. Referencing across internal pages in an absolute manner would be hard to maintain and also prevent us to move the docs to any destination we want.

**Comment by hferentschik** [comment]
That said, the docs contain links of the form `https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/docs/installing.adoc[ADB installation]`. This is something which needs to be addresses. Links between documents (at least withing the docs directory) need to be relative.

**Comment by thatdocslady** [comment]
Following the discussion and some comments (example https://github.com/projectatomic/adb-atomic-developer-bundle/pull/552#discussion_r81923940), links between books should stay relative and we need to look into a way to parse them automatically during site building so that they point to the HTML accordingly.

Note that this will probably only work if all the docs are in the same repo, so a link from ADB to VSM won't be able to be auto-generated.

**Comment by hferentschik** [comment]
> Note that this will probably only work if all the docs are in the same repo, so a link from ADB to VSM won't be able to be auto-generated.

We should use as few as possible of these type of links. 

Another thing which needs to be addressed is the use of links for Vagrantfiles and other source material of the repo. At least the READMEs contain a lot of them. In the docs, the content must either be in-lined or a copy of the configuration file needs to be added to the docs directory and dynamically included/referenced. Personally, I prefer in-lining the examples as much as possible, since I then don't have to jump between pages.
