### ISSUE TITLE
Enable live-rendering of TOC in GitHub for adoc files

### ISSUE THREAD

**Issue by thatdocslady** [projectatomic/adb-atomic-developer-bundle#556]
Following the merge of PR #552, adoc files do not show live-rendered TOC in GitHub. VSM repo does have this, but initial attempts to replicate the tagging structure didn't work, and now there's a need for deeper investigation to find out why and how to fix this in ADB repo.

**Comment by bexelbie** [comment]
Can you provide more context on this @thatdocslady ?  Why do we need live TOC rendering in AsciiDoc in the Repo?

**Comment by bexelbie** [comment]
also see https://github.com/johnnyutahh/search-based-email/edit/master/README.adoc

**Comment by hferentschik** [comment]
> Why do we need live TOC rendering in AsciiDoc in the Repo?

I don't consider it essential in the /docs directory. Not if we are able to build and publish a static version of it. The READMEs are a different story. They are essential part of the experience of the GitHub repo as well. Having no TOC for the README makes it really hard to navigate this content.

Maybe we need to differentiate between the set of documents which make up the published docs and other files, like the various READMEs.

Note, since we are not having a published version of the docs yet, merging the existing conversion to asciidoc is imo a degradation of the user experience.

**Comment by bexelbie** [comment]
@hferentschik I think we are in agreement that we should have live rendering in the READMEs but not hte docs sub-dir.

**Comment by hferentschik** [comment]
> I think we are in agreement that we should have live rendering in the READMEs but not hte docs sub-dir.

Right. Live rendering in the docs would be nice, but most likely there will be other things which will prevent a user to get a consistent experience. For example, I would assume we will add some variables (for example the tag/version we are building). This variable will probably then be used in various links etc. This would be broken in the GitHub version. 

One thought so, if it proves to be easy to have rendering of the TOC (and it we agree that we at least should have it for the READMEs and we also know it is possible), we should consider to also enable it for the documents under /doc, at least until we are at a stage were we can publish the docs.

**Comment by bexelbie** [comment]
I can see allowing live TOC in the docs in docs/ as a **temporary** stop-gap if it is relatively simple.  I will be focusing on this publication to get us publishing ASAP.  I just got caught a conference this week talking about our awesomeness :)

**Comment by hferentschik** [comment]
> I can see allowing live TOC in the docs in docs/ as a temporary stop-gap if it is relatively simple

+1 :-)

**Comment by thatdocslady** [comment]
@hferentschik @bexelbie @Preeticp it seems that the hack wasn't as ugly as it seemed, and I was able to create the TOC rendering in the major doc files. I suspect that it was failing mainly due to the massive amount of work I was doing on the PR last week and now that the "hairball" is smaller it was easier to untangle.

Anyway, PR #558 is ready for review :)
