### ISSUE TITLE
Docs Cleanup post asciidoc conversion

### ISSUE THREAD

**Issue by Preeticp** [projectatomic/adb-atomic-developer-bundle#560]
This Issue lists cleanup tasks in the Installing and Using docs, resulting from conversion of docs to Asciidoc:
1. installing.adoc: This doc had numbered second level headings as they are actually Steps to be run in an order.  The last heading: Setup ADB behind proxy however has no numbering,  I am wondering if this should be added before the Vagrant up step or maybe a note. WDYT?
2. using.adoc: 
- Using ADB with host-based tools (Eclipse and CLIs); Line36 has a dashed line (RAW format)which makes the entire doc below it grey, though on rendering I see no problem.
- Step 7. If you are using Eclipse, you should follow these steps:
  Install the Docker Tooling plugin. ,.  Enable the three Docker Views (Docker Explorer, Docker Containers, and Docker Images) by choosing Windows→Show Views→Others.
  These are 2 steps and the dot before Enable is for auto numbering in adoc.
- Windows→Show Views→Others, Docker explorer, connection name are all rendered differently let us fix one style for these GUI Labels. Maybe a simple Bold text for all GUI Labels? (I think this is a legacy issue, and not a result of the conversion. Just noting it here so that we know that this issue exists.)
- Alignment of Note in using.adoc step 7 needs to be corrected.
- Line 198 sccli readme is in rst, but has been changed to adoc. So do we revert to rst as link is broken currently, until there is a decision on the Plugin Conversions #557 

We can add other tasks here for other docs as the reviews happen.

**Comment by thatdocslady** [comment]
@Preeticp thanks for the review! Fixed most, here are some open questions:
1. I can bring back the numbered steps, but having the proxy heading stand-alone without a number makes it indeed seem out of place. At which point in the process is it needed? I assume it's an optional step, but maybe we can number it and just write "optional" as a prefix. Even optional steps should have the correct location in the main task.
2. using.adoc:
- I don't see the offending dashed line that you mention, and when I open the file, line 36 isn't in that section. I also don't see any problem in the rendering, maybe you can quote the text in the line so I can search for it in the file?
- Yes, all GUI elements should appear as bold. Again, I'm not sure where you see the problematic rendering, I'm testing the adoc file locally with asciidoctor FF plugin and also looking at the live-rendered GitHub and it looks fine.
- It looks like we're going to get an agreement on the adoc conversion for plugin docs so I'll keep the url for sccli for now. Worst case will revert later.

**Comment by Preeticp** [comment]
> 1. I can bring back the numbered steps, but having the proxy heading stand-alone without a number makes it indeed seem out of place. At which point in the process is it needed? I assume it's an optional step, but maybe we can number it and just write "optional" as a prefix. Even optional steps should have the correct location in the main task.

While it is optional, most of our target audience is likely to encounter this as they will be working behind a proxy. I feel this would be better off as a note, as an user will encounter this problem after he does vagrant up the first time, @praveenkumar can you please confirm. Making it as a note would highlight the section as well as resolve the numbering problem. I would place the note where it is at the moment, @praveenkumar hope I have got this right.

> 1. using.adoc:
> 
> I don't see the offending dashed line that you mention, and when I open the file, line 36 isn't in that section. I also don't see any problem in the rendering, maybe you can quote the text in the line so I can search for it in the file?

You may be able to see it in the blame format I think. Please see below the heading mentioned below: 
41  [[using-adb-with-host-based-tools-eclipse-and-clis]]
42  Using ADB with host-based tools (Eclipse and CLIs)
43  --------------------------------------------------
It is the line preceeding: Many users have preferred development environments built from tools

> Yes, all GUI elements should appear as bold. Again, I'm not sure where you see the problematic rendering, I'm testing the adoc file locally with asciidoctor FF plugin and also looking at the live-rendered GitHub and it looks fine.

This is the section I see it in:
If you are using Eclipse, you should follow these steps:
173 ..  Install the
174 http://www.eclipse.org/community/eclipse_newsletter/2015/june/article3.php[Docker
175 Tooling] plugin.
176 ,.  Enable the three Docker Views (Docker Explorer, Docker Containers,
177 and Docker Images) by choosing **Windows->Show Views->Others**.

**Comment by thatdocslady** [comment]
> While it is optional, most of our target audience is likely to encounter this as they will be working behind a proxy. I feel this would be better off as a note, as an user will encounter this problem after he does vagrant up the first time

@Preeticp I'm not sure placing the proxy steps as a note would be a good idea because then they won't show up in the TOC and if they are important they deserve a heading. If this is indeed a common use-case, then I recommend giving it a number in the appropriate stage of the task and rephrasing the beginning paragraph as "If you are...<etc>".

**Comment by thatdocslady** [comment]
Following fixes to issue #557, need to find and fix all links to plugin docs to point to new adoc files.

**Comment by praveenkumar** [comment]
> @praveenkumar can you please confirm?

proxy variable only need to set when user are behind proxy so may be best to have in TOC and marked as optional so only concerned user follow it.

**Comment by thatdocslady** [comment]
@praveenkumar ok so I can mark it as an optional step, but I'm still thinking it's better to number it and place it in the correct place in the workflow.

**Comment by Preeticp** [comment]
@thatdocslady discussed this with @praveenkumar, seems the current location is fine, the proxy section should go in as the last step and it has to be marked as optional.

**Comment by Preeticp** [comment]
@thatdocslady all other docs seem to be clean and unaffected by the .adoc conversion.
Just a suggestion: For the Readme heading, Advantage of ADB, can we think of replacing it with The ADB edge/ADB Features?

**Comment by thatdocslady** [comment]
@Preeticp not sure what would be the benefit of replacing that heading, I chose it based on the other headings in the document (we already have "why use ADB" and "what's included/full features". The top section is basically highlights, and I don't know about using the word "edge" because it's a bit slangy.

**Comment by Preeticp** [comment]
Agreed @thatdocslady, we can look into overhauling the headings in the next version/during convergence as discussed.
