### ISSUE TITLE
Add OCP tag, registry information to the RHEL-OSE Vagrantfile

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#568]
Next release of adb-utils [1] will support changing the tag of OCP and the next `vagrant up` will use the new docker images.  We need to add these options [2] to the RHEL-OSE Vagrantfile.

[1] https://github.com/projectatomic/adb-utils/issues/185
[2] https://paste.fedoraproject.org/456539/70490851

**Comment by praveenkumar** [comment]
@LalatenduMohanty I will suggest only add Image tag not the registry and Image name because for CDK images are OSP and it going to come from `access.registry.redhat.com` and name will also `ose`.

**Comment by LalatenduMohanty** [comment]
@praveenkumar agree.

**Comment by praveenkumar** [comment]
@LalatenduMohanty I think we already agreed on it and implemented this feature, so closing it now.
