### ISSUE TITLE
Consistent format for setting Vagrantfile configurations

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-atomic-developer-bundle#570]
Currently, we are using two formats in Vagrantfile for setting configurations
- Using `if` block as

```
if ENV.has_key?('SUB_USERNAME') && ENV.has_key?('SUB_PASSWORD')
    config.registration.username = ENV['SUB_USERNAME']
    config.registration.password = ENV['SUB_PASSWORD']
end
```
- One liner approach as

```
ENV['PROXY'] ? (config.registration.proxy = PROXY = ENV['PROXY']) : PROXY = ''
```

First one gives more readability while second option allow to achieve minimal Vagrantfile goal.

Any thoughts which should be used? 

**NOTE**:
`ENV['PROXY']` should be `ENV.key?('PROXY')` (Should be fix as part of this issue fix)

**Comment by praveenkumar** [comment]
@budhrg Let's go with readability, one liner approach looks bit more crypt. @LalatenduMohanty @hferentschik WDYT?

**Comment by LalatenduMohanty** [comment]
+1 For readability.

**Comment by hferentschik** [comment]
+1 For readability
