### ISSUE TITLE
Fix the IMAGE_TAG in rhel-ose Vagrantfile

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#582]
Currently the image_tag has an OCP version i.e. `IMAGE_TAG="v3.3.1.3" ` . However I think it should not contain any version as we have already have a cached version in the Vagrantbox. User should add a version only if a different version of OCP is required in CDK.

**Comment by praveenkumar** [comment]
Fixed by #583
