### ISSUE TITLE
cdk.zip does not contain .cdk marker (again)

### ISSUE THREAD

**Issue by mmalina** [projectatomic/adb-atomic-developer-bundle#587]
Radim Hopp found out today that the .cdk marker which was added in #551 is missing in cdk.zip from 09-Nov-2016.rc1 even though it's included here:
https://github.com/projectatomic/adb-atomic-developer-bundle/tree/master/components/rhel/rhel-ose

It is included in cdk nightly build though.

**Comment by praveenkumar** [comment]
@mmalina I will check the internal script which create zip file. Thanks to notify us.

**Comment by praveenkumar** [comment]
@mmalina It is fixed now I am going to close this issue.

**Comment by mmalina** [comment]
Thanks @praveenkumar . I can confirm that the .cdk marker is included in cdk 2.3.0.rc2 zip
