### ISSUE TITLE
We need some way to create an OpenShift setup for Atomic App

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#66]
We should be able to create an OpenShift instance so that it can be used by Atomic Apps to run.

For example wordpress-centos7-atomicapp [1] should be able to run on OpenShift environment provided by adb.

[1] https://github.com/projectatomic/nulecule/tree/master/examples/wordpress-centos7-atomicapp

**Comment by goern** [comment]
and that is a four node openshift? master, infrastructure, and two nodes? or a just origin container?

**Comment by bexelbie** [comment]
@LalatenduMohanty is this more than just including a containerized version of openshift in the box and box and either always launching it or launching it as needed?  (I am not implying this is a simple task)

**Comment by LalatenduMohanty** [comment]
@goern  @bexelbie  we are planning for an openshift container. @detiber is working on the initial content at https://github.com/detiber/vagrant-minimal-openshift

**Comment by hferentschik** [comment]
My understanding was that even though run as a Docker container, the OpenShift setup is a first class citizen, meaning it is all pre-configured and there are service scripts to control OpenShift (start/stop/etc).

The heavy lifting should not be done via Vagrant config.

The only config part needed is a switch for choosing whether native Kubernetes vs OpenShift should be started per default (as both afaiu should be possible to run on adb, but they cannot coexist).

**Comment by hferentschik** [comment]
So this adds a `Vagrantfile` to configure OpenShift. Is this the indented way now? If so, would you not at least add a script via provisioning to start/stop OpenShift?

**Comment by LalatenduMohanty** [comment]
@hferentschik ADB is behind CDK for these things.  So it is basically a stop gap solution till we have a solution for provisioning built in to the box and wont use the Vagrnatfile. Do you want to raise another issue to track it? I think we should

**Comment by hferentschik** [comment]
> Do you want to raise another issue to track it? 

Yes. I though we already did, but I can create one.

> I think we should

+1

**Comment by hferentschik** [comment]
Here we go - #140
