### ISSUE TITLE
RFE: All-in-one Windows installer

### ISSUE THREAD

**Issue by ncoghlan** [projectatomic/adb-atomic-developer-bundle#77]
It would be great to have a single Windows installer that installed:
- VirtualBox
- Vagrant
- git-for-windows (https://git-for-windows.github.io/)
- the developer bundle itself

I'm not sure how to make such a thing myself, but http://wixtoolset.org/ is the approach that's been recommended to me.

**Comment by bexelbie** [comment]
If this is going to get written, we should include ssh and friends

**Comment by bexelbie** [comment]
Thinking about this more, since the ADB is essentially a vagrant box + vagrant file, I believe this should exist as a separate project.

**Comment by vpavlin** [comment]
I agree with @bexelbie - this should live separately as it does not have to be strictly limited to adb, but basically any vagrant box.

**Comment by ncoghlan** [comment]
I don't mind where it lives, I just think it should exist and include the ADB components :)

**Comment by bexelbie** [comment]
@ncoghlan I think that having it start as a separate project with either ADB rolled in or as part of an option or a fork is best.  Do you want to take point on it?  A quick look around the interwebs didn't show any omnibus installers.  How do you solve the sub-packaging problem?

**Comment by ncoghlan** [comment]
Unfortunately, if I had the skills and time I would have built it, rather than suggesting it be built. The main thing I can contribute is that I know from experience what a big difference the all-in-one Python installers make for folks learning Python on Windows, so if we want to offer a better getting started experience than "Go to sites A, B, C, and D, download these installers, and run them all, and then try to figure out where everything landed so you can hook it together yourself", then finding a way to provide a combined installer where everything is preconfigured to work together is the way to do it.

Fortunately, MSI is designed to handle subpackaging - that's one of the main reasons folks were happy when CPython switched from providing exe's to providing MSI files. I suggested the WiX toolset in particular just because that's the one that CPython switched to when a dev from the MS developer tools team took over creating our installers.

**Comment by LalatenduMohanty** [comment]
Moving the issue to https://github.com/redhat-developer-tooling/developer-platform-install
