### ISSUE TITLE
Move the delivered boxes on https://atlas.hashicorp.com/atomicapp/boxes/dev

### ISSUE THREAD

**Issue by bexelbie** [projectatomic/adb-atomic-developer-bundle#78]
I believe we should use a namespace other than atomicapp on atlas.hashicorp.com

**Comment by LalatenduMohanty** [comment]
@bexelbie Any suggestion about what should be the name space name? adb or may be from projectatomic?

**Comment by bexelbie** [comment]
projectatomic is my vote with a descriptive box name to allow for other boxes that are not ADB to live there too

**Comment by bexelbie** [comment]
@jzb opinion?

**Comment by LalatenduMohanty** [comment]
@bexelbie I have a small discussion with @jzb about it and he is fine with the move. So looks like we are game for moving the box under projectatomic in https://atlas.hashicorp.com/projectatomic and rename it as adb.

CC @whitel @kbsingh @cctrieloff @veillard

**Comment by bexelbie** [comment]
In the October 13 meeting it was decided to move this to the projectatomic namespace.

**Comment by LalatenduMohanty** [comment]
Marking this as done.  As we have moved it to projectatomic/adb
