### ISSUE TITLE
expose ports available from within VM to the host

### ISSUE THREAD

**Issue by goern** [projectatomic/adb-atomic-developer-bundle#82]
## user story

As a developer
I run the CDK and 
I 'atomic run projectatomic/helloapache', 
so that I can access it with my browser running on my laptop 
## rational

As a developer using windows for development, I want to test my new containers on the CDK. Doing this tests will involve looking at the web interface. Most native way: open the browser on the host and have a look at... ja?! where?

**Comment by bexelbie** [comment]
Today, it appears to work that you can access the results of your `atomic run projectatomic/helloapache` on your host web browser by visiting http://<adb IP>/

The challenge is two fold, I think:
1. How do you know the IP of the machine.  You can find it by running `vagrant ssh-config` and may soon get it as an environment variable in your SHELL - but that is not so obvious.  A more obvious solution would be to dynamically add a port_forward, however I am not sure vagrant can do that.

2 - Perhaps the larger question is how do you actually get to run `atomic run projectatomic/helloapache`.  If you run it by first running `vagrant ssh` then I think it is ok to insist that you be able to find the IP address (with some documentation help).  If you run it through a tool then the tool should tell you what to do.

**Comment by navidshaikh** [comment]
in the scope of vagrant-adbinfo plugin
