### ISSUE TITLE
Network configuration for ADB box

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#93]
Vagrant boxes in all providers create a private host-based network.  Containers can expose ports on the IP address of the ADB.  Doing this means that we don't have to pre-define all of those ports in the Vagrantfile.This will allow arbitrary ports to be exposed by containers without requiring a Vagrantfile edit and a  `vagrant reload`.  

This allows developers to add and remove service end points without having to have pre-planned all port accesses.

However by default for Virtualbox (in Wndows/OS X) the host machine can't access the Vagrant box using Vagrant box's IP address. But we can fix them by adding some settings in the Vagrantfile.

This is a change only for Mac/Windows with VirtualBox which was previously only going to do localhost port forwards.

**Comment by bexelbie** [comment]
related #82
