### ISSUE TITLE
Host and box filesystem sync setup

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#94]
Challenge: Source code from the host needs to be available in the ADB
Solution: A two-pronged approach consisting of a "sensible" default and documentation about other options

"Sensible" default: The directory tree that from the vagrant project directory (where the Vagranfile is) will be mounted to ~vagrant in the ADB.  Additionally a symlink to ~vagrant will be created with the same absolute path in the vagrant machine that the vagrant project directory has on the host.

This adds the capability for (ADB consumer) client side tooling (Eclipse) to use their host file browser to select a path on the host to be mounted inside container and the sync setup should make available the location and data from the host to the ADB box, so containers can use it as volumes.

**Comment by bexelbie** [comment]
Note: We also need to think about Eclipse Synchronized Projects
