### ISSUE TITLE
Test and define the providers (recommended) versions

### ISSUE THREAD

**Issue by navidshaikh** [projectatomic/adb-atomic-developer-bundle#95]
Aim is to test the ADB with (stable versions) providers (VirtualBox, VMWare?, libvirt) and recommend the version to be used for provisioning the ADB vagrant box(es). Also document (if any) exceptions for other providers' (latest) versions.

**Comment by bexelbie** [comment]
@navidshaikh @LalatenduMohanty @praveenkumar @strzibny Can you all chime in with the versions?

**Comment by strzibny** [comment]
We have vagrant-libvirt-0.0.32 in Fedora rawhide (the latest) and I don't see a reason not to use it.

**Comment by praveenkumar** [comment]
Currently I have below version of different providers installed in my system.

```
$ rpm -qa | grep libvirt
libvirt-daemon-config-network-1.2.18.1-2.fc23.x86_64
libvirt-client-1.2.18.1-2.fc23.x86_64
libvirt-gobject-0.2.2-1.fc23.x86_64
libvirt-daemon-driver-nwfilter-1.2.18.1-2.fc23.x86_64
libvirt-daemon-driver-qemu-1.2.18.1-2.fc23.x86_64
libvirt-daemon-driver-storage-1.2.18.1-2.fc23.x86_64
libvirt-python-1.2.18-1.fc23.x86_64
rubygem-fog-libvirt-0.0.2-2.fc23.noarch
libvirt-daemon-1.2.18.1-2.fc23.x86_64
libvirt-glib-0.2.2-1.fc23.x86_64
libvirt-gconfig-0.2.2-1.fc23.x86_64
libvirt-daemon-driver-nodedev-1.2.18.1-2.fc23.x86_64
rubygem-ruby-libvirt-0.5.2-4.fc23.x86_64
libvirt-daemon-kvm-1.2.18.1-2.fc23.x86_64
libvirt-daemon-driver-secret-1.2.18.1-2.fc23.x86_64
libvirt-daemon-driver-interface-1.2.18.1-2.fc23.x86_64
libvirt-daemon-driver-network-1.2.18.1-2.fc23.x86_64
vagrant-libvirt-0.0.30-5.fc23.noarch

$ rpm -qa | grep -i virtual
VirtualBox-kmodsrc-5.0.10-1.fc23.x86_64
VirtualBox-5.0.10-1.fc23.x86_64
kmod-VirtualBox-4.2.6-300.fc23.x86_64-5.0.10-1.fc23.x86_64
akmod-VirtualBox-5.0.10-1.fc23.x86_64
```

**Comment by navidshaikh** [comment]
On Windows, 
- `VirtualBox 5.0.8 r103449`
- `Vagrant 1.7.4`

On Mac OS,
- `VirtualBox 5.0.0 r101573`
- `Vagrant  1.7.4`

On Fedora 22,
- `VirtualBox 4.3.34 r104062`
- `Vagrant 1.7.2`

**Comment by LalatenduMohanty** [comment]
@navidshaikh @bexelbie I think we should also mention Eclipse Version on which integration will work. I understand that it should work on any Eclipse version which supports docker tooling, but just providing the information will help IMO.

I have tried `Eclipse 4.5.0`
