### ISSUE TITLE
Defining version of the ADB Vagrant box. 

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#97]
We need a clean way to define the version of the ADB Vagrant box.

**Comment by LalatenduMohanty** [comment]
We are planning for a time based release of every month. So I think we should version it using the [year].[month].[date] format.

The [date] i.e. build date should take care of if we build more than one box in a month ( to address a blocker bug etc)

Also we can tag the github repo with same version number.

**Comment by LalatenduMohanty** [comment]
Or we can version it as [Last two digits of year].[month].[build_number] e.g. For first build of the month : 15.10.1 
And if we need 2nd rebuild in the same month : 15.10.2

**Comment by bexelbie** [comment]
I believe we should have version numbers like 1.x.x and 2.x.x with major revisions at significant changes and minor for minor updates as normal.  While I understand that we are not adding a ton of code to the universe with this project, we are building a synchronized set of binaries configured in a specific manner.  Having version numbers that do more than imply this is simply a point in time build is therefore important.

**Comment by bexelbie** [comment]
@LalatenduMohanty based on the newest release - is this resolved?  Can someone tell from inside the box what version they have?

**Comment by LalatenduMohanty** [comment]
@bexelbie nope. We need to fix this.

**Comment by LalatenduMohanty** [comment]
With https://github.com/projectatomic/adb-atomic-developer-bundle/pull/187  the issue is fixed.
