### ISSUE TITLE
Vagrant image intermittently fails to bring up networking

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-atomic-developer-bundle#99]
ADB box will have the same issue [1]  as CentOS base box as both have similar kickstart file. 
As @karmix  mentioned 

The vagrant box  intermittently fails to bring up networking when used in a configuration with more than one network adapter. This is because the 'eth0' connection profile is not associated with any specific interface. When NetworkManager tries to bring the 'eth0' connection up on a non-eth0 device (that is not on a network with a DHCP server), it logs a failure message such as:

network: Bringing up interface eth0: Error: Connection activation failed: Connection 'eth0' is already active on eth1

[1] reference : https://github.com/CentOS/sig-cloud-instance-build/issues/24

**Comment by LalatenduMohanty** [comment]
The solution is to associate the eth0 in the Vagrant box to eth0 of the host machine

```
# Bind the eth0 connection to the eth0 device (#24)
nmcli connection modify eth0 connection.interface-name eth0
```

Thanks @karmix

**Comment by praveenkumar** [comment]
@LalatenduMohanty Can we close this bug now since we already fixed it?

**Comment by praveenkumar** [comment]
@LalatenduMohanty ping, what it your opinion on this issue?

**Comment by LalatenduMohanty** [comment]
@praveenkumar I have not seen this occurring on ADB . So lets close this.
